# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRMEMC_Test/PRMEMC_Test/PRMEMC_Test.srcs/sources_1/ip/PR_L3PHIC_1/PR_L3PHIC.xci
# IP: The module: 'PR_L3PHIC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRMEMC_Test/PRMEMC_Test/PRMEMC_Test.srcs/sources_1/ip/PR_L3PHIC_1/constraints/ProjectionRouterTop_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PR_L3PHIC'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRMEMC_Test/PRMEMC_Test/PRMEMC_Test.srcs/sources_1/ip/PR_L3PHIC_1/PR_L3PHIC.xci
# IP: The module: 'PR_L3PHIC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRMEMC_Test/PRMEMC_Test/PRMEMC_Test.srcs/sources_1/ip/PR_L3PHIC_1/constraints/ProjectionRouterTop_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PR_L3PHIC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
