// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="MatchCalculatorTop,hls_ip_2019_2_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu7p-flvb2104-1-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.367500,HLS_SYN_LAT=119,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=1,HLS_SYN_FF=1721,HLS_SYN_LUT=6266,HLS_VERSION=2019_2_1}" *)

module MatchCalculatorTop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bx_V,
        match1_dataarray_data_V_address0,
        match1_dataarray_data_V_ce0,
        match1_dataarray_data_V_q0,
        match1_nentries_0_V,
        match1_nentries_1_V,
        match2_dataarray_data_V_address0,
        match2_dataarray_data_V_ce0,
        match2_dataarray_data_V_q0,
        match2_nentries_0_V,
        match2_nentries_1_V,
        match3_dataarray_data_V_address0,
        match3_dataarray_data_V_ce0,
        match3_dataarray_data_V_q0,
        match3_nentries_0_V,
        match3_nentries_1_V,
        match4_dataarray_data_V_address0,
        match4_dataarray_data_V_ce0,
        match4_dataarray_data_V_q0,
        match4_nentries_0_V,
        match4_nentries_1_V,
        match5_dataarray_data_V_address0,
        match5_dataarray_data_V_ce0,
        match5_dataarray_data_V_q0,
        match5_nentries_0_V,
        match5_nentries_1_V,
        match6_dataarray_data_V_address0,
        match6_dataarray_data_V_ce0,
        match6_dataarray_data_V_q0,
        match6_nentries_0_V,
        match6_nentries_1_V,
        match7_dataarray_data_V_address0,
        match7_dataarray_data_V_ce0,
        match7_dataarray_data_V_q0,
        match7_nentries_0_V,
        match7_nentries_1_V,
        match8_dataarray_data_V_address0,
        match8_dataarray_data_V_ce0,
        match8_dataarray_data_V_q0,
        match8_nentries_0_V,
        match8_nentries_1_V,
        allstub_dataarray_data_V_address0,
        allstub_dataarray_data_V_ce0,
        allstub_dataarray_data_V_q0,
        allstub_nentries_0_V,
        allstub_nentries_1_V,
        allstub_nentries_2_V,
        allstub_nentries_3_V,
        allstub_nentries_4_V,
        allstub_nentries_5_V,
        allstub_nentries_6_V,
        allstub_nentries_7_V,
        allproj_dataarray_data_V_address0,
        allproj_dataarray_data_V_ce0,
        allproj_dataarray_data_V_q0,
        allproj_nentries_0_V,
        allproj_nentries_1_V,
        allproj_nentries_2_V,
        allproj_nentries_3_V,
        allproj_nentries_4_V,
        allproj_nentries_5_V,
        allproj_nentries_6_V,
        allproj_nentries_7_V,
        bx_o_V,
        bx_o_V_ap_vld,
        fullmatch1_dataarray_data_V_address0,
        fullmatch1_dataarray_data_V_ce0,
        fullmatch1_dataarray_data_V_we0,
        fullmatch1_dataarray_data_V_d0,
        fullmatch1_nentries_0_V,
        fullmatch1_nentries_0_V_ap_vld,
        fullmatch1_nentries_1_V,
        fullmatch1_nentries_1_V_ap_vld,
        fullmatch2_dataarray_data_V_address0,
        fullmatch2_dataarray_data_V_ce0,
        fullmatch2_dataarray_data_V_we0,
        fullmatch2_dataarray_data_V_d0,
        fullmatch2_nentries_0_V,
        fullmatch2_nentries_0_V_ap_vld,
        fullmatch2_nentries_1_V,
        fullmatch2_nentries_1_V_ap_vld,
        fullmatch3_dataarray_data_V_address0,
        fullmatch3_dataarray_data_V_ce0,
        fullmatch3_dataarray_data_V_we0,
        fullmatch3_dataarray_data_V_d0,
        fullmatch3_nentries_0_V,
        fullmatch3_nentries_0_V_ap_vld,
        fullmatch3_nentries_1_V,
        fullmatch3_nentries_1_V_ap_vld,
        fullmatch4_dataarray_data_V_address0,
        fullmatch4_dataarray_data_V_ce0,
        fullmatch4_dataarray_data_V_we0,
        fullmatch4_dataarray_data_V_d0,
        fullmatch4_nentries_0_V,
        fullmatch4_nentries_0_V_ap_vld,
        fullmatch4_nentries_1_V,
        fullmatch4_nentries_1_V_ap_vld,
        fullmatch5_dataarray_data_V_address0,
        fullmatch5_dataarray_data_V_ce0,
        fullmatch5_dataarray_data_V_we0,
        fullmatch5_dataarray_data_V_d0,
        fullmatch5_nentries_0_V,
        fullmatch5_nentries_0_V_ap_vld,
        fullmatch5_nentries_1_V,
        fullmatch5_nentries_1_V_ap_vld,
        fullmatch6_dataarray_data_V_address0,
        fullmatch6_dataarray_data_V_ce0,
        fullmatch6_dataarray_data_V_we0,
        fullmatch6_dataarray_data_V_d0,
        fullmatch6_nentries_0_V,
        fullmatch6_nentries_0_V_ap_vld,
        fullmatch6_nentries_1_V,
        fullmatch6_nentries_1_V_ap_vld,
        fullmatch7_dataarray_data_V_address0,
        fullmatch7_dataarray_data_V_ce0,
        fullmatch7_dataarray_data_V_we0,
        fullmatch7_dataarray_data_V_d0,
        fullmatch7_nentries_0_V,
        fullmatch7_nentries_0_V_ap_vld,
        fullmatch7_nentries_1_V,
        fullmatch7_nentries_1_V_ap_vld
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [2:0] bx_V;
output  [7:0] match1_dataarray_data_V_address0;
output   match1_dataarray_data_V_ce0;
input  [13:0] match1_dataarray_data_V_q0;
input  [7:0] match1_nentries_0_V;
input  [7:0] match1_nentries_1_V;
output  [7:0] match2_dataarray_data_V_address0;
output   match2_dataarray_data_V_ce0;
input  [13:0] match2_dataarray_data_V_q0;
input  [7:0] match2_nentries_0_V;
input  [7:0] match2_nentries_1_V;
output  [7:0] match3_dataarray_data_V_address0;
output   match3_dataarray_data_V_ce0;
input  [13:0] match3_dataarray_data_V_q0;
input  [7:0] match3_nentries_0_V;
input  [7:0] match3_nentries_1_V;
output  [7:0] match4_dataarray_data_V_address0;
output   match4_dataarray_data_V_ce0;
input  [13:0] match4_dataarray_data_V_q0;
input  [7:0] match4_nentries_0_V;
input  [7:0] match4_nentries_1_V;
output  [7:0] match5_dataarray_data_V_address0;
output   match5_dataarray_data_V_ce0;
input  [13:0] match5_dataarray_data_V_q0;
input  [7:0] match5_nentries_0_V;
input  [7:0] match5_nentries_1_V;
output  [7:0] match6_dataarray_data_V_address0;
output   match6_dataarray_data_V_ce0;
input  [13:0] match6_dataarray_data_V_q0;
input  [7:0] match6_nentries_0_V;
input  [7:0] match6_nentries_1_V;
output  [7:0] match7_dataarray_data_V_address0;
output   match7_dataarray_data_V_ce0;
input  [13:0] match7_dataarray_data_V_q0;
input  [7:0] match7_nentries_0_V;
input  [7:0] match7_nentries_1_V;
output  [7:0] match8_dataarray_data_V_address0;
output   match8_dataarray_data_V_ce0;
input  [13:0] match8_dataarray_data_V_q0;
input  [7:0] match8_nentries_0_V;
input  [7:0] match8_nentries_1_V;
output  [9:0] allstub_dataarray_data_V_address0;
output   allstub_dataarray_data_V_ce0;
input  [35:0] allstub_dataarray_data_V_q0;
input  [7:0] allstub_nentries_0_V;
input  [7:0] allstub_nentries_1_V;
input  [7:0] allstub_nentries_2_V;
input  [7:0] allstub_nentries_3_V;
input  [7:0] allstub_nentries_4_V;
input  [7:0] allstub_nentries_5_V;
input  [7:0] allstub_nentries_6_V;
input  [7:0] allstub_nentries_7_V;
output  [9:0] allproj_dataarray_data_V_address0;
output   allproj_dataarray_data_V_ce0;
input  [59:0] allproj_dataarray_data_V_q0;
input  [7:0] allproj_nentries_0_V;
input  [7:0] allproj_nentries_1_V;
input  [7:0] allproj_nentries_2_V;
input  [7:0] allproj_nentries_3_V;
input  [7:0] allproj_nentries_4_V;
input  [7:0] allproj_nentries_5_V;
input  [7:0] allproj_nentries_6_V;
input  [7:0] allproj_nentries_7_V;
output  [2:0] bx_o_V;
output   bx_o_V_ap_vld;
output  [7:0] fullmatch1_dataarray_data_V_address0;
output   fullmatch1_dataarray_data_V_ce0;
output   fullmatch1_dataarray_data_V_we0;
output  [44:0] fullmatch1_dataarray_data_V_d0;
output  [7:0] fullmatch1_nentries_0_V;
output   fullmatch1_nentries_0_V_ap_vld;
output  [7:0] fullmatch1_nentries_1_V;
output   fullmatch1_nentries_1_V_ap_vld;
output  [7:0] fullmatch2_dataarray_data_V_address0;
output   fullmatch2_dataarray_data_V_ce0;
output   fullmatch2_dataarray_data_V_we0;
output  [44:0] fullmatch2_dataarray_data_V_d0;
output  [7:0] fullmatch2_nentries_0_V;
output   fullmatch2_nentries_0_V_ap_vld;
output  [7:0] fullmatch2_nentries_1_V;
output   fullmatch2_nentries_1_V_ap_vld;
output  [7:0] fullmatch3_dataarray_data_V_address0;
output   fullmatch3_dataarray_data_V_ce0;
output   fullmatch3_dataarray_data_V_we0;
output  [44:0] fullmatch3_dataarray_data_V_d0;
output  [7:0] fullmatch3_nentries_0_V;
output   fullmatch3_nentries_0_V_ap_vld;
output  [7:0] fullmatch3_nentries_1_V;
output   fullmatch3_nentries_1_V_ap_vld;
output  [7:0] fullmatch4_dataarray_data_V_address0;
output   fullmatch4_dataarray_data_V_ce0;
output   fullmatch4_dataarray_data_V_we0;
output  [44:0] fullmatch4_dataarray_data_V_d0;
output  [7:0] fullmatch4_nentries_0_V;
output   fullmatch4_nentries_0_V_ap_vld;
output  [7:0] fullmatch4_nentries_1_V;
output   fullmatch4_nentries_1_V_ap_vld;
output  [7:0] fullmatch5_dataarray_data_V_address0;
output   fullmatch5_dataarray_data_V_ce0;
output   fullmatch5_dataarray_data_V_we0;
output  [44:0] fullmatch5_dataarray_data_V_d0;
output  [7:0] fullmatch5_nentries_0_V;
output   fullmatch5_nentries_0_V_ap_vld;
output  [7:0] fullmatch5_nentries_1_V;
output   fullmatch5_nentries_1_V_ap_vld;
output  [7:0] fullmatch6_dataarray_data_V_address0;
output   fullmatch6_dataarray_data_V_ce0;
output   fullmatch6_dataarray_data_V_we0;
output  [44:0] fullmatch6_dataarray_data_V_d0;
output  [7:0] fullmatch6_nentries_0_V;
output   fullmatch6_nentries_0_V_ap_vld;
output  [7:0] fullmatch6_nentries_1_V;
output   fullmatch6_nentries_1_V_ap_vld;
output  [7:0] fullmatch7_dataarray_data_V_address0;
output   fullmatch7_dataarray_data_V_ce0;
output   fullmatch7_dataarray_data_V_we0;
output  [44:0] fullmatch7_dataarray_data_V_d0;
output  [7:0] fullmatch7_nentries_0_V;
output   fullmatch7_nentries_0_V_ap_vld;
output  [7:0] fullmatch7_nentries_1_V;
output   fullmatch7_nentries_1_V_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [2:0] bx_o_V_1_data_reg;
reg    bx_o_V_1_vld_reg;
wire    bx_o_V_1_vld_in;
reg    bx_o_V_1_ack_in;
wire    grp_MatchCalculator_fu_260_ap_start;
wire    grp_MatchCalculator_fu_260_ap_done;
wire    grp_MatchCalculator_fu_260_ap_idle;
wire    grp_MatchCalculator_fu_260_ap_ready;
wire   [7:0] grp_MatchCalculator_fu_260_match1_dataarray_data_V_address0;
wire    grp_MatchCalculator_fu_260_match1_dataarray_data_V_ce0;
wire   [7:0] grp_MatchCalculator_fu_260_match2_dataarray_data_V_address0;
wire    grp_MatchCalculator_fu_260_match2_dataarray_data_V_ce0;
wire   [7:0] grp_MatchCalculator_fu_260_match3_dataarray_data_V_address0;
wire    grp_MatchCalculator_fu_260_match3_dataarray_data_V_ce0;
wire   [7:0] grp_MatchCalculator_fu_260_match4_dataarray_data_V_address0;
wire    grp_MatchCalculator_fu_260_match4_dataarray_data_V_ce0;
wire   [7:0] grp_MatchCalculator_fu_260_match5_dataarray_data_V_address0;
wire    grp_MatchCalculator_fu_260_match5_dataarray_data_V_ce0;
wire   [7:0] grp_MatchCalculator_fu_260_match6_dataarray_data_V_address0;
wire    grp_MatchCalculator_fu_260_match6_dataarray_data_V_ce0;
wire   [7:0] grp_MatchCalculator_fu_260_match7_dataarray_data_V_address0;
wire    grp_MatchCalculator_fu_260_match7_dataarray_data_V_ce0;
wire   [7:0] grp_MatchCalculator_fu_260_match8_dataarray_data_V_address0;
wire    grp_MatchCalculator_fu_260_match8_dataarray_data_V_ce0;
wire   [9:0] grp_MatchCalculator_fu_260_allstub_dataarray_data_V_address0;
wire    grp_MatchCalculator_fu_260_allstub_dataarray_data_V_ce0;
wire   [9:0] grp_MatchCalculator_fu_260_allproj_dataarray_data_V_address0;
wire    grp_MatchCalculator_fu_260_allproj_dataarray_data_V_ce0;
wire   [2:0] grp_MatchCalculator_fu_260_bx_o_V;
wire    grp_MatchCalculator_fu_260_bx_o_V_ap_vld;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_address0;
wire    grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_ce0;
wire    grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_we0;
wire   [44:0] grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_d0;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch1_nentries_0_V;
wire    grp_MatchCalculator_fu_260_fullmatch1_nentries_0_V_ap_vld;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch1_nentries_1_V;
wire    grp_MatchCalculator_fu_260_fullmatch1_nentries_1_V_ap_vld;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_address0;
wire    grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_ce0;
wire    grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_we0;
wire   [44:0] grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_d0;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch2_nentries_0_V;
wire    grp_MatchCalculator_fu_260_fullmatch2_nentries_0_V_ap_vld;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch2_nentries_1_V;
wire    grp_MatchCalculator_fu_260_fullmatch2_nentries_1_V_ap_vld;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_address0;
wire    grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_ce0;
wire    grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_we0;
wire   [44:0] grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_d0;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch3_nentries_0_V;
wire    grp_MatchCalculator_fu_260_fullmatch3_nentries_0_V_ap_vld;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch3_nentries_1_V;
wire    grp_MatchCalculator_fu_260_fullmatch3_nentries_1_V_ap_vld;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_address0;
wire    grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_ce0;
wire    grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_we0;
wire   [44:0] grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_d0;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch4_nentries_0_V;
wire    grp_MatchCalculator_fu_260_fullmatch4_nentries_0_V_ap_vld;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch4_nentries_1_V;
wire    grp_MatchCalculator_fu_260_fullmatch4_nentries_1_V_ap_vld;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_address0;
wire    grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_ce0;
wire    grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_we0;
wire   [44:0] grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_d0;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch5_nentries_0_V;
wire    grp_MatchCalculator_fu_260_fullmatch5_nentries_0_V_ap_vld;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch5_nentries_1_V;
wire    grp_MatchCalculator_fu_260_fullmatch5_nentries_1_V_ap_vld;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_address0;
wire    grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_ce0;
wire    grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_we0;
wire   [44:0] grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_d0;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch6_nentries_0_V;
wire    grp_MatchCalculator_fu_260_fullmatch6_nentries_0_V_ap_vld;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch6_nentries_1_V;
wire    grp_MatchCalculator_fu_260_fullmatch6_nentries_1_V_ap_vld;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_address0;
wire    grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_ce0;
wire    grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_we0;
wire   [44:0] grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_d0;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch7_nentries_0_V;
wire    grp_MatchCalculator_fu_260_fullmatch7_nentries_0_V_ap_vld;
wire   [7:0] grp_MatchCalculator_fu_260_fullmatch7_nentries_1_V;
wire    grp_MatchCalculator_fu_260_fullmatch7_nentries_1_V_ap_vld;
reg    grp_MatchCalculator_fu_260_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [2:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 bx_o_V_1_data_reg = 3'd0;
#0 bx_o_V_1_vld_reg = 1'b0;
#0 grp_MatchCalculator_fu_260_ap_start_reg = 1'b0;
end

MatchCalculator grp_MatchCalculator_fu_260(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MatchCalculator_fu_260_ap_start),
    .ap_done(grp_MatchCalculator_fu_260_ap_done),
    .ap_idle(grp_MatchCalculator_fu_260_ap_idle),
    .ap_ready(grp_MatchCalculator_fu_260_ap_ready),
    .bx_V(bx_V),
    .match1_dataarray_data_V_address0(grp_MatchCalculator_fu_260_match1_dataarray_data_V_address0),
    .match1_dataarray_data_V_ce0(grp_MatchCalculator_fu_260_match1_dataarray_data_V_ce0),
    .match1_dataarray_data_V_q0(match1_dataarray_data_V_q0),
    .match1_nentries_0_V_read(match1_nentries_0_V),
    .match1_nentries_1_V_read(match1_nentries_1_V),
    .match2_dataarray_data_V_address0(grp_MatchCalculator_fu_260_match2_dataarray_data_V_address0),
    .match2_dataarray_data_V_ce0(grp_MatchCalculator_fu_260_match2_dataarray_data_V_ce0),
    .match2_dataarray_data_V_q0(match2_dataarray_data_V_q0),
    .match2_nentries_0_V_read(match2_nentries_0_V),
    .match2_nentries_1_V_read(match2_nentries_1_V),
    .match3_dataarray_data_V_address0(grp_MatchCalculator_fu_260_match3_dataarray_data_V_address0),
    .match3_dataarray_data_V_ce0(grp_MatchCalculator_fu_260_match3_dataarray_data_V_ce0),
    .match3_dataarray_data_V_q0(match3_dataarray_data_V_q0),
    .match3_nentries_0_V_read(match3_nentries_0_V),
    .match3_nentries_1_V_read(match3_nentries_1_V),
    .match4_dataarray_data_V_address0(grp_MatchCalculator_fu_260_match4_dataarray_data_V_address0),
    .match4_dataarray_data_V_ce0(grp_MatchCalculator_fu_260_match4_dataarray_data_V_ce0),
    .match4_dataarray_data_V_q0(match4_dataarray_data_V_q0),
    .match4_nentries_0_V_read(match4_nentries_0_V),
    .match4_nentries_1_V_read(match4_nentries_1_V),
    .match5_dataarray_data_V_address0(grp_MatchCalculator_fu_260_match5_dataarray_data_V_address0),
    .match5_dataarray_data_V_ce0(grp_MatchCalculator_fu_260_match5_dataarray_data_V_ce0),
    .match5_dataarray_data_V_q0(match5_dataarray_data_V_q0),
    .match5_nentries_0_V_read(match5_nentries_0_V),
    .match5_nentries_1_V_read(match5_nentries_1_V),
    .match6_dataarray_data_V_address0(grp_MatchCalculator_fu_260_match6_dataarray_data_V_address0),
    .match6_dataarray_data_V_ce0(grp_MatchCalculator_fu_260_match6_dataarray_data_V_ce0),
    .match6_dataarray_data_V_q0(match6_dataarray_data_V_q0),
    .match6_nentries_0_V_read(match6_nentries_0_V),
    .match6_nentries_1_V_read(match6_nentries_1_V),
    .match7_dataarray_data_V_address0(grp_MatchCalculator_fu_260_match7_dataarray_data_V_address0),
    .match7_dataarray_data_V_ce0(grp_MatchCalculator_fu_260_match7_dataarray_data_V_ce0),
    .match7_dataarray_data_V_q0(match7_dataarray_data_V_q0),
    .match7_nentries_0_V_read(match7_nentries_0_V),
    .match7_nentries_1_V_read(match7_nentries_1_V),
    .match8_dataarray_data_V_address0(grp_MatchCalculator_fu_260_match8_dataarray_data_V_address0),
    .match8_dataarray_data_V_ce0(grp_MatchCalculator_fu_260_match8_dataarray_data_V_ce0),
    .match8_dataarray_data_V_q0(match8_dataarray_data_V_q0),
    .match8_nentries_0_V_read(match8_nentries_0_V),
    .match8_nentries_1_V_read(match8_nentries_1_V),
    .allstub_dataarray_data_V_address0(grp_MatchCalculator_fu_260_allstub_dataarray_data_V_address0),
    .allstub_dataarray_data_V_ce0(grp_MatchCalculator_fu_260_allstub_dataarray_data_V_ce0),
    .allstub_dataarray_data_V_q0(allstub_dataarray_data_V_q0),
    .allproj_dataarray_data_V_address0(grp_MatchCalculator_fu_260_allproj_dataarray_data_V_address0),
    .allproj_dataarray_data_V_ce0(grp_MatchCalculator_fu_260_allproj_dataarray_data_V_ce0),
    .allproj_dataarray_data_V_q0(allproj_dataarray_data_V_q0),
    .bx_o_V(grp_MatchCalculator_fu_260_bx_o_V),
    .bx_o_V_ap_vld(grp_MatchCalculator_fu_260_bx_o_V_ap_vld),
    .fullmatch1_dataarray_data_V_address0(grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_address0),
    .fullmatch1_dataarray_data_V_ce0(grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_ce0),
    .fullmatch1_dataarray_data_V_we0(grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_we0),
    .fullmatch1_dataarray_data_V_d0(grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_d0),
    .fullmatch1_nentries_0_V(grp_MatchCalculator_fu_260_fullmatch1_nentries_0_V),
    .fullmatch1_nentries_0_V_ap_vld(grp_MatchCalculator_fu_260_fullmatch1_nentries_0_V_ap_vld),
    .fullmatch1_nentries_1_V(grp_MatchCalculator_fu_260_fullmatch1_nentries_1_V),
    .fullmatch1_nentries_1_V_ap_vld(grp_MatchCalculator_fu_260_fullmatch1_nentries_1_V_ap_vld),
    .fullmatch2_dataarray_data_V_address0(grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_address0),
    .fullmatch2_dataarray_data_V_ce0(grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_ce0),
    .fullmatch2_dataarray_data_V_we0(grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_we0),
    .fullmatch2_dataarray_data_V_d0(grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_d0),
    .fullmatch2_nentries_0_V(grp_MatchCalculator_fu_260_fullmatch2_nentries_0_V),
    .fullmatch2_nentries_0_V_ap_vld(grp_MatchCalculator_fu_260_fullmatch2_nentries_0_V_ap_vld),
    .fullmatch2_nentries_1_V(grp_MatchCalculator_fu_260_fullmatch2_nentries_1_V),
    .fullmatch2_nentries_1_V_ap_vld(grp_MatchCalculator_fu_260_fullmatch2_nentries_1_V_ap_vld),
    .fullmatch3_dataarray_data_V_address0(grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_address0),
    .fullmatch3_dataarray_data_V_ce0(grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_ce0),
    .fullmatch3_dataarray_data_V_we0(grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_we0),
    .fullmatch3_dataarray_data_V_d0(grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_d0),
    .fullmatch3_nentries_0_V(grp_MatchCalculator_fu_260_fullmatch3_nentries_0_V),
    .fullmatch3_nentries_0_V_ap_vld(grp_MatchCalculator_fu_260_fullmatch3_nentries_0_V_ap_vld),
    .fullmatch3_nentries_1_V(grp_MatchCalculator_fu_260_fullmatch3_nentries_1_V),
    .fullmatch3_nentries_1_V_ap_vld(grp_MatchCalculator_fu_260_fullmatch3_nentries_1_V_ap_vld),
    .fullmatch4_dataarray_data_V_address0(grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_address0),
    .fullmatch4_dataarray_data_V_ce0(grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_ce0),
    .fullmatch4_dataarray_data_V_we0(grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_we0),
    .fullmatch4_dataarray_data_V_d0(grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_d0),
    .fullmatch4_nentries_0_V(grp_MatchCalculator_fu_260_fullmatch4_nentries_0_V),
    .fullmatch4_nentries_0_V_ap_vld(grp_MatchCalculator_fu_260_fullmatch4_nentries_0_V_ap_vld),
    .fullmatch4_nentries_1_V(grp_MatchCalculator_fu_260_fullmatch4_nentries_1_V),
    .fullmatch4_nentries_1_V_ap_vld(grp_MatchCalculator_fu_260_fullmatch4_nentries_1_V_ap_vld),
    .fullmatch5_dataarray_data_V_address0(grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_address0),
    .fullmatch5_dataarray_data_V_ce0(grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_ce0),
    .fullmatch5_dataarray_data_V_we0(grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_we0),
    .fullmatch5_dataarray_data_V_d0(grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_d0),
    .fullmatch5_nentries_0_V(grp_MatchCalculator_fu_260_fullmatch5_nentries_0_V),
    .fullmatch5_nentries_0_V_ap_vld(grp_MatchCalculator_fu_260_fullmatch5_nentries_0_V_ap_vld),
    .fullmatch5_nentries_1_V(grp_MatchCalculator_fu_260_fullmatch5_nentries_1_V),
    .fullmatch5_nentries_1_V_ap_vld(grp_MatchCalculator_fu_260_fullmatch5_nentries_1_V_ap_vld),
    .fullmatch6_dataarray_data_V_address0(grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_address0),
    .fullmatch6_dataarray_data_V_ce0(grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_ce0),
    .fullmatch6_dataarray_data_V_we0(grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_we0),
    .fullmatch6_dataarray_data_V_d0(grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_d0),
    .fullmatch6_nentries_0_V(grp_MatchCalculator_fu_260_fullmatch6_nentries_0_V),
    .fullmatch6_nentries_0_V_ap_vld(grp_MatchCalculator_fu_260_fullmatch6_nentries_0_V_ap_vld),
    .fullmatch6_nentries_1_V(grp_MatchCalculator_fu_260_fullmatch6_nentries_1_V),
    .fullmatch6_nentries_1_V_ap_vld(grp_MatchCalculator_fu_260_fullmatch6_nentries_1_V_ap_vld),
    .fullmatch7_dataarray_data_V_address0(grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_address0),
    .fullmatch7_dataarray_data_V_ce0(grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_ce0),
    .fullmatch7_dataarray_data_V_we0(grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_we0),
    .fullmatch7_dataarray_data_V_d0(grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_d0),
    .fullmatch7_nentries_0_V(grp_MatchCalculator_fu_260_fullmatch7_nentries_0_V),
    .fullmatch7_nentries_0_V_ap_vld(grp_MatchCalculator_fu_260_fullmatch7_nentries_0_V_ap_vld),
    .fullmatch7_nentries_1_V(grp_MatchCalculator_fu_260_fullmatch7_nentries_1_V),
    .fullmatch7_nentries_1_V_ap_vld(grp_MatchCalculator_fu_260_fullmatch7_nentries_1_V_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MatchCalculator_fu_260_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_MatchCalculator_fu_260_ap_start_reg <= 1'b1;
        end else if ((grp_MatchCalculator_fu_260_ap_ready == 1'b1)) begin
            grp_MatchCalculator_fu_260_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b1;
    end else if (((bx_o_V_1_vld_in == 1'b0) & (1'b1 == 1'b1) & (bx_o_V_1_vld_reg == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (bx_o_V_1_vld_in == 1'b1) & (bx_o_V_1_vld_reg == 1'b1)))) begin
        bx_o_V_1_data_reg <= grp_MatchCalculator_fu_260_bx_o_V;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (bx_o_V_1_ack_in == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (bx_o_V_1_ack_in == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((bx_o_V_1_vld_reg == 1'b0) | ((1'b1 == 1'b1) & (bx_o_V_1_vld_reg == 1'b1)))) begin
        bx_o_V_1_ack_in = 1'b1;
    end else begin
        bx_o_V_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_MatchCalculator_fu_260_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (bx_o_V_1_ack_in == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign allproj_dataarray_data_V_address0 = grp_MatchCalculator_fu_260_allproj_dataarray_data_V_address0;

assign allproj_dataarray_data_V_ce0 = grp_MatchCalculator_fu_260_allproj_dataarray_data_V_ce0;

assign allstub_dataarray_data_V_address0 = grp_MatchCalculator_fu_260_allstub_dataarray_data_V_address0;

assign allstub_dataarray_data_V_ce0 = grp_MatchCalculator_fu_260_allstub_dataarray_data_V_ce0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign bx_o_V = bx_o_V_1_data_reg;

assign bx_o_V_1_vld_in = grp_MatchCalculator_fu_260_bx_o_V_ap_vld;

assign bx_o_V_ap_vld = bx_o_V_1_vld_reg;

assign fullmatch1_dataarray_data_V_address0 = grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_address0;

assign fullmatch1_dataarray_data_V_ce0 = grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_ce0;

assign fullmatch1_dataarray_data_V_d0 = grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_d0;

assign fullmatch1_dataarray_data_V_we0 = grp_MatchCalculator_fu_260_fullmatch1_dataarray_data_V_we0;

assign fullmatch1_nentries_0_V = grp_MatchCalculator_fu_260_fullmatch1_nentries_0_V;

assign fullmatch1_nentries_0_V_ap_vld = grp_MatchCalculator_fu_260_fullmatch1_nentries_0_V_ap_vld;

assign fullmatch1_nentries_1_V = grp_MatchCalculator_fu_260_fullmatch1_nentries_1_V;

assign fullmatch1_nentries_1_V_ap_vld = grp_MatchCalculator_fu_260_fullmatch1_nentries_1_V_ap_vld;

assign fullmatch2_dataarray_data_V_address0 = grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_address0;

assign fullmatch2_dataarray_data_V_ce0 = grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_ce0;

assign fullmatch2_dataarray_data_V_d0 = grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_d0;

assign fullmatch2_dataarray_data_V_we0 = grp_MatchCalculator_fu_260_fullmatch2_dataarray_data_V_we0;

assign fullmatch2_nentries_0_V = grp_MatchCalculator_fu_260_fullmatch2_nentries_0_V;

assign fullmatch2_nentries_0_V_ap_vld = grp_MatchCalculator_fu_260_fullmatch2_nentries_0_V_ap_vld;

assign fullmatch2_nentries_1_V = grp_MatchCalculator_fu_260_fullmatch2_nentries_1_V;

assign fullmatch2_nentries_1_V_ap_vld = grp_MatchCalculator_fu_260_fullmatch2_nentries_1_V_ap_vld;

assign fullmatch3_dataarray_data_V_address0 = grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_address0;

assign fullmatch3_dataarray_data_V_ce0 = grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_ce0;

assign fullmatch3_dataarray_data_V_d0 = grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_d0;

assign fullmatch3_dataarray_data_V_we0 = grp_MatchCalculator_fu_260_fullmatch3_dataarray_data_V_we0;

assign fullmatch3_nentries_0_V = grp_MatchCalculator_fu_260_fullmatch3_nentries_0_V;

assign fullmatch3_nentries_0_V_ap_vld = grp_MatchCalculator_fu_260_fullmatch3_nentries_0_V_ap_vld;

assign fullmatch3_nentries_1_V = grp_MatchCalculator_fu_260_fullmatch3_nentries_1_V;

assign fullmatch3_nentries_1_V_ap_vld = grp_MatchCalculator_fu_260_fullmatch3_nentries_1_V_ap_vld;

assign fullmatch4_dataarray_data_V_address0 = grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_address0;

assign fullmatch4_dataarray_data_V_ce0 = grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_ce0;

assign fullmatch4_dataarray_data_V_d0 = grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_d0;

assign fullmatch4_dataarray_data_V_we0 = grp_MatchCalculator_fu_260_fullmatch4_dataarray_data_V_we0;

assign fullmatch4_nentries_0_V = grp_MatchCalculator_fu_260_fullmatch4_nentries_0_V;

assign fullmatch4_nentries_0_V_ap_vld = grp_MatchCalculator_fu_260_fullmatch4_nentries_0_V_ap_vld;

assign fullmatch4_nentries_1_V = grp_MatchCalculator_fu_260_fullmatch4_nentries_1_V;

assign fullmatch4_nentries_1_V_ap_vld = grp_MatchCalculator_fu_260_fullmatch4_nentries_1_V_ap_vld;

assign fullmatch5_dataarray_data_V_address0 = grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_address0;

assign fullmatch5_dataarray_data_V_ce0 = grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_ce0;

assign fullmatch5_dataarray_data_V_d0 = grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_d0;

assign fullmatch5_dataarray_data_V_we0 = grp_MatchCalculator_fu_260_fullmatch5_dataarray_data_V_we0;

assign fullmatch5_nentries_0_V = grp_MatchCalculator_fu_260_fullmatch5_nentries_0_V;

assign fullmatch5_nentries_0_V_ap_vld = grp_MatchCalculator_fu_260_fullmatch5_nentries_0_V_ap_vld;

assign fullmatch5_nentries_1_V = grp_MatchCalculator_fu_260_fullmatch5_nentries_1_V;

assign fullmatch5_nentries_1_V_ap_vld = grp_MatchCalculator_fu_260_fullmatch5_nentries_1_V_ap_vld;

assign fullmatch6_dataarray_data_V_address0 = grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_address0;

assign fullmatch6_dataarray_data_V_ce0 = grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_ce0;

assign fullmatch6_dataarray_data_V_d0 = grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_d0;

assign fullmatch6_dataarray_data_V_we0 = grp_MatchCalculator_fu_260_fullmatch6_dataarray_data_V_we0;

assign fullmatch6_nentries_0_V = grp_MatchCalculator_fu_260_fullmatch6_nentries_0_V;

assign fullmatch6_nentries_0_V_ap_vld = grp_MatchCalculator_fu_260_fullmatch6_nentries_0_V_ap_vld;

assign fullmatch6_nentries_1_V = grp_MatchCalculator_fu_260_fullmatch6_nentries_1_V;

assign fullmatch6_nentries_1_V_ap_vld = grp_MatchCalculator_fu_260_fullmatch6_nentries_1_V_ap_vld;

assign fullmatch7_dataarray_data_V_address0 = grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_address0;

assign fullmatch7_dataarray_data_V_ce0 = grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_ce0;

assign fullmatch7_dataarray_data_V_d0 = grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_d0;

assign fullmatch7_dataarray_data_V_we0 = grp_MatchCalculator_fu_260_fullmatch7_dataarray_data_V_we0;

assign fullmatch7_nentries_0_V = grp_MatchCalculator_fu_260_fullmatch7_nentries_0_V;

assign fullmatch7_nentries_0_V_ap_vld = grp_MatchCalculator_fu_260_fullmatch7_nentries_0_V_ap_vld;

assign fullmatch7_nentries_1_V = grp_MatchCalculator_fu_260_fullmatch7_nentries_1_V;

assign fullmatch7_nentries_1_V_ap_vld = grp_MatchCalculator_fu_260_fullmatch7_nentries_1_V_ap_vld;

assign grp_MatchCalculator_fu_260_ap_start = grp_MatchCalculator_fu_260_ap_start_reg;

assign match1_dataarray_data_V_address0 = grp_MatchCalculator_fu_260_match1_dataarray_data_V_address0;

assign match1_dataarray_data_V_ce0 = grp_MatchCalculator_fu_260_match1_dataarray_data_V_ce0;

assign match2_dataarray_data_V_address0 = grp_MatchCalculator_fu_260_match2_dataarray_data_V_address0;

assign match2_dataarray_data_V_ce0 = grp_MatchCalculator_fu_260_match2_dataarray_data_V_ce0;

assign match3_dataarray_data_V_address0 = grp_MatchCalculator_fu_260_match3_dataarray_data_V_address0;

assign match3_dataarray_data_V_ce0 = grp_MatchCalculator_fu_260_match3_dataarray_data_V_ce0;

assign match4_dataarray_data_V_address0 = grp_MatchCalculator_fu_260_match4_dataarray_data_V_address0;

assign match4_dataarray_data_V_ce0 = grp_MatchCalculator_fu_260_match4_dataarray_data_V_ce0;

assign match5_dataarray_data_V_address0 = grp_MatchCalculator_fu_260_match5_dataarray_data_V_address0;

assign match5_dataarray_data_V_ce0 = grp_MatchCalculator_fu_260_match5_dataarray_data_V_ce0;

assign match6_dataarray_data_V_address0 = grp_MatchCalculator_fu_260_match6_dataarray_data_V_address0;

assign match6_dataarray_data_V_ce0 = grp_MatchCalculator_fu_260_match6_dataarray_data_V_ce0;

assign match7_dataarray_data_V_address0 = grp_MatchCalculator_fu_260_match7_dataarray_data_V_address0;

assign match7_dataarray_data_V_ce0 = grp_MatchCalculator_fu_260_match7_dataarray_data_V_ce0;

assign match8_dataarray_data_V_address0 = grp_MatchCalculator_fu_260_match8_dataarray_data_V_address0;

assign match8_dataarray_data_V_ce0 = grp_MatchCalculator_fu_260_match8_dataarray_data_V_ce0;

endmodule //MatchCalculatorTop
