// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module read_inmem (
        ap_ready,
        data_data_V_read,
        read_imem_V,
        ap_return
);


output   ap_ready;
input  [59:0] data_data_V_read;
input  [4:0] read_imem_V;
output  [59:0] ap_return;

wire   [0:0] tmp_i_fu_40_p2;
wire   [0:0] tmp_i2_i1_fu_46_p2;
wire   [0:0] tmp_i2_i_i3_fu_52_p2;
wire   [0:0] tmp_i3_i_i_fu_58_p2;

assign ap_ready = 1'b1;

assign ap_return = data_data_V_read;

assign tmp_i2_i1_fu_46_p2 = ((read_imem_V == 5'd21) ? 1'b1 : 1'b0);

assign tmp_i2_i_i3_fu_52_p2 = ((read_imem_V == 5'd22) ? 1'b1 : 1'b0);

assign tmp_i3_i_i_fu_58_p2 = ((read_imem_V == 5'd23) ? 1'b1 : 1'b0);

assign tmp_i_fu_40_p2 = ((read_imem_V == 5'd20) ? 1'b1 : 1'b0);

endmodule //read_inmem
