# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/scratch/rz393/firmware-hls/IntegrationTests/ME_Test_1/ME_Test/ME_Test/ME_Test.srcs/sources_1/ip/MatchEngineTopL1_0_1/MatchEngineTopL1_0.xci
# IP: The module: 'MatchEngineTopL1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/scratch/rz393/firmware-hls/IntegrationTests/ME_Test_1/ME_Test/ME_Test/ME_Test.srcs/sources_1/ip/MatchEngineTopL1_0_1/constraints/MatchEngineTopL1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MatchEngineTopL1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /mnt/scratch/rz393/firmware-hls/IntegrationTests/ME_Test_1/ME_Test/ME_Test/ME_Test.srcs/sources_1/ip/MatchEngineTopL1_0_1/MatchEngineTopL1_0.xci
# IP: The module: 'MatchEngineTopL1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/scratch/rz393/firmware-hls/IntegrationTests/ME_Test_1/ME_Test/ME_Test/ME_Test.srcs/sources_1/ip/MatchEngineTopL1_0_1/constraints/MatchEngineTopL1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MatchEngineTopL1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
