// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module MatchEngine_1_0_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bx_V,
        bx_o_V,
        bx_o_V_ap_vld,
        instubdata_dataarray_data_V_address0,
        instubdata_dataarray_data_V_ce0,
        instubdata_dataarray_data_V_q0,
        instubdata_nentries_0_V_0,
        instubdata_nentries_0_V_1,
        instubdata_nentries_0_V_2,
        instubdata_nentries_0_V_3,
        instubdata_nentries_0_V_4,
        instubdata_nentries_0_V_5,
        instubdata_nentries_0_V_6,
        instubdata_nentries_0_V_7,
        instubdata_nentries_1_V_0,
        instubdata_nentries_1_V_1,
        instubdata_nentries_1_V_2,
        instubdata_nentries_1_V_3,
        instubdata_nentries_1_V_4,
        instubdata_nentries_1_V_5,
        instubdata_nentries_1_V_6,
        instubdata_nentries_1_V_7,
        instubdata_nentries_2_V_0,
        instubdata_nentries_2_V_1,
        instubdata_nentries_2_V_2,
        instubdata_nentries_2_V_3,
        instubdata_nentries_2_V_4,
        instubdata_nentries_2_V_5,
        instubdata_nentries_2_V_6,
        instubdata_nentries_2_V_7,
        instubdata_nentries_3_V_0,
        instubdata_nentries_3_V_1,
        instubdata_nentries_3_V_2,
        instubdata_nentries_3_V_3,
        instubdata_nentries_3_V_4,
        instubdata_nentries_3_V_5,
        instubdata_nentries_3_V_6,
        instubdata_nentries_3_V_7,
        inprojdata_dataarray_data_V_address0,
        inprojdata_dataarray_data_V_ce0,
        inprojdata_dataarray_data_V_q0,
        inprojdata_nentries_0_V,
        inprojdata_nentries_1_V,
        outcandmatch_dataarray_data_V_address0,
        outcandmatch_dataarray_data_V_ce0,
        outcandmatch_dataarray_data_V_we0,
        outcandmatch_dataarray_data_V_d0,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_pp0_stage0 = 4'd2;
parameter    ap_ST_fsm_pp0_stage1 = 4'd4;
parameter    ap_ST_fsm_state9 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [2:0] bx_V;
output  [2:0] bx_o_V;
output   bx_o_V_ap_vld;
output  [8:0] instubdata_dataarray_data_V_address0;
output   instubdata_dataarray_data_V_ce0;
input  [13:0] instubdata_dataarray_data_V_q0;
input  [4:0] instubdata_nentries_0_V_0;
input  [4:0] instubdata_nentries_0_V_1;
input  [4:0] instubdata_nentries_0_V_2;
input  [4:0] instubdata_nentries_0_V_3;
input  [4:0] instubdata_nentries_0_V_4;
input  [4:0] instubdata_nentries_0_V_5;
input  [4:0] instubdata_nentries_0_V_6;
input  [4:0] instubdata_nentries_0_V_7;
input  [4:0] instubdata_nentries_1_V_0;
input  [4:0] instubdata_nentries_1_V_1;
input  [4:0] instubdata_nentries_1_V_2;
input  [4:0] instubdata_nentries_1_V_3;
input  [4:0] instubdata_nentries_1_V_4;
input  [4:0] instubdata_nentries_1_V_5;
input  [4:0] instubdata_nentries_1_V_6;
input  [4:0] instubdata_nentries_1_V_7;
input  [4:0] instubdata_nentries_2_V_0;
input  [4:0] instubdata_nentries_2_V_1;
input  [4:0] instubdata_nentries_2_V_2;
input  [4:0] instubdata_nentries_2_V_3;
input  [4:0] instubdata_nentries_2_V_4;
input  [4:0] instubdata_nentries_2_V_5;
input  [4:0] instubdata_nentries_2_V_6;
input  [4:0] instubdata_nentries_2_V_7;
input  [4:0] instubdata_nentries_3_V_0;
input  [4:0] instubdata_nentries_3_V_1;
input  [4:0] instubdata_nentries_3_V_2;
input  [4:0] instubdata_nentries_3_V_3;
input  [4:0] instubdata_nentries_3_V_4;
input  [4:0] instubdata_nentries_3_V_5;
input  [4:0] instubdata_nentries_3_V_6;
input  [4:0] instubdata_nentries_3_V_7;
output  [7:0] inprojdata_dataarray_data_V_address0;
output   inprojdata_dataarray_data_V_ce0;
input  [20:0] inprojdata_dataarray_data_V_q0;
input  [7:0] inprojdata_nentries_0_V;
input  [7:0] inprojdata_nentries_1_V;
output  [7:0] outcandmatch_dataarray_data_V_address0;
output   outcandmatch_dataarray_data_V_ce0;
output   outcandmatch_dataarray_data_V_we0;
output  [13:0] outcandmatch_dataarray_data_V_d0;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg bx_o_V_ap_vld;
reg instubdata_dataarray_data_V_ce0;
reg inprojdata_dataarray_data_V_ce0;
reg outcandmatch_dataarray_data_V_ce0;
reg outcandmatch_dataarray_data_V_we0;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [7:0] table1_address0;
reg    table1_ce0;
wire   [0:0] table1_q0;
reg   [2:0] writeindextmp_V_reg_577;
reg   [6:0] iprojtmp_V_reg_589;
reg   [6:0] p_4_reg_601;
reg   [0:0] moreproj1_reg_612;
wire   [0:0] tmp_3_fu_636_p1;
reg   [0:0] tmp_3_reg_2636;
wire   [7:0] nproj_V_fu_640_p3;
reg   [7:0] nproj_V_reg_2643;
wire   [0:0] moreproj_fu_648_p2;
wire   [1:0] tmp_4_fu_654_p1;
reg   [1:0] tmp_4_reg_2653;
wire   [9:0] tmp_20_cast_fu_666_p1;
reg   [9:0] tmp_20_cast_reg_2660;
wire   [0:0] tmp_8_fu_700_p2;
reg   [0:0] tmp_8_reg_2665;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state6_pp0_stage0_iter2;
wire    ap_block_state8_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_8_reg_2665_pp0_iter1_reg;
wire   [6:0] istep_V_fu_706_p2;
reg   [6:0] istep_V_reg_2669;
reg    ap_enable_reg_pp0_iter0;
wire   [6:0] iproj_V_fu_730_p2;
reg   [6:0] iproj_V_reg_2682;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_state5_pp0_stage1_iter1;
wire    ap_block_state7_pp0_stage1_iter2;
wire    ap_block_pp0_stage1_11001;
wire   [0:0] moreproj_2_fu_740_p2;
reg   [0:0] moreproj_2_reg_2687;
reg   [4:0] instubdata_nentries_s_reg_2692;
reg   [4:0] instubdata_nentries_1_reg_2698;
reg   [4:0] instubdata_nentries_2_reg_2704;
reg   [4:0] instubdata_nentries_3_reg_2710;
reg   [4:0] instubdata_nentries_4_reg_2716;
reg   [4:0] instubdata_nentries_5_reg_2722;
reg   [4:0] instubdata_nentries_6_reg_2728;
reg   [4:0] instubdata_nentries_7_reg_2734;
reg   [4:0] instubdata_nentries_8_reg_2740;
reg   [4:0] instubdata_nentries_9_reg_2746;
reg   [4:0] instubdata_nentries_10_reg_2752;
reg   [4:0] instubdata_nentries_11_reg_2758;
reg   [4:0] instubdata_nentries_12_reg_2764;
reg   [4:0] instubdata_nentries_13_reg_2770;
reg   [4:0] instubdata_nentries_14_reg_2776;
reg   [4:0] instubdata_nentries_15_reg_2782;
reg   [4:0] instubdata_nentries_16_reg_2788;
reg   [4:0] instubdata_nentries_17_reg_2794;
reg   [4:0] instubdata_nentries_18_reg_2800;
reg   [4:0] instubdata_nentries_19_reg_2806;
reg   [4:0] instubdata_nentries_20_reg_2812;
reg   [4:0] instubdata_nentries_21_reg_2818;
reg   [4:0] instubdata_nentries_22_reg_2824;
reg   [4:0] instubdata_nentries_23_reg_2830;
reg   [4:0] instubdata_nentries_24_reg_2836;
reg   [4:0] instubdata_nentries_25_reg_2842;
reg   [4:0] instubdata_nentries_26_reg_2848;
reg   [4:0] instubdata_nentries_27_reg_2854;
reg   [4:0] instubdata_nentries_28_reg_2860;
reg   [4:0] instubdata_nentries_29_reg_2866;
reg   [4:0] instubdata_nentries_30_reg_2872;
reg   [4:0] instubdata_nentries_31_reg_2878;
reg   [29:0] projbuffer_7_V_35_l_reg_2884;
reg   [29:0] projbuffer_7_V_29_l_reg_2892;
reg   [29:0] projbuffer_7_V_22_l_reg_2901;
reg   [29:0] projbuffer_7_V_8_lo_reg_2911;
reg   [29:0] projbuffer_7_V_44_l_reg_2922;
reg   [29:0] projbuffer_7_V_45_l_reg_2934;
reg   [29:0] projbuffer_7_V_load_reg_2947;
wire   [2:0] writeindexplus_V_fu_791_p2;
reg   [2:0] writeindexplus_V_reg_2960;
wire   [2:0] writeindex_V_3_fu_797_p2;
reg   [2:0] writeindex_V_3_reg_2965;
wire   [0:0] buffernotempty_fu_803_p2;
reg   [0:0] buffernotempty_reg_2970;
reg   [0:0] buffernotempty_reg_2970_pp0_iter2_reg;
wire   [0:0] brmerge_fu_833_p2;
reg   [0:0] brmerge_reg_2974;
wire   [0:0] savefirst_fu_965_p2;
reg   [0:0] savefirst_reg_2987;
wire   [0:0] savelast_fu_977_p2;
reg   [0:0] savelast_reg_3007;
wire   [29:0] projbuffer_7_V_178_fu_1001_p3;
reg   [29:0] projbuffer_7_V_178_reg_3020;
wire   [0:0] sel_tmp_fu_1009_p2;
reg   [0:0] sel_tmp_reg_3031;
wire   [0:0] sel_tmp5_fu_1015_p2;
reg   [0:0] sel_tmp5_reg_3039;
wire   [0:0] sel_tmp7_fu_1021_p2;
reg   [0:0] sel_tmp7_reg_3051;
wire   [0:0] sel_tmp9_fu_1027_p2;
reg   [0:0] sel_tmp9_reg_3066;
wire   [0:0] sel_tmp8_fu_1033_p2;
reg   [0:0] sel_tmp8_reg_3084;
wire   [29:0] projbuffer_7_V_179_fu_1073_p3;
reg   [29:0] projbuffer_7_V_179_reg_3109;
wire   [0:0] sel_tmp1_fu_1081_p2;
reg   [0:0] sel_tmp1_reg_3127;
wire   [6:0] iproj_V_1_fu_1127_p3;
reg    ap_enable_reg_pp0_iter1;
wire   [0:0] moreproj_1_fu_1134_p3;
reg   [0:0] moreproj_1_reg_3143;
reg   [3:0] istubtmp_V_reg_3148;
wire   [0:0] tmp_6_fu_1149_p2;
reg   [0:0] tmp_6_reg_3155;
reg   [6:0] projindex_V_reg_3159;
reg   [4:0] projrinv_V_reg_3164;
reg   [0:0] isPSseed_1_reg_3169;
wire   [4:0] projfinezadj_V_2_fu_1231_p3;
reg   [4:0] projfinezadj_V_2_reg_3174;
wire   [2:0] writeindex_V_fu_2195_p3;
reg   [2:0] writeindex_V_reg_3182;
reg   [6:0] stubindex_V_reg_3195;
wire   [0:0] pass_2_fu_2387_p3;
reg   [0:0] pass_2_reg_3200;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg   [2:0] ap_phi_mux_writeindextmp_V_phi_fu_581_p4;
wire    ap_block_pp0_stage0;
reg   [6:0] ap_phi_mux_iprojtmp_V_phi_fu_593_p4;
reg   [6:0] ap_phi_mux_p_4_phi_fu_605_p4;
reg   [0:0] ap_phi_mux_moreproj1_phi_fu_615_p4;
wire   [63:0] tmp_16_fu_719_p1;
wire   [63:0] tmp_21_fu_2296_p5;
wire    ap_block_pp0_stage1;
wire   [63:0] tmp_13_fu_2406_p1;
wire  signed [63:0] tmp_24_cast_fu_2440_p1;
wire   [0:0] tmp_14_fu_2425_p2;
reg   [29:0] projbuffer_7_V_40_fu_232;
wire   [29:0] projbuffer_7_V_177_fu_1119_p3;
reg   [29:0] projbuffer_7_V_35_fu_236;
wire   [29:0] projbuffer_7_V_176_fu_2171_p3;
reg   [29:0] projbuffer_7_V_29_fu_240;
wire   [29:0] projbuffer_7_V_175_fu_2165_p3;
reg   [29:0] projbuffer_7_V_22_fu_244;
wire   [29:0] projbuffer_7_V_174_fu_2159_p3;
reg   [29:0] projbuffer_7_V_8_fu_248;
wire   [29:0] projbuffer_7_V_173_fu_2153_p3;
reg   [29:0] projbuffer_7_V_44_fu_252;
wire   [29:0] projbuffer_7_V_172_fu_2147_p3;
reg   [29:0] projbuffer_7_V_45_fu_256;
wire   [29:0] projbuffer_7_V_171_fu_2141_p3;
reg   [29:0] projbuffer_7_V_fu_260;
wire   [29:0] projbuffer_7_V_7_fu_2135_p3;
reg   [7:0] outcandmatch_nentrie_2_fu_264;
wire   [7:0] outcandmatch_nentrie_4_fu_2462_p3;
wire    ap_CS_fsm_state9;
reg   [7:0] outcandmatch_nentrie_fu_268;
wire   [7:0] outcandmatch_nentrie_3_fu_2455_p3;
reg   [31:0] addr_index_assign_fu_272;
wire   [31:0] ncmatchout_fu_2482_p2;
reg   [0:0] isPSseed_fu_276;
reg   [3:0] nstubs_V_1_fu_280;
wire   [3:0] nstubs_V_fu_1155_p4;
wire   [0:0] tmp_7_fu_1239_p2;
reg   [4:0] projfinezadj_V_3_fu_284;
reg   [2:0] readindex_V_2_fu_288;
wire   [2:0] readindex_V_1_fu_1263_p2;
wire   [2:0] readindex_V_fu_2260_p2;
wire   [0:0] tmp_s_fu_2254_p2;
reg   [2:0] p_Repl2_s_fu_292;
reg   [6:0] p_Repl2_1_fu_296;
reg   [4:0] p_Repl2_2_fu_300;
reg   [3:0] istub_V_fu_304;
wire   [3:0] istub_V_1_fu_2271_p2;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] tmp_17_fu_724_p2;
wire   [7:0] tmp_9_fu_658_p3;
wire   [7:0] tmp_15_fu_712_p3;
wire   [7:0] tmp_cast_fu_736_p1;
wire   [0:0] notlhs_fu_815_p2;
wire   [0:0] moreproj_0_not_fu_809_p2;
wire   [0:0] tmp2_fu_827_p2;
wire   [0:0] notrhs_fu_821_p2;
wire   [0:0] tmp_18_fu_849_p3;
wire   [2:0] tmp_2_fu_857_p1;
wire   [2:0] zfirst_V_fu_839_p4;
wire   [4:0] tmp_4_i_fu_867_p3;
wire   [5:0] nstubfirst_V_fu_878_p33;
wire   [2:0] zlast_V_fu_861_p2;
wire   [4:0] tmp_4_i7_fu_916_p3;
wire   [5:0] nstublast_V_fu_927_p33;
wire   [4:0] nstubfirst_V_fu_878_p34;
wire   [4:0] nstublast_V_fu_927_p34;
wire   [0:0] not_tmp_3_fu_971_p2;
wire   [24:0] p_Result_s_fu_983_p4;
wire   [3:0] tmp_19_fu_997_p1;
wire   [25:0] tmp2_V_fu_993_p1;
wire   [29:0] projbuffer_7_V_80_fu_1039_p3;
wire   [24:0] p_Result_1_fu_1055_p4;
wire   [3:0] tmp_20_fu_1069_p1;
wire   [25:0] tmp2_V_1_fu_1065_p1;
wire   [29:0] projbuffer_7_V_87_fu_1047_p3;
wire   [29:0] projbuffer_7_V_122_fu_1087_p3;
wire   [29:0] projbuffer_7_V_156_fu_1095_p3;
wire   [29:0] projbuffer_7_V_163_fu_1103_p3;
wire   [29:0] projbuffer_7_V_170_fu_1111_p3;
wire   [29:0] qdata_V_fu_769_p10;
wire   [3:0] projfinez_V_fu_1185_p4;
wire   [3:0] projfinezadj_V_1_fu_1221_p2;
wire   [0:0] tmp_22_fu_1213_p1;
wire  signed [4:0] projfinezadj_V_1_cas_fu_1227_p1;
wire   [4:0] projfinezadj_V_fu_1217_p1;
wire   [29:0] projbuffer_7_V_9_fu_1287_p3;
wire   [29:0] projbuffer_7_V_47_fu_1292_p3;
wire   [29:0] projbuffer_7_V_48_fu_1298_p3;
wire   [0:0] sel_tmp2_fu_1310_p2;
wire   [29:0] projbuffer_7_V_49_fu_1304_p3;
wire   [0:0] sel_tmp4_fu_1323_p2;
wire   [29:0] projbuffer_7_V_50_fu_1316_p3;
wire   [29:0] projbuffer_7_V_51_fu_1329_p3;
wire   [29:0] projbuffer_7_V_52_fu_1342_p3;
wire   [29:0] projbuffer_7_V_53_fu_1347_p3;
wire   [29:0] projbuffer_7_V_54_fu_1353_p3;
wire   [29:0] projbuffer_7_V_55_fu_1359_p3;
wire   [29:0] projbuffer_7_V_57_fu_1365_p3;
wire   [29:0] projbuffer_7_V_58_fu_1372_p3;
wire   [29:0] projbuffer_7_V_60_fu_1385_p3;
wire   [29:0] projbuffer_7_V_61_fu_1390_p3;
wire   [29:0] projbuffer_7_V_62_fu_1396_p3;
wire   [29:0] projbuffer_7_V_63_fu_1402_p3;
wire   [29:0] projbuffer_7_V_64_fu_1409_p3;
wire   [29:0] projbuffer_7_V_66_fu_1422_p3;
wire   [29:0] projbuffer_7_V_67_fu_1427_p3;
wire   [29:0] projbuffer_7_V_68_fu_1433_p3;
wire   [29:0] projbuffer_7_V_69_fu_1440_p3;
wire   [29:0] projbuffer_7_V_71_fu_1453_p3;
wire   [29:0] projbuffer_7_V_72_fu_1458_p3;
wire   [29:0] projbuffer_7_V_73_fu_1465_p3;
wire   [29:0] projbuffer_7_V_75_fu_1478_p3;
wire   [29:0] projbuffer_7_V_76_fu_1484_p3;
wire   [29:0] projbuffer_7_V_78_fu_1497_p3;
wire   [29:0] projbuffer_7_V_1_fu_1336_p3;
wire   [29:0] projbuffer_7_V_59_fu_1379_p3;
wire   [29:0] projbuffer_7_V_65_fu_1416_p3;
wire   [29:0] projbuffer_7_V_70_fu_1447_p3;
wire   [29:0] projbuffer_7_V_74_fu_1472_p3;
wire   [29:0] projbuffer_7_V_77_fu_1491_p3;
wire   [29:0] projbuffer_7_V_79_fu_1503_p3;
wire   [29:0] projbuffer_7_V_2_fu_1509_p3;
wire   [29:0] projbuffer_7_V_89_fu_1551_p3;
wire   [29:0] projbuffer_7_V_90_fu_1557_p3;
wire   [29:0] projbuffer_7_V_91_fu_1564_p3;
wire   [29:0] projbuffer_7_V_92_fu_1571_p3;
wire   [29:0] projbuffer_7_V_93_fu_1579_p3;
wire   [29:0] projbuffer_7_V_94_fu_1587_p3;
wire   [29:0] projbuffer_7_V_81_fu_1515_p3;
wire   [29:0] projbuffer_7_V_95_fu_1601_p3;
wire   [29:0] projbuffer_7_V_96_fu_1607_p3;
wire   [29:0] projbuffer_7_V_97_fu_1614_p3;
wire   [29:0] projbuffer_7_V_98_fu_1621_p3;
wire   [29:0] projbuffer_7_V_99_fu_1629_p3;
wire   [29:0] projbuffer_7_V_100_fu_1637_p3;
wire   [29:0] projbuffer_7_V_82_fu_1521_p3;
wire   [29:0] projbuffer_7_V_102_fu_1651_p3;
wire   [29:0] projbuffer_7_V_103_fu_1657_p3;
wire   [29:0] projbuffer_7_V_104_fu_1664_p3;
wire   [29:0] projbuffer_7_V_105_fu_1672_p3;
wire   [29:0] projbuffer_7_V_106_fu_1680_p3;
wire   [29:0] projbuffer_7_V_83_fu_1527_p3;
wire   [29:0] projbuffer_7_V_108_fu_1694_p3;
wire   [29:0] projbuffer_7_V_109_fu_1700_p3;
wire   [29:0] projbuffer_7_V_110_fu_1708_p3;
wire   [29:0] projbuffer_7_V_111_fu_1716_p3;
wire   [29:0] projbuffer_7_V_84_fu_1533_p3;
wire   [29:0] projbuffer_7_V_113_fu_1730_p3;
wire   [29:0] projbuffer_7_V_114_fu_1737_p3;
wire   [29:0] projbuffer_7_V_115_fu_1745_p3;
wire   [29:0] projbuffer_7_V_85_fu_1539_p3;
wire   [29:0] projbuffer_7_V_117_fu_1759_p3;
wire   [29:0] projbuffer_7_V_118_fu_1766_p3;
wire   [29:0] projbuffer_7_V_86_fu_1545_p3;
wire   [29:0] projbuffer_7_V_120_fu_1780_p3;
wire   [29:0] projbuffer_7_V_123_fu_1793_p3;
wire   [29:0] projbuffer_7_V_124_fu_1799_p3;
wire   [29:0] projbuffer_7_V_125_fu_1806_p3;
wire   [29:0] projbuffer_7_V_126_fu_1813_p3;
wire   [29:0] projbuffer_7_V_127_fu_1820_p3;
wire   [29:0] projbuffer_7_V_128_fu_1828_p3;
wire   [29:0] projbuffer_7_V_129_fu_1843_p3;
wire   [29:0] projbuffer_7_V_130_fu_1849_p3;
wire   [29:0] projbuffer_7_V_131_fu_1856_p3;
wire   [29:0] projbuffer_7_V_132_fu_1863_p3;
wire   [29:0] projbuffer_7_V_133_fu_1870_p3;
wire   [29:0] projbuffer_7_V_134_fu_1878_p3;
wire   [29:0] projbuffer_7_V_136_fu_1893_p3;
wire   [29:0] projbuffer_7_V_137_fu_1899_p3;
wire   [29:0] projbuffer_7_V_138_fu_1906_p3;
wire   [29:0] projbuffer_7_V_139_fu_1913_p3;
wire   [29:0] projbuffer_7_V_140_fu_1921_p3;
wire   [29:0] projbuffer_7_V_142_fu_1936_p3;
wire   [29:0] projbuffer_7_V_143_fu_1942_p3;
wire   [29:0] projbuffer_7_V_144_fu_1949_p3;
wire   [29:0] projbuffer_7_V_145_fu_1957_p3;
wire   [29:0] projbuffer_7_V_147_fu_1972_p3;
wire   [29:0] projbuffer_7_V_148_fu_1978_p3;
wire   [29:0] projbuffer_7_V_149_fu_1986_p3;
wire   [29:0] projbuffer_7_V_151_fu_2001_p3;
wire   [29:0] projbuffer_7_V_152_fu_2008_p3;
wire   [29:0] projbuffer_7_V_154_fu_2023_p3;
wire   [29:0] projbuffer_7_V_3_fu_1594_p3;
wire   [29:0] projbuffer_7_V_4_fu_1836_p3;
wire   [29:0] projbuffer_7_V_101_fu_1644_p3;
wire   [29:0] projbuffer_7_V_135_fu_1886_p3;
wire   [29:0] projbuffer_7_V_107_fu_1687_p3;
wire   [29:0] projbuffer_7_V_141_fu_1929_p3;
wire   [29:0] projbuffer_7_V_112_fu_1723_p3;
wire   [29:0] projbuffer_7_V_146_fu_1965_p3;
wire   [29:0] projbuffer_7_V_116_fu_1752_p3;
wire   [29:0] projbuffer_7_V_150_fu_1994_p3;
wire   [29:0] projbuffer_7_V_119_fu_1773_p3;
wire   [29:0] projbuffer_7_V_153_fu_2016_p3;
wire   [29:0] projbuffer_7_V_121_fu_1786_p3;
wire   [29:0] projbuffer_7_V_155_fu_2030_p3;
wire   [29:0] projbuffer_7_V_5_fu_2037_p3;
wire   [29:0] projbuffer_7_V_157_fu_2044_p3;
wire   [29:0] projbuffer_7_V_158_fu_2051_p3;
wire   [29:0] projbuffer_7_V_159_fu_2058_p3;
wire   [29:0] projbuffer_7_V_160_fu_2065_p3;
wire   [29:0] projbuffer_7_V_161_fu_2072_p3;
wire   [29:0] projbuffer_7_V_162_fu_2079_p3;
wire   [29:0] projbuffer_7_V_6_fu_2086_p3;
wire   [29:0] projbuffer_7_V_164_fu_2093_p3;
wire   [29:0] projbuffer_7_V_165_fu_2100_p3;
wire   [29:0] projbuffer_7_V_166_fu_2107_p3;
wire   [29:0] projbuffer_7_V_167_fu_2114_p3;
wire   [29:0] projbuffer_7_V_168_fu_2121_p3;
wire   [29:0] projbuffer_7_V_169_fu_2128_p3;
wire   [0:0] brmerge1213_demorgan_fu_1279_p2;
wire   [0:0] brmerge1_fu_1283_p2;
wire   [0:0] or_cond_fu_2183_p2;
wire   [2:0] newSel_fu_2177_p3;
wire   [2:0] newSel1_fu_2188_p3;
wire   [4:0] lhs_V_cast_fu_2241_p1;
wire   [4:0] r_V_fu_2244_p2;
wire   [4:0] tmp_10_cast_fu_2250_p1;
wire   [3:0] stubfinez_V_fu_2327_p1;
wire   [4:0] tmp_1_fu_2341_p1;
wire   [4:0] idz_V_fu_2345_p2;
wire   [0:0] tmp_5_fu_2351_p2;
wire   [0:0] tmp_10_fu_2357_p2;
wire   [0:0] tmp_11_fu_2369_p2;
wire   [0:0] tmp_12_fu_2375_p2;
wire   [0:0] pass_fu_2363_p2;
wire   [0:0] pass_1_fu_2381_p2;
wire   [2:0] stubbend_V_fu_2331_p4;
wire   [7:0] p_Result_2_fu_2398_p3;
wire   [9:0] tmp_25_fu_2431_p1;
wire   [9:0] tmp_23_fu_2435_p2;
wire   [7:0] tmp_26_fu_2445_p1;
wire   [7:0] p_09_0_i_fu_2449_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

MatchEngine_1_0_sbkb #(
    .DataWidth( 1 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
table1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table1_address0),
    .ce0(table1_ce0),
    .q0(table1_q0)
);

MatchEngineTopL1_cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .din2_WIDTH( 30 ),
    .din3_WIDTH( 30 ),
    .din4_WIDTH( 30 ),
    .din5_WIDTH( 30 ),
    .din6_WIDTH( 30 ),
    .din7_WIDTH( 30 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 30 ))
MatchEngineTopL1_cud_U1(
    .din0(projbuffer_7_V_40_fu_232),
    .din1(projbuffer_7_V_35_fu_236),
    .din2(projbuffer_7_V_29_fu_240),
    .din3(projbuffer_7_V_22_fu_244),
    .din4(projbuffer_7_V_8_fu_248),
    .din5(projbuffer_7_V_44_fu_252),
    .din6(projbuffer_7_V_45_fu_256),
    .din7(projbuffer_7_V_fu_260),
    .din8(readindex_V_2_fu_288),
    .dout(qdata_V_fu_769_p10)
);

MatchEngineTopL1_dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 5 ),
    .din3_WIDTH( 5 ),
    .din4_WIDTH( 5 ),
    .din5_WIDTH( 5 ),
    .din6_WIDTH( 5 ),
    .din7_WIDTH( 5 ),
    .din8_WIDTH( 5 ),
    .din9_WIDTH( 5 ),
    .din10_WIDTH( 5 ),
    .din11_WIDTH( 5 ),
    .din12_WIDTH( 5 ),
    .din13_WIDTH( 5 ),
    .din14_WIDTH( 5 ),
    .din15_WIDTH( 5 ),
    .din16_WIDTH( 5 ),
    .din17_WIDTH( 5 ),
    .din18_WIDTH( 5 ),
    .din19_WIDTH( 5 ),
    .din20_WIDTH( 5 ),
    .din21_WIDTH( 5 ),
    .din22_WIDTH( 5 ),
    .din23_WIDTH( 5 ),
    .din24_WIDTH( 5 ),
    .din25_WIDTH( 5 ),
    .din26_WIDTH( 5 ),
    .din27_WIDTH( 5 ),
    .din28_WIDTH( 5 ),
    .din29_WIDTH( 5 ),
    .din30_WIDTH( 5 ),
    .din31_WIDTH( 5 ),
    .din32_WIDTH( 6 ),
    .dout_WIDTH( 5 ))
MatchEngineTopL1_dEe_U2(
    .din0(instubdata_nentries_s_reg_2692),
    .din1(instubdata_nentries_1_reg_2698),
    .din2(instubdata_nentries_2_reg_2704),
    .din3(instubdata_nentries_3_reg_2710),
    .din4(instubdata_nentries_4_reg_2716),
    .din5(instubdata_nentries_5_reg_2722),
    .din6(instubdata_nentries_6_reg_2728),
    .din7(instubdata_nentries_7_reg_2734),
    .din8(instubdata_nentries_8_reg_2740),
    .din9(instubdata_nentries_9_reg_2746),
    .din10(instubdata_nentries_10_reg_2752),
    .din11(instubdata_nentries_11_reg_2758),
    .din12(instubdata_nentries_12_reg_2764),
    .din13(instubdata_nentries_13_reg_2770),
    .din14(instubdata_nentries_14_reg_2776),
    .din15(instubdata_nentries_15_reg_2782),
    .din16(instubdata_nentries_16_reg_2788),
    .din17(instubdata_nentries_17_reg_2794),
    .din18(instubdata_nentries_18_reg_2800),
    .din19(instubdata_nentries_19_reg_2806),
    .din20(instubdata_nentries_20_reg_2812),
    .din21(instubdata_nentries_21_reg_2818),
    .din22(instubdata_nentries_22_reg_2824),
    .din23(instubdata_nentries_23_reg_2830),
    .din24(instubdata_nentries_24_reg_2836),
    .din25(instubdata_nentries_25_reg_2842),
    .din26(instubdata_nentries_26_reg_2848),
    .din27(instubdata_nentries_27_reg_2854),
    .din28(instubdata_nentries_28_reg_2860),
    .din29(instubdata_nentries_29_reg_2866),
    .din30(instubdata_nentries_30_reg_2872),
    .din31(instubdata_nentries_31_reg_2878),
    .din32(nstubfirst_V_fu_878_p33),
    .dout(nstubfirst_V_fu_878_p34)
);

MatchEngineTopL1_dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 5 ),
    .din3_WIDTH( 5 ),
    .din4_WIDTH( 5 ),
    .din5_WIDTH( 5 ),
    .din6_WIDTH( 5 ),
    .din7_WIDTH( 5 ),
    .din8_WIDTH( 5 ),
    .din9_WIDTH( 5 ),
    .din10_WIDTH( 5 ),
    .din11_WIDTH( 5 ),
    .din12_WIDTH( 5 ),
    .din13_WIDTH( 5 ),
    .din14_WIDTH( 5 ),
    .din15_WIDTH( 5 ),
    .din16_WIDTH( 5 ),
    .din17_WIDTH( 5 ),
    .din18_WIDTH( 5 ),
    .din19_WIDTH( 5 ),
    .din20_WIDTH( 5 ),
    .din21_WIDTH( 5 ),
    .din22_WIDTH( 5 ),
    .din23_WIDTH( 5 ),
    .din24_WIDTH( 5 ),
    .din25_WIDTH( 5 ),
    .din26_WIDTH( 5 ),
    .din27_WIDTH( 5 ),
    .din28_WIDTH( 5 ),
    .din29_WIDTH( 5 ),
    .din30_WIDTH( 5 ),
    .din31_WIDTH( 5 ),
    .din32_WIDTH( 6 ),
    .dout_WIDTH( 5 ))
MatchEngineTopL1_dEe_U3(
    .din0(instubdata_nentries_s_reg_2692),
    .din1(instubdata_nentries_1_reg_2698),
    .din2(instubdata_nentries_2_reg_2704),
    .din3(instubdata_nentries_3_reg_2710),
    .din4(instubdata_nentries_4_reg_2716),
    .din5(instubdata_nentries_5_reg_2722),
    .din6(instubdata_nentries_6_reg_2728),
    .din7(instubdata_nentries_7_reg_2734),
    .din8(instubdata_nentries_8_reg_2740),
    .din9(instubdata_nentries_9_reg_2746),
    .din10(instubdata_nentries_10_reg_2752),
    .din11(instubdata_nentries_11_reg_2758),
    .din12(instubdata_nentries_12_reg_2764),
    .din13(instubdata_nentries_13_reg_2770),
    .din14(instubdata_nentries_14_reg_2776),
    .din15(instubdata_nentries_15_reg_2782),
    .din16(instubdata_nentries_16_reg_2788),
    .din17(instubdata_nentries_17_reg_2794),
    .din18(instubdata_nentries_18_reg_2800),
    .din19(instubdata_nentries_19_reg_2806),
    .din20(instubdata_nentries_20_reg_2812),
    .din21(instubdata_nentries_21_reg_2818),
    .din22(instubdata_nentries_22_reg_2824),
    .din23(instubdata_nentries_23_reg_2830),
    .din24(instubdata_nentries_24_reg_2836),
    .din25(instubdata_nentries_25_reg_2842),
    .din26(instubdata_nentries_26_reg_2848),
    .din27(instubdata_nentries_27_reg_2854),
    .din28(instubdata_nentries_28_reg_2860),
    .din29(instubdata_nentries_29_reg_2866),
    .din30(instubdata_nentries_30_reg_2872),
    .din31(instubdata_nentries_31_reg_2878),
    .din32(nstublast_V_fu_927_p33),
    .dout(nstublast_V_fu_927_p34)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((table1_q0 == 1'd1) & (pass_2_reg_3200 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (buffernotempty_reg_2970_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        addr_index_assign_fu_272 <= ncmatchout_fu_2482_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        addr_index_assign_fu_272 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_8_reg_2665 == 1'd0))) begin
        iprojtmp_V_reg_589 <= iproj_V_1_fu_1127_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        iprojtmp_V_reg_589 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_2254_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (tmp_6_reg_3155 == 1'd0) & (buffernotempty_reg_2970 == 1'd0))) begin
        istub_V_fu_304 <= istub_V_1_fu_2271_p2;
    end else if (((tmp_6_fu_1149_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_7_fu_1239_p2 == 1'd0) & (buffernotempty_fu_803_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        istub_V_fu_304 <= 4'd1;
    end else if ((((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (tmp_s_fu_2254_p2 == 1'd0) & (tmp_6_reg_3155 == 1'd0) & (buffernotempty_reg_2970 == 1'd0)) | ((tmp_7_fu_1239_p2 == 1'd1) & (tmp_6_fu_1149_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (buffernotempty_fu_803_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        istub_V_fu_304 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_8_reg_2665_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        moreproj1_reg_612 <= moreproj_1_reg_3143;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        moreproj1_reg_612 <= moreproj_fu_648_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_fu_1239_p2 == 1'd1) & (tmp_6_fu_1149_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (buffernotempty_fu_803_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        nstubs_V_1_fu_280 <= 4'd1;
    end else if (((tmp_6_fu_1149_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_7_fu_1239_p2 == 1'd0) & (buffernotempty_fu_803_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        nstubs_V_1_fu_280 <= {{qdata_V_fu_769_p10[29:26]}};
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        nstubs_V_1_fu_280 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((table1_q0 == 1'd1) & (tmp_14_fu_2425_p2 == 1'd1) & (pass_2_reg_3200 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (buffernotempty_reg_2970_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outcandmatch_nentrie_2_fu_264 <= outcandmatch_nentrie_4_fu_2462_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        outcandmatch_nentrie_2_fu_264 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((table1_q0 == 1'd1) & (tmp_14_fu_2425_p2 == 1'd1) & (pass_2_reg_3200 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (buffernotempty_reg_2970_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outcandmatch_nentrie_fu_268 <= outcandmatch_nentrie_3_fu_2455_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        outcandmatch_nentrie_fu_268 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_8_reg_2665 == 1'd0))) begin
        p_4_reg_601 <= istep_V_reg_2669;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_4_reg_601 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_6_fu_1149_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (buffernotempty_fu_803_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Repl2_s_fu_292 <= {{qdata_V_fu_769_p10[3:1]}};
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_Repl2_s_fu_292 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (tmp_s_fu_2254_p2 == 1'd0) & (tmp_6_reg_3155 == 1'd0) & (buffernotempty_reg_2970 == 1'd0))) begin
        readindex_V_2_fu_288 <= readindex_V_fu_2260_p2;
    end else if (((tmp_7_fu_1239_p2 == 1'd1) & (tmp_6_fu_1149_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (buffernotempty_fu_803_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        readindex_V_2_fu_288 <= readindex_V_1_fu_1263_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        readindex_V_2_fu_288 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_8_reg_2665_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        writeindextmp_V_reg_577 <= writeindex_V_reg_3182;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        writeindextmp_V_reg_577 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_8_reg_2665 == 1'd0))) begin
        brmerge_reg_2974 <= brmerge_fu_833_p2;
        buffernotempty_reg_2970 <= buffernotempty_fu_803_p2;
        projbuffer_7_V_178_reg_3020[24 : 1] <= projbuffer_7_V_178_fu_1001_p3[24 : 1];
projbuffer_7_V_178_reg_3020[29 : 26] <= projbuffer_7_V_178_fu_1001_p3[29 : 26];
        projbuffer_7_V_179_reg_3109[24 : 1] <= projbuffer_7_V_179_fu_1073_p3[24 : 1];
projbuffer_7_V_179_reg_3109[29 : 26] <= projbuffer_7_V_179_fu_1073_p3[29 : 26];
        projbuffer_7_V_22_l_reg_2901 <= projbuffer_7_V_22_fu_244;
        projbuffer_7_V_29_l_reg_2892 <= projbuffer_7_V_29_fu_240;
        projbuffer_7_V_35_l_reg_2884 <= projbuffer_7_V_35_fu_236;
        projbuffer_7_V_44_l_reg_2922 <= projbuffer_7_V_44_fu_252;
        projbuffer_7_V_45_l_reg_2934 <= projbuffer_7_V_45_fu_256;
        projbuffer_7_V_8_lo_reg_2911 <= projbuffer_7_V_8_fu_248;
        projbuffer_7_V_load_reg_2947 <= projbuffer_7_V_fu_260;
        savefirst_reg_2987 <= savefirst_fu_965_p2;
        savelast_reg_3007 <= savelast_fu_977_p2;
        sel_tmp1_reg_3127 <= sel_tmp1_fu_1081_p2;
        sel_tmp5_reg_3039 <= sel_tmp5_fu_1015_p2;
        sel_tmp7_reg_3051 <= sel_tmp7_fu_1021_p2;
        sel_tmp8_reg_3084 <= sel_tmp8_fu_1033_p2;
        sel_tmp9_reg_3066 <= sel_tmp9_fu_1027_p2;
        sel_tmp_reg_3031 <= sel_tmp_fu_1009_p2;
        writeindex_V_3_reg_2965 <= writeindex_V_3_fu_797_p2;
        writeindexplus_V_reg_2960 <= writeindexplus_V_fu_791_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buffernotempty_reg_2970_pp0_iter2_reg <= buffernotempty_reg_2970;
        tmp_8_reg_2665 <= tmp_8_fu_700_p2;
        tmp_8_reg_2665_pp0_iter1_reg <= tmp_8_reg_2665;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (tmp_8_reg_2665 == 1'd0))) begin
        instubdata_nentries_10_reg_2752 <= instubdata_nentries_1_V_2;
        instubdata_nentries_11_reg_2758 <= instubdata_nentries_1_V_3;
        instubdata_nentries_12_reg_2764 <= instubdata_nentries_1_V_4;
        instubdata_nentries_13_reg_2770 <= instubdata_nentries_1_V_5;
        instubdata_nentries_14_reg_2776 <= instubdata_nentries_1_V_6;
        instubdata_nentries_15_reg_2782 <= instubdata_nentries_1_V_7;
        instubdata_nentries_16_reg_2788 <= instubdata_nentries_2_V_0;
        instubdata_nentries_17_reg_2794 <= instubdata_nentries_2_V_1;
        instubdata_nentries_18_reg_2800 <= instubdata_nentries_2_V_2;
        instubdata_nentries_19_reg_2806 <= instubdata_nentries_2_V_3;
        instubdata_nentries_1_reg_2698 <= instubdata_nentries_0_V_1;
        instubdata_nentries_20_reg_2812 <= instubdata_nentries_2_V_4;
        instubdata_nentries_21_reg_2818 <= instubdata_nentries_2_V_5;
        instubdata_nentries_22_reg_2824 <= instubdata_nentries_2_V_6;
        instubdata_nentries_23_reg_2830 <= instubdata_nentries_2_V_7;
        instubdata_nentries_24_reg_2836 <= instubdata_nentries_3_V_0;
        instubdata_nentries_25_reg_2842 <= instubdata_nentries_3_V_1;
        instubdata_nentries_26_reg_2848 <= instubdata_nentries_3_V_2;
        instubdata_nentries_27_reg_2854 <= instubdata_nentries_3_V_3;
        instubdata_nentries_28_reg_2860 <= instubdata_nentries_3_V_4;
        instubdata_nentries_29_reg_2866 <= instubdata_nentries_3_V_5;
        instubdata_nentries_2_reg_2704 <= instubdata_nentries_0_V_2;
        instubdata_nentries_30_reg_2872 <= instubdata_nentries_3_V_6;
        instubdata_nentries_31_reg_2878 <= instubdata_nentries_3_V_7;
        instubdata_nentries_3_reg_2710 <= instubdata_nentries_0_V_3;
        instubdata_nentries_4_reg_2716 <= instubdata_nentries_0_V_4;
        instubdata_nentries_5_reg_2722 <= instubdata_nentries_0_V_5;
        instubdata_nentries_6_reg_2728 <= instubdata_nentries_0_V_6;
        instubdata_nentries_7_reg_2734 <= instubdata_nentries_0_V_7;
        instubdata_nentries_8_reg_2740 <= instubdata_nentries_1_V_0;
        instubdata_nentries_9_reg_2746 <= instubdata_nentries_1_V_1;
        instubdata_nentries_s_reg_2692 <= instubdata_nentries_0_V_0;
        iproj_V_reg_2682 <= iproj_V_fu_730_p2;
        moreproj_2_reg_2687 <= moreproj_2_fu_740_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_6_fu_1149_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (buffernotempty_fu_803_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        isPSseed_1_reg_3169 <= qdata_V_fu_769_p10[32'd4];
        projfinezadj_V_2_reg_3174 <= projfinezadj_V_2_fu_1231_p3;
        projindex_V_reg_3159 <= {{qdata_V_fu_769_p10[24:18]}};
        projrinv_V_reg_3164 <= {{qdata_V_fu_769_p10[9:5]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_6_reg_3155 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (buffernotempty_reg_2970 == 1'd0))) begin
        isPSseed_fu_276 <= isPSseed_1_reg_3169;
        p_Repl2_2_fu_300 <= projrinv_V_reg_3164;
        projfinezadj_V_3_fu_284 <= projfinezadj_V_2_reg_3174;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        istep_V_reg_2669 <= istep_V_fu_706_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (buffernotempty_fu_803_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        istubtmp_V_reg_3148 <= istub_V_fu_304;
        tmp_6_reg_3155 <= tmp_6_fu_1149_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_8_reg_2665 == 1'd0))) begin
        moreproj_1_reg_3143 <= moreproj_1_fu_1134_p3;
        projbuffer_7_V_40_fu_232 <= projbuffer_7_V_177_fu_1119_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        nproj_V_reg_2643 <= nproj_V_fu_640_p3;
        tmp_20_cast_reg_2660[7] <= tmp_20_cast_fu_666_p1[7];
        tmp_3_reg_2636 <= tmp_3_fu_636_p1;
        tmp_4_reg_2653 <= tmp_4_fu_654_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_6_reg_3155 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (buffernotempty_reg_2970 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Repl2_1_fu_296 <= projindex_V_reg_3159;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (buffernotempty_reg_2970_pp0_iter2_reg == 1'd0))) begin
        pass_2_reg_3200 <= pass_2_fu_2387_p3;
        stubindex_V_reg_3195 <= {{instubdata_dataarray_data_V_q0[13:7]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (tmp_8_reg_2665_pp0_iter1_reg == 1'd0))) begin
        projbuffer_7_V_22_fu_244 <= projbuffer_7_V_174_fu_2159_p3;
        projbuffer_7_V_29_fu_240 <= projbuffer_7_V_175_fu_2165_p3;
        projbuffer_7_V_35_fu_236 <= projbuffer_7_V_176_fu_2171_p3;
        projbuffer_7_V_44_fu_252 <= projbuffer_7_V_172_fu_2147_p3;
        projbuffer_7_V_45_fu_256 <= projbuffer_7_V_171_fu_2141_p3;
        projbuffer_7_V_8_fu_248 <= projbuffer_7_V_173_fu_2153_p3;
        projbuffer_7_V_fu_260 <= projbuffer_7_V_7_fu_2135_p3;
        writeindex_V_reg_3182 <= writeindex_V_fu_2195_p3;
    end
end

always @ (*) begin
    if ((tmp_8_fu_700_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_8_reg_2665 == 1'd0))) begin
        ap_phi_mux_iprojtmp_V_phi_fu_593_p4 = iproj_V_1_fu_1127_p3;
    end else begin
        ap_phi_mux_iprojtmp_V_phi_fu_593_p4 = iprojtmp_V_reg_589;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_8_reg_2665_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_moreproj1_phi_fu_615_p4 = moreproj_1_reg_3143;
    end else begin
        ap_phi_mux_moreproj1_phi_fu_615_p4 = moreproj1_reg_612;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_8_reg_2665 == 1'd0))) begin
        ap_phi_mux_p_4_phi_fu_605_p4 = istep_V_reg_2669;
    end else begin
        ap_phi_mux_p_4_phi_fu_605_p4 = p_4_reg_601;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_8_reg_2665_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_writeindextmp_V_phi_fu_581_p4 = writeindex_V_reg_3182;
    end else begin
        ap_phi_mux_writeindextmp_V_phi_fu_581_p4 = writeindextmp_V_reg_577;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (tmp_17_fu_724_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_8_fu_700_p2 == 1'd0))) begin
        bx_o_V_ap_vld = 1'b1;
    end else begin
        bx_o_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inprojdata_dataarray_data_V_ce0 = 1'b1;
    end else begin
        inprojdata_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        instubdata_dataarray_data_V_ce0 = 1'b1;
    end else begin
        instubdata_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outcandmatch_dataarray_data_V_ce0 = 1'b1;
    end else begin
        outcandmatch_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((table1_q0 == 1'd1) & (tmp_14_fu_2425_p2 == 1'd1) & (pass_2_reg_3200 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (buffernotempty_reg_2970_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outcandmatch_dataarray_data_V_we0 = 1'b1;
    end else begin
        outcandmatch_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        table1_ce0 = 1'b1;
    end else begin
        table1_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (tmp_8_fu_700_p2 == 1'd1)) & ~((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (tmp_8_fu_700_p2 == 1'd1)) | ((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return_0 = outcandmatch_nentrie_fu_268;

assign ap_return_1 = outcandmatch_nentrie_2_fu_264;

assign brmerge1213_demorgan_fu_1279_p2 = (savelast_reg_3007 & savefirst_reg_2987);

assign brmerge1_fu_1283_p2 = (savelast_reg_3007 | savefirst_reg_2987);

assign brmerge_fu_833_p2 = (tmp2_fu_827_p2 | notrhs_fu_821_p2);

assign buffernotempty_fu_803_p2 = ((ap_phi_mux_writeindextmp_V_phi_fu_581_p4 == readindex_V_2_fu_288) ? 1'b1 : 1'b0);

assign bx_o_V = bx_V;

assign idz_V_fu_2345_p2 = (tmp_1_fu_2341_p1 - projfinezadj_V_3_fu_284);

assign inprojdata_dataarray_data_V_address0 = tmp_16_fu_719_p1;

assign instubdata_dataarray_data_V_address0 = tmp_21_fu_2296_p5;

assign iproj_V_1_fu_1127_p3 = ((brmerge_fu_833_p2[0:0] === 1'b1) ? iprojtmp_V_reg_589 : iproj_V_reg_2682);

assign iproj_V_fu_730_p2 = (7'd1 + iprojtmp_V_reg_589);

assign istep_V_fu_706_p2 = (ap_phi_mux_p_4_phi_fu_605_p4 + 7'd1);

assign istub_V_1_fu_2271_p2 = (istubtmp_V_reg_3148 + 4'd1);

assign lhs_V_cast_fu_2241_p1 = istubtmp_V_reg_3148;

assign moreproj_0_not_fu_809_p2 = (ap_phi_mux_moreproj1_phi_fu_615_p4 ^ 1'd1);

assign moreproj_1_fu_1134_p3 = ((brmerge_fu_833_p2[0:0] === 1'b1) ? ap_phi_mux_moreproj1_phi_fu_615_p4 : moreproj_2_reg_2687);

assign moreproj_2_fu_740_p2 = ((tmp_cast_fu_736_p1 < nproj_V_reg_2643) ? 1'b1 : 1'b0);

assign moreproj_fu_648_p2 = ((nproj_V_fu_640_p3 != 8'd0) ? 1'b1 : 1'b0);

assign ncmatchout_fu_2482_p2 = (addr_index_assign_fu_272 + 32'd1);

assign newSel1_fu_2188_p3 = ((brmerge1_fu_1283_p2[0:0] === 1'b1) ? writeindexplus_V_reg_2960 : writeindextmp_V_reg_577);

assign newSel_fu_2177_p3 = ((brmerge_reg_2974[0:0] === 1'b1) ? writeindextmp_V_reg_577 : writeindex_V_3_reg_2965);

assign not_tmp_3_fu_971_p2 = ((nstublast_V_fu_927_p34 != 5'd0) ? 1'b1 : 1'b0);

assign notlhs_fu_815_p2 = ((writeindex_V_3_fu_797_p2 == readindex_V_2_fu_288) ? 1'b1 : 1'b0);

assign notrhs_fu_821_p2 = ((writeindexplus_V_fu_791_p2 == readindex_V_2_fu_288) ? 1'b1 : 1'b0);

assign nproj_V_fu_640_p3 = ((tmp_3_fu_636_p1[0:0] === 1'b1) ? inprojdata_nentries_1_V : inprojdata_nentries_0_V);

assign nstubfirst_V_fu_878_p33 = tmp_4_i_fu_867_p3;

assign nstublast_V_fu_927_p33 = tmp_4_i7_fu_916_p3;

assign nstubs_V_fu_1155_p4 = {{qdata_V_fu_769_p10[29:26]}};

assign or_cond_fu_2183_p2 = (brmerge_reg_2974 | brmerge1213_demorgan_fu_1279_p2);

assign outcandmatch_dataarray_data_V_address0 = tmp_24_cast_fu_2440_p1;

assign outcandmatch_dataarray_data_V_d0 = {{p_Repl2_1_fu_296}, {stubindex_V_reg_3195}};

assign outcandmatch_nentrie_3_fu_2455_p3 = ((tmp_3_reg_2636[0:0] === 1'b1) ? outcandmatch_nentrie_fu_268 : p_09_0_i_fu_2449_p2);

assign outcandmatch_nentrie_4_fu_2462_p3 = ((tmp_3_reg_2636[0:0] === 1'b1) ? p_09_0_i_fu_2449_p2 : outcandmatch_nentrie_2_fu_264);

assign p_09_0_i_fu_2449_p2 = (8'd1 + tmp_26_fu_2445_p1);

assign p_Result_1_fu_1055_p4 = {{{inprojdata_dataarray_data_V_q0}, {zlast_V_fu_861_p2}}, {1'd1}};

assign p_Result_2_fu_2398_p3 = {{p_Repl2_2_fu_300}, {stubbend_V_fu_2331_p4}};

assign p_Result_s_fu_983_p4 = {{{inprojdata_dataarray_data_V_q0}, {zfirst_V_fu_839_p4}}, {1'd0}};

assign pass_1_fu_2381_p2 = (tmp_12_fu_2375_p2 & tmp_11_fu_2369_p2);

assign pass_2_fu_2387_p3 = ((isPSseed_fu_276[0:0] === 1'b1) ? pass_fu_2363_p2 : pass_1_fu_2381_p2);

assign pass_fu_2363_p2 = (tmp_5_fu_2351_p2 & tmp_10_fu_2357_p2);

assign projbuffer_7_V_100_fu_1637_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_81_fu_1515_p3 : projbuffer_7_V_99_fu_1629_p3);

assign projbuffer_7_V_101_fu_1644_p3 = ((sel_tmp1_reg_3127[0:0] === 1'b1) ? projbuffer_7_V_81_fu_1515_p3 : projbuffer_7_V_100_fu_1637_p3);

assign projbuffer_7_V_102_fu_1651_p3 = ((sel_tmp7_reg_3051[0:0] === 1'b1) ? projbuffer_7_V_179_reg_3109 : projbuffer_7_V_82_fu_1521_p3);

assign projbuffer_7_V_103_fu_1657_p3 = ((sel_tmp9_reg_3066[0:0] === 1'b1) ? projbuffer_7_V_82_fu_1521_p3 : projbuffer_7_V_102_fu_1651_p3);

assign projbuffer_7_V_104_fu_1664_p3 = ((sel_tmp2_fu_1310_p2[0:0] === 1'b1) ? projbuffer_7_V_82_fu_1521_p3 : projbuffer_7_V_103_fu_1657_p3);

assign projbuffer_7_V_105_fu_1672_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_82_fu_1521_p3 : projbuffer_7_V_104_fu_1664_p3);

assign projbuffer_7_V_106_fu_1680_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_82_fu_1521_p3 : projbuffer_7_V_105_fu_1672_p3);

assign projbuffer_7_V_107_fu_1687_p3 = ((sel_tmp1_reg_3127[0:0] === 1'b1) ? projbuffer_7_V_82_fu_1521_p3 : projbuffer_7_V_106_fu_1680_p3);

assign projbuffer_7_V_108_fu_1694_p3 = ((sel_tmp9_reg_3066[0:0] === 1'b1) ? projbuffer_7_V_179_reg_3109 : projbuffer_7_V_83_fu_1527_p3);

assign projbuffer_7_V_109_fu_1700_p3 = ((sel_tmp2_fu_1310_p2[0:0] === 1'b1) ? projbuffer_7_V_83_fu_1527_p3 : projbuffer_7_V_108_fu_1694_p3);

assign projbuffer_7_V_110_fu_1708_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_83_fu_1527_p3 : projbuffer_7_V_109_fu_1700_p3);

assign projbuffer_7_V_111_fu_1716_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_83_fu_1527_p3 : projbuffer_7_V_110_fu_1708_p3);

assign projbuffer_7_V_112_fu_1723_p3 = ((sel_tmp1_reg_3127[0:0] === 1'b1) ? projbuffer_7_V_83_fu_1527_p3 : projbuffer_7_V_111_fu_1716_p3);

assign projbuffer_7_V_113_fu_1730_p3 = ((sel_tmp2_fu_1310_p2[0:0] === 1'b1) ? projbuffer_7_V_179_reg_3109 : projbuffer_7_V_84_fu_1533_p3);

assign projbuffer_7_V_114_fu_1737_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_84_fu_1533_p3 : projbuffer_7_V_113_fu_1730_p3);

assign projbuffer_7_V_115_fu_1745_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_84_fu_1533_p3 : projbuffer_7_V_114_fu_1737_p3);

assign projbuffer_7_V_116_fu_1752_p3 = ((sel_tmp1_reg_3127[0:0] === 1'b1) ? projbuffer_7_V_84_fu_1533_p3 : projbuffer_7_V_115_fu_1745_p3);

assign projbuffer_7_V_117_fu_1759_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_179_reg_3109 : projbuffer_7_V_85_fu_1539_p3);

assign projbuffer_7_V_118_fu_1766_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_85_fu_1539_p3 : projbuffer_7_V_117_fu_1759_p3);

assign projbuffer_7_V_119_fu_1773_p3 = ((sel_tmp1_reg_3127[0:0] === 1'b1) ? projbuffer_7_V_85_fu_1539_p3 : projbuffer_7_V_118_fu_1766_p3);

assign projbuffer_7_V_120_fu_1780_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_179_reg_3109 : projbuffer_7_V_86_fu_1545_p3);

assign projbuffer_7_V_121_fu_1786_p3 = ((sel_tmp1_reg_3127[0:0] === 1'b1) ? projbuffer_7_V_86_fu_1545_p3 : projbuffer_7_V_120_fu_1780_p3);

assign projbuffer_7_V_122_fu_1087_p3 = ((sel_tmp1_fu_1081_p2[0:0] === 1'b1) ? projbuffer_7_V_179_fu_1073_p3 : projbuffer_7_V_87_fu_1047_p3);

assign projbuffer_7_V_123_fu_1793_p3 = ((sel_tmp_reg_3031[0:0] === 1'b1) ? projbuffer_7_V_2_fu_1509_p3 : projbuffer_7_V_179_reg_3109);

assign projbuffer_7_V_124_fu_1799_p3 = ((sel_tmp5_reg_3039[0:0] === 1'b1) ? projbuffer_7_V_2_fu_1509_p3 : projbuffer_7_V_123_fu_1793_p3);

assign projbuffer_7_V_125_fu_1806_p3 = ((sel_tmp7_reg_3051[0:0] === 1'b1) ? projbuffer_7_V_2_fu_1509_p3 : projbuffer_7_V_124_fu_1799_p3);

assign projbuffer_7_V_126_fu_1813_p3 = ((sel_tmp9_reg_3066[0:0] === 1'b1) ? projbuffer_7_V_2_fu_1509_p3 : projbuffer_7_V_125_fu_1806_p3);

assign projbuffer_7_V_127_fu_1820_p3 = ((sel_tmp2_fu_1310_p2[0:0] === 1'b1) ? projbuffer_7_V_2_fu_1509_p3 : projbuffer_7_V_126_fu_1813_p3);

assign projbuffer_7_V_128_fu_1828_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_2_fu_1509_p3 : projbuffer_7_V_127_fu_1820_p3);

assign projbuffer_7_V_129_fu_1843_p3 = ((sel_tmp_reg_3031[0:0] === 1'b1) ? projbuffer_7_V_179_reg_3109 : projbuffer_7_V_81_fu_1515_p3);

assign projbuffer_7_V_130_fu_1849_p3 = ((sel_tmp5_reg_3039[0:0] === 1'b1) ? projbuffer_7_V_81_fu_1515_p3 : projbuffer_7_V_129_fu_1843_p3);

assign projbuffer_7_V_131_fu_1856_p3 = ((sel_tmp7_reg_3051[0:0] === 1'b1) ? projbuffer_7_V_81_fu_1515_p3 : projbuffer_7_V_130_fu_1849_p3);

assign projbuffer_7_V_132_fu_1863_p3 = ((sel_tmp9_reg_3066[0:0] === 1'b1) ? projbuffer_7_V_81_fu_1515_p3 : projbuffer_7_V_131_fu_1856_p3);

assign projbuffer_7_V_133_fu_1870_p3 = ((sel_tmp2_fu_1310_p2[0:0] === 1'b1) ? projbuffer_7_V_81_fu_1515_p3 : projbuffer_7_V_132_fu_1863_p3);

assign projbuffer_7_V_134_fu_1878_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_81_fu_1515_p3 : projbuffer_7_V_133_fu_1870_p3);

assign projbuffer_7_V_135_fu_1886_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_81_fu_1515_p3 : projbuffer_7_V_134_fu_1878_p3);

assign projbuffer_7_V_136_fu_1893_p3 = ((sel_tmp5_reg_3039[0:0] === 1'b1) ? projbuffer_7_V_179_reg_3109 : projbuffer_7_V_82_fu_1521_p3);

assign projbuffer_7_V_137_fu_1899_p3 = ((sel_tmp7_reg_3051[0:0] === 1'b1) ? projbuffer_7_V_82_fu_1521_p3 : projbuffer_7_V_136_fu_1893_p3);

assign projbuffer_7_V_138_fu_1906_p3 = ((sel_tmp9_reg_3066[0:0] === 1'b1) ? projbuffer_7_V_82_fu_1521_p3 : projbuffer_7_V_137_fu_1899_p3);

assign projbuffer_7_V_139_fu_1913_p3 = ((sel_tmp2_fu_1310_p2[0:0] === 1'b1) ? projbuffer_7_V_82_fu_1521_p3 : projbuffer_7_V_138_fu_1906_p3);

assign projbuffer_7_V_140_fu_1921_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_82_fu_1521_p3 : projbuffer_7_V_139_fu_1913_p3);

assign projbuffer_7_V_141_fu_1929_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_82_fu_1521_p3 : projbuffer_7_V_140_fu_1921_p3);

assign projbuffer_7_V_142_fu_1936_p3 = ((sel_tmp7_reg_3051[0:0] === 1'b1) ? projbuffer_7_V_179_reg_3109 : projbuffer_7_V_83_fu_1527_p3);

assign projbuffer_7_V_143_fu_1942_p3 = ((sel_tmp9_reg_3066[0:0] === 1'b1) ? projbuffer_7_V_83_fu_1527_p3 : projbuffer_7_V_142_fu_1936_p3);

assign projbuffer_7_V_144_fu_1949_p3 = ((sel_tmp2_fu_1310_p2[0:0] === 1'b1) ? projbuffer_7_V_83_fu_1527_p3 : projbuffer_7_V_143_fu_1942_p3);

assign projbuffer_7_V_145_fu_1957_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_83_fu_1527_p3 : projbuffer_7_V_144_fu_1949_p3);

assign projbuffer_7_V_146_fu_1965_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_83_fu_1527_p3 : projbuffer_7_V_145_fu_1957_p3);

assign projbuffer_7_V_147_fu_1972_p3 = ((sel_tmp9_reg_3066[0:0] === 1'b1) ? projbuffer_7_V_179_reg_3109 : projbuffer_7_V_84_fu_1533_p3);

assign projbuffer_7_V_148_fu_1978_p3 = ((sel_tmp2_fu_1310_p2[0:0] === 1'b1) ? projbuffer_7_V_84_fu_1533_p3 : projbuffer_7_V_147_fu_1972_p3);

assign projbuffer_7_V_149_fu_1986_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_84_fu_1533_p3 : projbuffer_7_V_148_fu_1978_p3);

assign projbuffer_7_V_150_fu_1994_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_84_fu_1533_p3 : projbuffer_7_V_149_fu_1986_p3);

assign projbuffer_7_V_151_fu_2001_p3 = ((sel_tmp2_fu_1310_p2[0:0] === 1'b1) ? projbuffer_7_V_179_reg_3109 : projbuffer_7_V_85_fu_1539_p3);

assign projbuffer_7_V_152_fu_2008_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_85_fu_1539_p3 : projbuffer_7_V_151_fu_2001_p3);

assign projbuffer_7_V_153_fu_2016_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_85_fu_1539_p3 : projbuffer_7_V_152_fu_2008_p3);

assign projbuffer_7_V_154_fu_2023_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_179_reg_3109 : projbuffer_7_V_86_fu_1545_p3);

assign projbuffer_7_V_155_fu_2030_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_86_fu_1545_p3 : projbuffer_7_V_154_fu_2023_p3);

assign projbuffer_7_V_156_fu_1095_p3 = ((sel_tmp8_fu_1033_p2[0:0] === 1'b1) ? projbuffer_7_V_179_fu_1073_p3 : projbuffer_7_V_87_fu_1047_p3);

assign projbuffer_7_V_157_fu_2044_p3 = ((savefirst_reg_2987[0:0] === 1'b1) ? projbuffer_7_V_101_fu_1644_p3 : projbuffer_7_V_135_fu_1886_p3);

assign projbuffer_7_V_158_fu_2051_p3 = ((savefirst_reg_2987[0:0] === 1'b1) ? projbuffer_7_V_107_fu_1687_p3 : projbuffer_7_V_141_fu_1929_p3);

assign projbuffer_7_V_159_fu_2058_p3 = ((savefirst_reg_2987[0:0] === 1'b1) ? projbuffer_7_V_112_fu_1723_p3 : projbuffer_7_V_146_fu_1965_p3);

assign projbuffer_7_V_160_fu_2065_p3 = ((savefirst_reg_2987[0:0] === 1'b1) ? projbuffer_7_V_116_fu_1752_p3 : projbuffer_7_V_150_fu_1994_p3);

assign projbuffer_7_V_161_fu_2072_p3 = ((savefirst_reg_2987[0:0] === 1'b1) ? projbuffer_7_V_119_fu_1773_p3 : projbuffer_7_V_153_fu_2016_p3);

assign projbuffer_7_V_162_fu_2079_p3 = ((savefirst_reg_2987[0:0] === 1'b1) ? projbuffer_7_V_121_fu_1786_p3 : projbuffer_7_V_155_fu_2030_p3);

assign projbuffer_7_V_163_fu_1103_p3 = ((savefirst_fu_965_p2[0:0] === 1'b1) ? projbuffer_7_V_122_fu_1087_p3 : projbuffer_7_V_156_fu_1095_p3);

assign projbuffer_7_V_164_fu_2093_p3 = ((savelast_reg_3007[0:0] === 1'b1) ? projbuffer_7_V_157_fu_2044_p3 : projbuffer_7_V_81_fu_1515_p3);

assign projbuffer_7_V_165_fu_2100_p3 = ((savelast_reg_3007[0:0] === 1'b1) ? projbuffer_7_V_158_fu_2051_p3 : projbuffer_7_V_82_fu_1521_p3);

assign projbuffer_7_V_166_fu_2107_p3 = ((savelast_reg_3007[0:0] === 1'b1) ? projbuffer_7_V_159_fu_2058_p3 : projbuffer_7_V_83_fu_1527_p3);

assign projbuffer_7_V_167_fu_2114_p3 = ((savelast_reg_3007[0:0] === 1'b1) ? projbuffer_7_V_160_fu_2065_p3 : projbuffer_7_V_84_fu_1533_p3);

assign projbuffer_7_V_168_fu_2121_p3 = ((savelast_reg_3007[0:0] === 1'b1) ? projbuffer_7_V_161_fu_2072_p3 : projbuffer_7_V_85_fu_1539_p3);

assign projbuffer_7_V_169_fu_2128_p3 = ((savelast_reg_3007[0:0] === 1'b1) ? projbuffer_7_V_162_fu_2079_p3 : projbuffer_7_V_86_fu_1545_p3);

assign projbuffer_7_V_170_fu_1111_p3 = ((savelast_fu_977_p2[0:0] === 1'b1) ? projbuffer_7_V_163_fu_1103_p3 : projbuffer_7_V_87_fu_1047_p3);

assign projbuffer_7_V_171_fu_2141_p3 = ((brmerge_reg_2974[0:0] === 1'b1) ? projbuffer_7_V_45_l_reg_2934 : projbuffer_7_V_164_fu_2093_p3);

assign projbuffer_7_V_172_fu_2147_p3 = ((brmerge_reg_2974[0:0] === 1'b1) ? projbuffer_7_V_44_l_reg_2922 : projbuffer_7_V_165_fu_2100_p3);

assign projbuffer_7_V_173_fu_2153_p3 = ((brmerge_reg_2974[0:0] === 1'b1) ? projbuffer_7_V_8_lo_reg_2911 : projbuffer_7_V_166_fu_2107_p3);

assign projbuffer_7_V_174_fu_2159_p3 = ((brmerge_reg_2974[0:0] === 1'b1) ? projbuffer_7_V_22_l_reg_2901 : projbuffer_7_V_167_fu_2114_p3);

assign projbuffer_7_V_175_fu_2165_p3 = ((brmerge_reg_2974[0:0] === 1'b1) ? projbuffer_7_V_29_l_reg_2892 : projbuffer_7_V_168_fu_2121_p3);

assign projbuffer_7_V_176_fu_2171_p3 = ((brmerge_reg_2974[0:0] === 1'b1) ? projbuffer_7_V_35_l_reg_2884 : projbuffer_7_V_169_fu_2128_p3);

assign projbuffer_7_V_177_fu_1119_p3 = ((brmerge_fu_833_p2[0:0] === 1'b1) ? projbuffer_7_V_40_fu_232 : projbuffer_7_V_170_fu_1111_p3);

assign projbuffer_7_V_178_fu_1001_p3 = {{tmp_19_fu_997_p1}, {tmp2_V_fu_993_p1}};

assign projbuffer_7_V_179_fu_1073_p3 = {{tmp_20_fu_1069_p1}, {tmp2_V_1_fu_1065_p1}};

assign projbuffer_7_V_1_fu_1336_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_load_reg_2947 : projbuffer_7_V_51_fu_1329_p3);

assign projbuffer_7_V_2_fu_1509_p3 = ((savefirst_reg_2987[0:0] === 1'b1) ? projbuffer_7_V_1_fu_1336_p3 : projbuffer_7_V_load_reg_2947);

assign projbuffer_7_V_3_fu_1594_p3 = ((sel_tmp1_reg_3127[0:0] === 1'b1) ? projbuffer_7_V_2_fu_1509_p3 : projbuffer_7_V_94_fu_1587_p3);

assign projbuffer_7_V_47_fu_1292_p3 = ((sel_tmp5_reg_3039[0:0] === 1'b1) ? projbuffer_7_V_load_reg_2947 : projbuffer_7_V_9_fu_1287_p3);

assign projbuffer_7_V_48_fu_1298_p3 = ((sel_tmp7_reg_3051[0:0] === 1'b1) ? projbuffer_7_V_load_reg_2947 : projbuffer_7_V_47_fu_1292_p3);

assign projbuffer_7_V_49_fu_1304_p3 = ((sel_tmp9_reg_3066[0:0] === 1'b1) ? projbuffer_7_V_load_reg_2947 : projbuffer_7_V_48_fu_1298_p3);

assign projbuffer_7_V_4_fu_1836_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_2_fu_1509_p3 : projbuffer_7_V_128_fu_1828_p3);

assign projbuffer_7_V_50_fu_1316_p3 = ((sel_tmp2_fu_1310_p2[0:0] === 1'b1) ? projbuffer_7_V_load_reg_2947 : projbuffer_7_V_49_fu_1304_p3);

assign projbuffer_7_V_51_fu_1329_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_load_reg_2947 : projbuffer_7_V_50_fu_1316_p3);

assign projbuffer_7_V_52_fu_1342_p3 = ((sel_tmp_reg_3031[0:0] === 1'b1) ? projbuffer_7_V_178_reg_3020 : projbuffer_7_V_45_l_reg_2934);

assign projbuffer_7_V_53_fu_1347_p3 = ((sel_tmp5_reg_3039[0:0] === 1'b1) ? projbuffer_7_V_45_l_reg_2934 : projbuffer_7_V_52_fu_1342_p3);

assign projbuffer_7_V_54_fu_1353_p3 = ((sel_tmp7_reg_3051[0:0] === 1'b1) ? projbuffer_7_V_45_l_reg_2934 : projbuffer_7_V_53_fu_1347_p3);

assign projbuffer_7_V_55_fu_1359_p3 = ((sel_tmp9_reg_3066[0:0] === 1'b1) ? projbuffer_7_V_45_l_reg_2934 : projbuffer_7_V_54_fu_1353_p3);

assign projbuffer_7_V_57_fu_1365_p3 = ((sel_tmp2_fu_1310_p2[0:0] === 1'b1) ? projbuffer_7_V_45_l_reg_2934 : projbuffer_7_V_55_fu_1359_p3);

assign projbuffer_7_V_58_fu_1372_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_45_l_reg_2934 : projbuffer_7_V_57_fu_1365_p3);

assign projbuffer_7_V_59_fu_1379_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_45_l_reg_2934 : projbuffer_7_V_58_fu_1372_p3);

assign projbuffer_7_V_5_fu_2037_p3 = ((savefirst_reg_2987[0:0] === 1'b1) ? projbuffer_7_V_3_fu_1594_p3 : projbuffer_7_V_4_fu_1836_p3);

assign projbuffer_7_V_60_fu_1385_p3 = ((sel_tmp5_reg_3039[0:0] === 1'b1) ? projbuffer_7_V_178_reg_3020 : projbuffer_7_V_44_l_reg_2922);

assign projbuffer_7_V_61_fu_1390_p3 = ((sel_tmp7_reg_3051[0:0] === 1'b1) ? projbuffer_7_V_44_l_reg_2922 : projbuffer_7_V_60_fu_1385_p3);

assign projbuffer_7_V_62_fu_1396_p3 = ((sel_tmp9_reg_3066[0:0] === 1'b1) ? projbuffer_7_V_44_l_reg_2922 : projbuffer_7_V_61_fu_1390_p3);

assign projbuffer_7_V_63_fu_1402_p3 = ((sel_tmp2_fu_1310_p2[0:0] === 1'b1) ? projbuffer_7_V_44_l_reg_2922 : projbuffer_7_V_62_fu_1396_p3);

assign projbuffer_7_V_64_fu_1409_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_44_l_reg_2922 : projbuffer_7_V_63_fu_1402_p3);

assign projbuffer_7_V_65_fu_1416_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_44_l_reg_2922 : projbuffer_7_V_64_fu_1409_p3);

assign projbuffer_7_V_66_fu_1422_p3 = ((sel_tmp7_reg_3051[0:0] === 1'b1) ? projbuffer_7_V_178_reg_3020 : projbuffer_7_V_8_lo_reg_2911);

assign projbuffer_7_V_67_fu_1427_p3 = ((sel_tmp9_reg_3066[0:0] === 1'b1) ? projbuffer_7_V_8_lo_reg_2911 : projbuffer_7_V_66_fu_1422_p3);

assign projbuffer_7_V_68_fu_1433_p3 = ((sel_tmp2_fu_1310_p2[0:0] === 1'b1) ? projbuffer_7_V_8_lo_reg_2911 : projbuffer_7_V_67_fu_1427_p3);

assign projbuffer_7_V_69_fu_1440_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_8_lo_reg_2911 : projbuffer_7_V_68_fu_1433_p3);

assign projbuffer_7_V_6_fu_2086_p3 = ((savelast_reg_3007[0:0] === 1'b1) ? projbuffer_7_V_5_fu_2037_p3 : projbuffer_7_V_2_fu_1509_p3);

assign projbuffer_7_V_70_fu_1447_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_8_lo_reg_2911 : projbuffer_7_V_69_fu_1440_p3);

assign projbuffer_7_V_71_fu_1453_p3 = ((sel_tmp9_reg_3066[0:0] === 1'b1) ? projbuffer_7_V_178_reg_3020 : projbuffer_7_V_22_l_reg_2901);

assign projbuffer_7_V_72_fu_1458_p3 = ((sel_tmp2_fu_1310_p2[0:0] === 1'b1) ? projbuffer_7_V_22_l_reg_2901 : projbuffer_7_V_71_fu_1453_p3);

assign projbuffer_7_V_73_fu_1465_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_22_l_reg_2901 : projbuffer_7_V_72_fu_1458_p3);

assign projbuffer_7_V_74_fu_1472_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_22_l_reg_2901 : projbuffer_7_V_73_fu_1465_p3);

assign projbuffer_7_V_75_fu_1478_p3 = ((sel_tmp2_fu_1310_p2[0:0] === 1'b1) ? projbuffer_7_V_178_reg_3020 : projbuffer_7_V_29_l_reg_2892);

assign projbuffer_7_V_76_fu_1484_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_29_l_reg_2892 : projbuffer_7_V_75_fu_1478_p3);

assign projbuffer_7_V_77_fu_1491_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_29_l_reg_2892 : projbuffer_7_V_76_fu_1484_p3);

assign projbuffer_7_V_78_fu_1497_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_178_reg_3020 : projbuffer_7_V_35_l_reg_2884);

assign projbuffer_7_V_79_fu_1503_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_35_l_reg_2884 : projbuffer_7_V_78_fu_1497_p3);

assign projbuffer_7_V_7_fu_2135_p3 = ((brmerge_reg_2974[0:0] === 1'b1) ? projbuffer_7_V_load_reg_2947 : projbuffer_7_V_6_fu_2086_p3);

assign projbuffer_7_V_80_fu_1039_p3 = ((sel_tmp8_fu_1033_p2[0:0] === 1'b1) ? projbuffer_7_V_178_fu_1001_p3 : projbuffer_7_V_40_fu_232);

assign projbuffer_7_V_81_fu_1515_p3 = ((savefirst_reg_2987[0:0] === 1'b1) ? projbuffer_7_V_59_fu_1379_p3 : projbuffer_7_V_45_l_reg_2934);

assign projbuffer_7_V_82_fu_1521_p3 = ((savefirst_reg_2987[0:0] === 1'b1) ? projbuffer_7_V_65_fu_1416_p3 : projbuffer_7_V_44_l_reg_2922);

assign projbuffer_7_V_83_fu_1527_p3 = ((savefirst_reg_2987[0:0] === 1'b1) ? projbuffer_7_V_70_fu_1447_p3 : projbuffer_7_V_8_lo_reg_2911);

assign projbuffer_7_V_84_fu_1533_p3 = ((savefirst_reg_2987[0:0] === 1'b1) ? projbuffer_7_V_74_fu_1472_p3 : projbuffer_7_V_22_l_reg_2901);

assign projbuffer_7_V_85_fu_1539_p3 = ((savefirst_reg_2987[0:0] === 1'b1) ? projbuffer_7_V_77_fu_1491_p3 : projbuffer_7_V_29_l_reg_2892);

assign projbuffer_7_V_86_fu_1545_p3 = ((savefirst_reg_2987[0:0] === 1'b1) ? projbuffer_7_V_79_fu_1503_p3 : projbuffer_7_V_35_l_reg_2884);

assign projbuffer_7_V_87_fu_1047_p3 = ((savefirst_fu_965_p2[0:0] === 1'b1) ? projbuffer_7_V_80_fu_1039_p3 : projbuffer_7_V_40_fu_232);

assign projbuffer_7_V_89_fu_1551_p3 = ((sel_tmp5_reg_3039[0:0] === 1'b1) ? projbuffer_7_V_2_fu_1509_p3 : projbuffer_7_V_179_reg_3109);

assign projbuffer_7_V_90_fu_1557_p3 = ((sel_tmp7_reg_3051[0:0] === 1'b1) ? projbuffer_7_V_2_fu_1509_p3 : projbuffer_7_V_89_fu_1551_p3);

assign projbuffer_7_V_91_fu_1564_p3 = ((sel_tmp9_reg_3066[0:0] === 1'b1) ? projbuffer_7_V_2_fu_1509_p3 : projbuffer_7_V_90_fu_1557_p3);

assign projbuffer_7_V_92_fu_1571_p3 = ((sel_tmp2_fu_1310_p2[0:0] === 1'b1) ? projbuffer_7_V_2_fu_1509_p3 : projbuffer_7_V_91_fu_1564_p3);

assign projbuffer_7_V_93_fu_1579_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_2_fu_1509_p3 : projbuffer_7_V_92_fu_1571_p3);

assign projbuffer_7_V_94_fu_1587_p3 = ((sel_tmp8_reg_3084[0:0] === 1'b1) ? projbuffer_7_V_2_fu_1509_p3 : projbuffer_7_V_93_fu_1579_p3);

assign projbuffer_7_V_95_fu_1601_p3 = ((sel_tmp5_reg_3039[0:0] === 1'b1) ? projbuffer_7_V_179_reg_3109 : projbuffer_7_V_81_fu_1515_p3);

assign projbuffer_7_V_96_fu_1607_p3 = ((sel_tmp7_reg_3051[0:0] === 1'b1) ? projbuffer_7_V_81_fu_1515_p3 : projbuffer_7_V_95_fu_1601_p3);

assign projbuffer_7_V_97_fu_1614_p3 = ((sel_tmp9_reg_3066[0:0] === 1'b1) ? projbuffer_7_V_81_fu_1515_p3 : projbuffer_7_V_96_fu_1607_p3);

assign projbuffer_7_V_98_fu_1621_p3 = ((sel_tmp2_fu_1310_p2[0:0] === 1'b1) ? projbuffer_7_V_81_fu_1515_p3 : projbuffer_7_V_97_fu_1614_p3);

assign projbuffer_7_V_99_fu_1629_p3 = ((sel_tmp4_fu_1323_p2[0:0] === 1'b1) ? projbuffer_7_V_81_fu_1515_p3 : projbuffer_7_V_98_fu_1621_p3);

assign projbuffer_7_V_9_fu_1287_p3 = ((sel_tmp_reg_3031[0:0] === 1'b1) ? projbuffer_7_V_load_reg_2947 : projbuffer_7_V_178_reg_3020);

assign projfinez_V_fu_1185_p4 = {{qdata_V_fu_769_p10[13:10]}};

assign projfinezadj_V_1_cas_fu_1227_p1 = $signed(projfinezadj_V_1_fu_1221_p2);

assign projfinezadj_V_1_fu_1221_p2 = (projfinez_V_fu_1185_p4 ^ 4'd8);

assign projfinezadj_V_2_fu_1231_p3 = ((tmp_22_fu_1213_p1[0:0] === 1'b1) ? projfinezadj_V_1_cas_fu_1227_p1 : projfinezadj_V_fu_1217_p1);

assign projfinezadj_V_fu_1217_p1 = projfinez_V_fu_1185_p4;

assign r_V_fu_2244_p2 = (lhs_V_cast_fu_2241_p1 + 5'd1);

assign readindex_V_1_fu_1263_p2 = (readindex_V_2_fu_288 + 3'd1);

assign readindex_V_fu_2260_p2 = (readindex_V_2_fu_288 + 3'd1);

assign savefirst_fu_965_p2 = ((nstubfirst_V_fu_878_p34 != 5'd0) ? 1'b1 : 1'b0);

assign savelast_fu_977_p2 = (tmp_18_fu_849_p3 & not_tmp_3_fu_971_p2);

assign sel_tmp1_fu_1081_p2 = ((ap_phi_mux_writeindextmp_V_phi_fu_581_p4 == 3'd7) ? 1'b1 : 1'b0);

assign sel_tmp2_fu_1310_p2 = ((writeindextmp_V_reg_577 == 3'd2) ? 1'b1 : 1'b0);

assign sel_tmp4_fu_1323_p2 = ((writeindextmp_V_reg_577 == 3'd1) ? 1'b1 : 1'b0);

assign sel_tmp5_fu_1015_p2 = ((ap_phi_mux_writeindextmp_V_phi_fu_581_p4 == 3'd5) ? 1'b1 : 1'b0);

assign sel_tmp7_fu_1021_p2 = ((ap_phi_mux_writeindextmp_V_phi_fu_581_p4 == 3'd4) ? 1'b1 : 1'b0);

assign sel_tmp8_fu_1033_p2 = ((ap_phi_mux_writeindextmp_V_phi_fu_581_p4 == 3'd0) ? 1'b1 : 1'b0);

assign sel_tmp9_fu_1027_p2 = ((ap_phi_mux_writeindextmp_V_phi_fu_581_p4 == 3'd3) ? 1'b1 : 1'b0);

assign sel_tmp_fu_1009_p2 = ((ap_phi_mux_writeindextmp_V_phi_fu_581_p4 == 3'd6) ? 1'b1 : 1'b0);

assign stubbend_V_fu_2331_p4 = {{instubdata_dataarray_data_V_q0[6:4]}};

assign stubfinez_V_fu_2327_p1 = instubdata_dataarray_data_V_q0[3:0];

assign table1_address0 = tmp_13_fu_2406_p1;

assign tmp2_V_1_fu_1065_p1 = p_Result_1_fu_1055_p4;

assign tmp2_V_fu_993_p1 = p_Result_s_fu_983_p4;

assign tmp2_fu_827_p2 = (notlhs_fu_815_p2 | moreproj_0_not_fu_809_p2);

assign tmp_10_cast_fu_2250_p1 = nstubs_V_1_fu_280;

assign tmp_10_fu_2357_p2 = (($signed(idz_V_fu_2345_p2) < $signed(5'd3)) ? 1'b1 : 1'b0);

assign tmp_11_fu_2369_p2 = (($signed(idz_V_fu_2345_p2) > $signed(5'd26)) ? 1'b1 : 1'b0);

assign tmp_12_fu_2375_p2 = (($signed(idz_V_fu_2345_p2) < $signed(5'd6)) ? 1'b1 : 1'b0);

assign tmp_13_fu_2406_p1 = p_Result_2_fu_2398_p3;

assign tmp_14_fu_2425_p2 = (($signed(addr_index_assign_fu_272) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign tmp_15_fu_712_p3 = {{tmp_3_reg_2636}, {ap_phi_mux_iprojtmp_V_phi_fu_593_p4}};

assign tmp_16_fu_719_p1 = tmp_15_fu_712_p3;

assign tmp_17_fu_724_p2 = ((ap_phi_mux_p_4_phi_fu_605_p4 == 7'd107) ? 1'b1 : 1'b0);

assign tmp_18_fu_849_p3 = inprojdata_dataarray_data_V_q0[32'd10];

assign tmp_19_fu_997_p1 = nstubfirst_V_fu_878_p34[3:0];

assign tmp_1_fu_2341_p1 = stubfinez_V_fu_2327_p1;

assign tmp_20_cast_fu_666_p1 = tmp_9_fu_658_p3;

assign tmp_20_fu_1069_p1 = nstublast_V_fu_927_p34[3:0];

assign tmp_21_fu_2296_p5 = {{{{{{55'd0}, {tmp_4_reg_2653}}}, {p_Repl2_s_fu_292}}}, {istubtmp_V_reg_3148}};

assign tmp_22_fu_1213_p1 = qdata_V_fu_769_p10[0:0];

assign tmp_23_fu_2435_p2 = (tmp_25_fu_2431_p1 + tmp_20_cast_reg_2660);

assign tmp_24_cast_fu_2440_p1 = $signed(tmp_23_fu_2435_p2);

assign tmp_25_fu_2431_p1 = addr_index_assign_fu_272[9:0];

assign tmp_26_fu_2445_p1 = addr_index_assign_fu_272[7:0];

assign tmp_2_fu_857_p1 = tmp_18_fu_849_p3;

assign tmp_3_fu_636_p1 = bx_V[0:0];

assign tmp_4_fu_654_p1 = bx_V[1:0];

assign tmp_4_i7_fu_916_p3 = {{tmp_4_reg_2653}, {zlast_V_fu_861_p2}};

assign tmp_4_i_fu_867_p3 = {{tmp_4_reg_2653}, {zfirst_V_fu_839_p4}};

assign tmp_5_fu_2351_p2 = (($signed(idz_V_fu_2345_p2) > $signed(5'd29)) ? 1'b1 : 1'b0);

assign tmp_6_fu_1149_p2 = ((istub_V_fu_304 == 4'd0) ? 1'b1 : 1'b0);

assign tmp_7_fu_1239_p2 = ((nstubs_V_fu_1155_p4 == 4'd1) ? 1'b1 : 1'b0);

assign tmp_8_fu_700_p2 = ((ap_phi_mux_p_4_phi_fu_605_p4 == 7'd108) ? 1'b1 : 1'b0);

assign tmp_9_fu_658_p3 = {{tmp_3_fu_636_p1}, {7'd0}};

assign tmp_cast_fu_736_p1 = iproj_V_fu_730_p2;

assign tmp_s_fu_2254_p2 = ((r_V_fu_2244_p2 < tmp_10_cast_fu_2250_p1) ? 1'b1 : 1'b0);

assign writeindex_V_3_fu_797_p2 = (3'd2 + ap_phi_mux_writeindextmp_V_phi_fu_581_p4);

assign writeindex_V_fu_2195_p3 = ((or_cond_fu_2183_p2[0:0] === 1'b1) ? newSel_fu_2177_p3 : newSel1_fu_2188_p3);

assign writeindexplus_V_fu_791_p2 = (3'd1 + ap_phi_mux_writeindextmp_V_phi_fu_581_p4);

assign zfirst_V_fu_839_p4 = {{inprojdata_dataarray_data_V_q0[13:11]}};

assign zlast_V_fu_861_p2 = (tmp_2_fu_857_p1 + zfirst_V_fu_839_p4);

always @ (posedge ap_clk) begin
    tmp_20_cast_reg_2660[6:0] <= 7'b0000000;
    tmp_20_cast_reg_2660[9:8] <= 2'b00;
    projbuffer_7_V_178_reg_3020[0] <= 1'b0;
    projbuffer_7_V_178_reg_3020[25] <= 1'b0;
    projbuffer_7_V_179_reg_3109[0] <= 1'b1;
    projbuffer_7_V_179_reg_3109[25] <= 1'b0;
end

endmodule //MatchEngine_1_0_s
