// Test bench generated by generator_verilog.py

`timescale 1ns / 1ps

module SectorProcessor_test();

reg clk;
reg reset;

initial begin
  reset = 1'b1;
  clk   = 1'b1;
end

initial begin
  #1080
  reset = 1'b0;
end

reg en_proc = 1'b0;
always @(posedge clk) begin
  if (reset) en_proc = 1'b0;
  else       en_proc = 1'b1;
end

always begin
  #2.5 clk = ~clk;
end

reg[2:0] bx_in_MatchEngine;
initial bx_in_MatchEngine = 3'b110;
always begin
  #540 bx_in_MatchEngine <= bx_in_MatchEngine + 1'b1;
end
wire[2:0] bx_out_MatchEngine;

reg VMSME_L1PHIE20n1_dataarray_data_V_wea;
wire[7:0] VMSME_L1PHIE20n1_dataarray_data_V_writeaddr;
wire[13:0] VMSME_L1PHIE20n1_dataarray_data_V_din;
reg VMSME_L1PHIE20n1_nentries_0_0_V_we;
wire[3:0] VMSME_L1PHIE20n1_nentries_0_0_V_din;
reg VMSME_L1PHIE20n1_nentries_0_1_V_we;
wire[3:0] VMSME_L1PHIE20n1_nentries_0_1_V_din;
reg VMSME_L1PHIE20n1_nentries_0_2_V_we;
wire[3:0] VMSME_L1PHIE20n1_nentries_0_2_V_din;
reg VMSME_L1PHIE20n1_nentries_0_3_V_we;
wire[3:0] VMSME_L1PHIE20n1_nentries_0_3_V_din;
reg VMSME_L1PHIE20n1_nentries_0_4_V_we;
wire[3:0] VMSME_L1PHIE20n1_nentries_0_4_V_din;
reg VMSME_L1PHIE20n1_nentries_0_5_V_we;
wire[3:0] VMSME_L1PHIE20n1_nentries_0_5_V_din;
reg VMSME_L1PHIE20n1_nentries_0_6_V_we;
wire[3:0] VMSME_L1PHIE20n1_nentries_0_6_V_din;
reg VMSME_L1PHIE20n1_nentries_0_7_V_we;
wire[3:0] VMSME_L1PHIE20n1_nentries_0_7_V_din;
reg VMSME_L1PHIE20n1_nentries_1_0_V_we;
wire[3:0] VMSME_L1PHIE20n1_nentries_1_0_V_din;
reg 	VMSME_L1PHIE20n1_nentries_1_1_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_1_1_V_din;
reg 	VMSME_L1PHIE20n1_nentries_1_2_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_1_2_V_din;
reg 	VMSME_L1PHIE20n1_nentries_1_3_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_1_3_V_din;
reg 	VMSME_L1PHIE20n1_nentries_1_4_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_1_4_V_din;
reg 	VMSME_L1PHIE20n1_nentries_1_5_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_1_5_V_din;
reg 	VMSME_L1PHIE20n1_nentries_1_6_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_1_6_V_din;
reg 	VMSME_L1PHIE20n1_nentries_1_7_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_1_7_V_din;
reg 	VMSME_L1PHIE20n1_nentries_2_0_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_2_0_V_din;
reg 	VMSME_L1PHIE20n1_nentries_2_1_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_2_1_V_din;
reg 	VMSME_L1PHIE20n1_nentries_2_2_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_2_2_V_din;
reg 	VMSME_L1PHIE20n1_nentries_2_3_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_2_3_V_din;
reg 	VMSME_L1PHIE20n1_nentries_2_4_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_2_4_V_din;
reg 	VMSME_L1PHIE20n1_nentries_2_5_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_2_5_V_din;
reg 	VMSME_L1PHIE20n1_nentries_2_6_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_2_6_V_din;
reg 	VMSME_L1PHIE20n1_nentries_2_7_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_2_7_V_din;
reg 	VMSME_L1PHIE20n1_nentries_3_0_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_3_0_V_din;
reg 	VMSME_L1PHIE20n1_nentries_3_1_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_3_1_V_din;
reg 	VMSME_L1PHIE20n1_nentries_3_2_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_3_2_V_din;
reg 	VMSME_L1PHIE20n1_nentries_3_3_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_3_3_V_din;
reg 	VMSME_L1PHIE20n1_nentries_3_4_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_3_4_V_din;
reg 	VMSME_L1PHIE20n1_nentries_3_5_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_3_5_V_din;
reg 	VMSME_L1PHIE20n1_nentries_3_6_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_3_6_V_din;
reg 	VMSME_L1PHIE20n1_nentries_3_7_V_we;
wire [3:0] VMSME_L1PHIE20n1_nentries_3_7_V_din;
wire VMSME_L1PHIE20n1_dataarray_data_V_enb;
wire[8:0] VMSME_L1PHIE20n1_dataarray_data_V_readaddr;
wire[13:0] VMSME_L1PHIE20n1_dataarray_data_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_0_0_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_0_1_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_0_2_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_0_3_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_0_4_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_0_5_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_0_6_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_0_7_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_1_0_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_1_1_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_1_2_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_1_3_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_1_4_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_1_5_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_1_6_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_1_7_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_2_0_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_2_1_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_2_2_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_2_3_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_2_4_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_2_5_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_2_6_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_2_7_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_3_0_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_3_1_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_3_2_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_3_3_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_3_4_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_3_5_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_3_6_V_dout;
wire[3:0] VMSME_L1PHIE20n1_nentries_3_7_V_dout;
   

initial begin
  VMSME_L1PHIE20n1_nentries_0_0_V_we = 1'b1;
  VMSME_L1PHIE20n1_nentries_0_1_V_we = 1'b1;
  VMSME_L1PHIE20n1_nentries_0_2_V_we = 1'b1;
  VMSME_L1PHIE20n1_nentries_0_3_V_we = 1'b1;
  VMSME_L1PHIE20n1_nentries_0_4_V_we = 1'b1;
  VMSME_L1PHIE20n1_nentries_0_5_V_we = 1'b1;
  VMSME_L1PHIE20n1_nentries_0_6_V_we = 1'b1;
  VMSME_L1PHIE20n1_nentries_0_7_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_1_0_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_1_1_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_1_2_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_1_3_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_1_4_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_1_5_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_1_6_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_1_7_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_2_0_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_2_1_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_2_2_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_2_3_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_2_4_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_2_5_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_2_6_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_2_7_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_3_0_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_3_1_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_3_2_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_3_3_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_3_4_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_3_5_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_3_6_V_we = 1'b1;
   VMSME_L1PHIE20n1_nentries_3_7_V_we = 1'b1;
end

reg[3:0] VMSME_L1PHIE20n1_nentreg_0_0 = 4'b0001; // FIX
reg[3:0] VMSME_L1PHIE20n1_nentreg_0_1 = 4'b0010; // FIX
reg[3:0] VMSME_L1PHIE20n1_nentreg_0_2 = 4'b0010; // FIX
reg[3:0] VMSME_L1PHIE20n1_nentreg_0_3 = 4'b0101; // FIX
reg[3:0] VMSME_L1PHIE20n1_nentreg_0_4 = 4'b0100; // FIX
reg[3:0] VMSME_L1PHIE20n1_nentreg_0_5 = 4'b0000; // FIX
reg[3:0] VMSME_L1PHIE20n1_nentreg_0_6 = 4'b0000; // FIX
reg[3:0] VMSME_L1PHIE20n1_nentreg_0_7 = 4'b0010; // FIX
assign VMSME_L1PHIE20n1_nentries_0_0_V_din = VMSME_L1PHIE20n1_nentreg_0_0;
assign VMSME_L1PHIE20n1_nentries_0_1_V_din = VMSME_L1PHIE20n1_nentreg_0_1;
assign VMSME_L1PHIE20n1_nentries_0_2_V_din = VMSME_L1PHIE20n1_nentreg_0_2;
assign VMSME_L1PHIE20n1_nentries_0_3_V_din = VMSME_L1PHIE20n1_nentreg_0_3;
assign VMSME_L1PHIE20n1_nentries_0_4_V_din = VMSME_L1PHIE20n1_nentreg_0_4;
assign VMSME_L1PHIE20n1_nentries_0_5_V_din = VMSME_L1PHIE20n1_nentreg_0_5;
assign VMSME_L1PHIE20n1_nentries_0_6_V_din = VMSME_L1PHIE20n1_nentreg_0_6;
assign VMSME_L1PHIE20n1_nentries_0_7_V_din = VMSME_L1PHIE20n1_nentreg_0_7;
reg [3:0] VMSME_L1PHIE20n1_nentreg_1_0 = 4'b0001; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_1_1 = 4'b0010; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_1_2 = 4'b0010; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_1_3 = 4'b0010; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_1_4 = 4'b0101; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_1_5 = 4'b0100; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_1_6 = 4'b0000; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_1_7 = 4'b1001; // FIX
assign VMSME_L1PHIE20n1_nentries_1_0_V_din = VMSME_L1PHIE20n1_nentreg_1_0;
assign VMSME_L1PHIE20n1_nentries_1_1_V_din = VMSME_L1PHIE20n1_nentreg_1_1;
assign VMSME_L1PHIE20n1_nentries_1_2_V_din = VMSME_L1PHIE20n1_nentreg_1_2;
assign VMSME_L1PHIE20n1_nentries_1_3_V_din = VMSME_L1PHIE20n1_nentreg_1_3;
assign VMSME_L1PHIE20n1_nentries_1_4_V_din = VMSME_L1PHIE20n1_nentreg_1_4;
assign VMSME_L1PHIE20n1_nentries_1_5_V_din = VMSME_L1PHIE20n1_nentreg_1_5;
assign VMSME_L1PHIE20n1_nentries_1_6_V_din = VMSME_L1PHIE20n1_nentreg_1_6;
assign VMSME_L1PHIE20n1_nentries_1_7_V_din = VMSME_L1PHIE20n1_nentreg_1_7;
reg [3:0] VMSME_L1PHIE20n1_nentreg_2_0 = 4'b0000; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_2_1 = 4'b0000; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_2_2 = 4'b0000; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_2_3 = 4'b0000; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_2_4 = 4'b0000; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_2_5 = 4'b0000; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_2_6 = 4'b0000; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_2_7 = 4'b0000; // FIX
assign VMSME_L1PHIE20n1_nentries_2_0_V_din = VMSME_L1PHIE20n1_nentreg_2_0;
assign VMSME_L1PHIE20n1_nentries_2_1_V_din = VMSME_L1PHIE20n1_nentreg_2_1;
assign VMSME_L1PHIE20n1_nentries_2_2_V_din = VMSME_L1PHIE20n1_nentreg_2_2;
assign VMSME_L1PHIE20n1_nentries_2_3_V_din = VMSME_L1PHIE20n1_nentreg_2_3;
assign VMSME_L1PHIE20n1_nentries_2_4_V_din = VMSME_L1PHIE20n1_nentreg_2_4;
assign VMSME_L1PHIE20n1_nentries_2_5_V_din = VMSME_L1PHIE20n1_nentreg_2_5;
assign VMSME_L1PHIE20n1_nentries_2_6_V_din = VMSME_L1PHIE20n1_nentreg_2_6;
assign VMSME_L1PHIE20n1_nentries_2_7_V_din = VMSME_L1PHIE20n1_nentreg_2_7;
reg [3:0] VMSME_L1PHIE20n1_nentreg_3_0 = 4'b0000; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_3_1 = 4'b0000; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_3_2 = 4'b0000; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_3_3 = 4'b0000; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_3_4 = 4'b0000; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_3_5 = 4'b0000; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_3_6 = 4'b0000; // FIX
reg [3:0] VMSME_L1PHIE20n1_nentreg_3_7 = 4'b0000; // FIX
assign VMSME_L1PHIE20n1_nentries_3_0_V_din = VMSME_L1PHIE20n1_nentreg_3_0;
assign VMSME_L1PHIE20n1_nentries_3_1_V_din = VMSME_L1PHIE20n1_nentreg_3_1;
assign VMSME_L1PHIE20n1_nentries_3_2_V_din = VMSME_L1PHIE20n1_nentreg_3_2;
assign VMSME_L1PHIE20n1_nentries_3_3_V_din = VMSME_L1PHIE20n1_nentreg_3_3;
assign VMSME_L1PHIE20n1_nentries_3_4_V_din = VMSME_L1PHIE20n1_nentreg_3_4;
assign VMSME_L1PHIE20n1_nentries_3_5_V_din = VMSME_L1PHIE20n1_nentreg_3_5;
assign VMSME_L1PHIE20n1_nentries_3_6_V_din = VMSME_L1PHIE20n1_nentreg_3_6;
assign VMSME_L1PHIE20n1_nentries_3_7_V_din = VMSME_L1PHIE20n1_nentreg_3_7;

// // // // // // // //    

   
MemoryBinned #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256), //This is only 2 pages, want 4 pages eventually
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(1),
  .INIT_FILE("VMStubs_VMSME_L1PHIE20n1_04.dat")
) VMSME_L1PHIE20n1 (
  .clka(clk),
  .clkb(clk),
  .wea(VMSME_L1PHIE20n1_dataarray_data_V_wea),
  .addra(VMSME_L1PHIE20n1_dataarray_data_V_writeaddr),
  .dina(VMSME_L1PHIE20n1_dataarray_data_V_din),
  .nent_0_we0(VMSME_L1PHIE20n1_nentries_0_0_V_we),
  .nent_0_i0(VMSME_L1PHIE20n1_nentries_0_0_V_din),
  .nent_0_we1(VMSME_L1PHIE20n1_nentries_0_1_V_we),
  .nent_0_i1(VMSME_L1PHIE20n1_nentries_0_1_V_din),
  .nent_0_we2(VMSME_L1PHIE20n1_nentries_0_2_V_we),
  .nent_0_i2(VMSME_L1PHIE20n1_nentries_0_2_V_din),
  .nent_0_we3(VMSME_L1PHIE20n1_nentries_0_3_V_we),
  .nent_0_i3(VMSME_L1PHIE20n1_nentries_0_3_V_din),
  .nent_0_we4(VMSME_L1PHIE20n1_nentries_0_4_V_we),
  .nent_0_i4(VMSME_L1PHIE20n1_nentries_0_4_V_din),
  .nent_0_we5(VMSME_L1PHIE20n1_nentries_0_5_V_we),
  .nent_0_i5(VMSME_L1PHIE20n1_nentries_0_5_V_din),
  .nent_0_we6(VMSME_L1PHIE20n1_nentries_0_6_V_we),
  .nent_0_i6(VMSME_L1PHIE20n1_nentries_0_6_V_din),
  .nent_0_we7(VMSME_L1PHIE20n1_nentries_0_7_V_we),
  .nent_0_i7(VMSME_L1PHIE20n1_nentries_0_7_V_din),
  .nent_1_we0(VMSME_L1PHIE20n1_nentries_1_0_V_we),
  .nent_1_i0(VMSME_L1PHIE20n1_nentries_1_0_V_din),
  .nent_1_we1(VMSME_L1PHIE20n1_nentries_1_1_V_we),
  .nent_1_i1(VMSME_L1PHIE20n1_nentries_1_1_V_din),
  .nent_1_we2(VMSME_L1PHIE20n1_nentries_1_2_V_we),
  .nent_1_i2(VMSME_L1PHIE20n1_nentries_1_2_V_din),
  .nent_1_we3(VMSME_L1PHIE20n1_nentries_1_3_V_we),
  .nent_1_i3(VMSME_L1PHIE20n1_nentries_1_3_V_din),
  .nent_1_we4(VMSME_L1PHIE20n1_nentries_1_4_V_we),
  .nent_1_i4(VMSME_L1PHIE20n1_nentries_1_4_V_din),
  .nent_1_we5(VMSME_L1PHIE20n1_nentries_1_5_V_we),
  .nent_1_i5(VMSME_L1PHIE20n1_nentries_1_5_V_din),
  .nent_1_we6(VMSME_L1PHIE20n1_nentries_1_6_V_we),
  .nent_1_i6(VMSME_L1PHIE20n1_nentries_1_6_V_din),
  .nent_1_we7(VMSME_L1PHIE20n1_nentries_1_7_V_we),
  .nent_1_i7(VMSME_L1PHIE20n1_nentries_1_7_V_din),
  .nent_2_we0(VMSME_L1PHIE20n1_nentries_2_0_V_we),
  .nent_2_i0(VMSME_L1PHIE20n1_nentries_2_0_V_din),
  .nent_2_we1(VMSME_L1PHIE20n1_nentries_2_1_V_we),
  .nent_2_i1(VMSME_L1PHIE20n1_nentries_2_1_V_din),
  .nent_2_we2(VMSME_L1PHIE20n1_nentries_2_2_V_we),
  .nent_2_i2(VMSME_L1PHIE20n1_nentries_2_2_V_din),
  .nent_2_we3(VMSME_L1PHIE20n1_nentries_2_3_V_we),
  .nent_2_i3(VMSME_L1PHIE20n1_nentries_2_3_V_din),
  .nent_2_we4(VMSME_L1PHIE20n1_nentries_2_4_V_we),
  .nent_2_i4(VMSME_L1PHIE20n1_nentries_2_4_V_din),
  .nent_2_we5(VMSME_L1PHIE20n1_nentries_2_5_V_we),
  .nent_2_i5(VMSME_L1PHIE20n1_nentries_2_5_V_din),
  .nent_2_we6(VMSME_L1PHIE20n1_nentries_2_6_V_we),
  .nent_2_i6(VMSME_L1PHIE20n1_nentries_2_6_V_din),
  .nent_2_we7(VMSME_L1PHIE20n1_nentries_2_7_V_we),
  .nent_2_i7(VMSME_L1PHIE20n1_nentries_2_7_V_din),
  .nent_3_we0(VMSME_L1PHIE20n1_nentries_3_0_V_we),
  .nent_3_i0(VMSME_L1PHIE20n1_nentries_3_0_V_din),
  .nent_3_we1(VMSME_L1PHIE20n1_nentries_3_1_V_we),
  .nent_3_i1(VMSME_L1PHIE20n1_nentries_3_1_V_din),
  .nent_3_we2(VMSME_L1PHIE20n1_nentries_3_2_V_we),
  .nent_3_i2(VMSME_L1PHIE20n1_nentries_3_2_V_din),
  .nent_3_we3(VMSME_L1PHIE20n1_nentries_3_3_V_we),
  .nent_3_i3(VMSME_L1PHIE20n1_nentries_3_3_V_din),
  .nent_3_we4(VMSME_L1PHIE20n1_nentries_3_4_V_we),
  .nent_3_i4(VMSME_L1PHIE20n1_nentries_3_4_V_din),
  .nent_3_we5(VMSME_L1PHIE20n1_nentries_3_5_V_we),
  .nent_3_i5(VMSME_L1PHIE20n1_nentries_3_5_V_din),
  .nent_3_we6(VMSME_L1PHIE20n1_nentries_3_6_V_we),
  .nent_3_i6(VMSME_L1PHIE20n1_nentries_3_6_V_din),
  .nent_3_we7(VMSME_L1PHIE20n1_nentries_3_7_V_we),
  .nent_3_i7(VMSME_L1PHIE20n1_nentries_3_7_V_din),		    
  .enb(VMSME_L1PHIE20n1_dataarray_data_V_enb),
  .addrb(VMSME_L1PHIE20n1_dataarray_data_V_readaddr),
  .doutb(VMSME_L1PHIE20n1_dataarray_data_V_dout),
  .nent_0_o0(VMSME_L1PHIE20n1_nentries_0_0_V_dout),
  .nent_0_o1(VMSME_L1PHIE20n1_nentries_0_1_V_dout),
  .nent_0_o2(VMSME_L1PHIE20n1_nentries_0_2_V_dout),
  .nent_0_o3(VMSME_L1PHIE20n1_nentries_0_3_V_dout),
  .nent_0_o4(VMSME_L1PHIE20n1_nentries_0_4_V_dout),
  .nent_0_o5(VMSME_L1PHIE20n1_nentries_0_5_V_dout),
  .nent_0_o6(VMSME_L1PHIE20n1_nentries_0_6_V_dout),
  .nent_0_o7(VMSME_L1PHIE20n1_nentries_0_7_V_dout),
  .nent_1_o0(VMSME_L1PHIE20n1_nentries_1_0_V_dout),
  .nent_1_o1(VMSME_L1PHIE20n1_nentries_1_1_V_dout),
  .nent_1_o2(VMSME_L1PHIE20n1_nentries_1_2_V_dout),
  .nent_1_o3(VMSME_L1PHIE20n1_nentries_1_3_V_dout),
  .nent_1_o4(VMSME_L1PHIE20n1_nentries_1_4_V_dout),
  .nent_1_o5(VMSME_L1PHIE20n1_nentries_1_5_V_dout),
  .nent_1_o6(VMSME_L1PHIE20n1_nentries_1_6_V_dout),
  .nent_1_o7(VMSME_L1PHIE20n1_nentries_1_7_V_dout),
  .nent_2_o0(VMSME_L1PHIE20n1_nentries_2_0_V_dout),
  .nent_2_o1(VMSME_L1PHIE20n1_nentries_2_1_V_dout),
  .nent_2_o2(VMSME_L1PHIE20n1_nentries_2_2_V_dout),
  .nent_2_o3(VMSME_L1PHIE20n1_nentries_2_3_V_dout),
  .nent_2_o4(VMSME_L1PHIE20n1_nentries_2_4_V_dout),
  .nent_2_o5(VMSME_L1PHIE20n1_nentries_2_5_V_dout),
  .nent_2_o6(VMSME_L1PHIE20n1_nentries_2_6_V_dout),
  .nent_2_o7(VMSME_L1PHIE20n1_nentries_2_7_V_dout),
  .nent_3_o0(VMSME_L1PHIE20n1_nentries_3_0_V_dout),
  .nent_3_o1(VMSME_L1PHIE20n1_nentries_3_1_V_dout),
  .nent_3_o2(VMSME_L1PHIE20n1_nentries_3_2_V_dout),
  .nent_3_o3(VMSME_L1PHIE20n1_nentries_3_3_V_dout),
  .nent_3_o4(VMSME_L1PHIE20n1_nentries_3_4_V_dout),
  .nent_3_o5(VMSME_L1PHIE20n1_nentries_3_5_V_dout),
  .nent_3_o6(VMSME_L1PHIE20n1_nentries_3_6_V_dout),
  .nent_3_o7(VMSME_L1PHIE20n1_nentries_3_7_V_dout),		    
  .regceb(1'b1)
);

reg VMPROJ_L1PHIE20_dataarray_data_V_wea;
wire[7:0] VMPROJ_L1PHIE20_dataarray_data_V_writeaddr;
wire[20:0] VMPROJ_L1PHIE20_dataarray_data_V_din;
reg VMPROJ_L1PHIE20_nentries_0_V_we;
wire[6:0] VMPROJ_L1PHIE20_nentries_0_V_din;
reg VMPROJ_L1PHIE20_nentries_1_V_we;
wire[6:0] VMPROJ_L1PHIE20_nentries_1_V_din;
wire VMPROJ_L1PHIE20_dataarray_data_V_enb;
wire[7:0] VMPROJ_L1PHIE20_dataarray_data_V_readaddr;
wire[20:0] VMPROJ_L1PHIE20_dataarray_data_V_dout;
wire[6:0] VMPROJ_L1PHIE20_nentries_0_V_dout;
wire[6:0] VMPROJ_L1PHIE20_nentries_1_V_dout;

initial begin
  VMPROJ_L1PHIE20_nentries_0_V_we = 1'b1;
  VMPROJ_L1PHIE20_nentries_1_V_we = 1'b1;
end

reg[6:0] VMPROJ_L1PHIE20_nentreg_0 = 7'b0000011; // FIX
reg[6:0] VMPROJ_L1PHIE20_nentreg_1 = 7'b0000011; // FIX
assign VMPROJ_L1PHIE20_nentries_0_V_din = VMPROJ_L1PHIE20_nentreg_0;
assign VMPROJ_L1PHIE20_nentries_1_V_din = VMPROJ_L1PHIE20_nentreg_1;

Memory #(
  .RAM_WIDTH(21),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(1),
  .INIT_FILE("VMProjections_VMPROJ_L1PHIE20_04.dat")
) VMPROJ_L1PHIE20 (
  .clka(clk),
  .clkb(clk),
  .wea(VMPROJ_L1PHIE20_dataarray_data_V_wea),
  .addra(VMPROJ_L1PHIE20_dataarray_data_V_writeaddr),
  .dina(VMPROJ_L1PHIE20_dataarray_data_V_din),
  .nent_we0(VMPROJ_L1PHIE20_nentries_0_V_we),
  .nent_i0(VMPROJ_L1PHIE20_nentries_0_V_din),
  .nent_we1(VMPROJ_L1PHIE20_nentries_1_V_we),
  .nent_i1(VMPROJ_L1PHIE20_nentries_1_V_din),
  .enb(VMPROJ_L1PHIE20_dataarray_data_V_enb),
  .addrb(VMPROJ_L1PHIE20_dataarray_data_V_readaddr),
  .doutb(VMPROJ_L1PHIE20_dataarray_data_V_dout),
  .nent_o0(VMPROJ_L1PHIE20_nentries_0_V_dout),
  .nent_o1(VMPROJ_L1PHIE20_nentries_1_V_dout),
  .regceb(1'b1)
);


wire CM_L1PHIE20_dataarray_data_V_wea;
wire[7:0] CM_L1PHIE20_dataarray_data_V_writeaddr;
wire[13:0] CM_L1PHIE20_dataarray_data_V_din;
wire CM_L1PHIE20_nentries_0_V_we;
wire[6:0] CM_L1PHIE20_nentries_0_V_din;
wire CM_L1PHIE20_nentries_1_V_we;
wire[6:0] CM_L1PHIE20_nentries_1_V_din;
wire CM_L1PHIE20_dataarray_data_V_enb;
wire[7:0] CM_L1PHIE20_dataarray_data_V_readaddr;
wire[13:0] CM_L1PHIE20_dataarray_data_V_dout;
wire[6:0] CM_L1PHIE20_nentries_0_V_dout;
wire[6:0] CM_L1PHIE20_nentries_1_V_dout;

Memory #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) CM_L1PHIE20 (
  .clka(clk),
  .clkb(clk),
  .wea(CM_L1PHIE20_dataarray_data_V_wea),
  .addra(CM_L1PHIE20_dataarray_data_V_writeaddr),
  .dina(CM_L1PHIE20_dataarray_data_V_din),
  .nent_we0(CM_L1PHIE20_nentries_0_V_we),
  .nent_i0(CM_L1PHIE20_nentries_0_V_din),
  .nent_we1(CM_L1PHIE20_nentries_1_V_we),
  .nent_i1(CM_L1PHIE20_nentries_1_V_din),
  .enb(CM_L1PHIE20_dataarray_data_V_enb),
  .addrb(CM_L1PHIE20_dataarray_data_V_readaddr),
  .doutb(CM_L1PHIE20_dataarray_data_V_dout),
  .nent_o0(CM_L1PHIE20_nentries_0_V_dout),
  .nent_o1(CM_L1PHIE20_nentries_1_V_dout),
  .regceb(1'b1)
);


SectorProcessor SectorProcessor_inst (
  .clk(clk),
  .reset(reset),
  .en_proc(en_proc),
  .bx_in_MatchEngine(bx_in_MatchEngine),
  .VMSME_L1PHIE20n1_dataarray_data_V_enb(VMSME_L1PHIE20n1_dataarray_data_V_enb),
  .VMSME_L1PHIE20n1_dataarray_data_V_readaddr(VMSME_L1PHIE20n1_dataarray_data_V_readaddr),
  .VMSME_L1PHIE20n1_dataarray_data_V_dout(VMSME_L1PHIE20n1_dataarray_data_V_dout),
  .VMSME_L1PHIE20n1_nentries_0_0_V_dout(VMSME_L1PHIE20n1_nentries_0_0_V_dout),
  .VMSME_L1PHIE20n1_nentries_0_1_V_dout(VMSME_L1PHIE20n1_nentries_0_1_V_dout),
  .VMSME_L1PHIE20n1_nentries_0_2_V_dout(VMSME_L1PHIE20n1_nentries_0_2_V_dout),
  .VMSME_L1PHIE20n1_nentries_0_3_V_dout(VMSME_L1PHIE20n1_nentries_0_3_V_dout),
  .VMSME_L1PHIE20n1_nentries_0_4_V_dout(VMSME_L1PHIE20n1_nentries_0_4_V_dout),
  .VMSME_L1PHIE20n1_nentries_0_5_V_dout(VMSME_L1PHIE20n1_nentries_0_5_V_dout),
  .VMSME_L1PHIE20n1_nentries_0_6_V_dout(VMSME_L1PHIE20n1_nentries_0_6_V_dout),
  .VMSME_L1PHIE20n1_nentries_0_7_V_dout(VMSME_L1PHIE20n1_nentries_0_7_V_dout),
  .VMSME_L1PHIE20n1_nentries_1_0_V_dout(VMSME_L1PHIE20n1_nentries_1_0_V_dout),
  .VMSME_L1PHIE20n1_nentries_1_1_V_dout(VMSME_L1PHIE20n1_nentries_1_1_V_dout),
  .VMSME_L1PHIE20n1_nentries_1_2_V_dout(VMSME_L1PHIE20n1_nentries_1_2_V_dout),
  .VMSME_L1PHIE20n1_nentries_1_3_V_dout(VMSME_L1PHIE20n1_nentries_1_3_V_dout),
  .VMSME_L1PHIE20n1_nentries_1_4_V_dout(VMSME_L1PHIE20n1_nentries_1_4_V_dout),
  .VMSME_L1PHIE20n1_nentries_1_5_V_dout(VMSME_L1PHIE20n1_nentries_1_5_V_dout),
  .VMSME_L1PHIE20n1_nentries_1_6_V_dout(VMSME_L1PHIE20n1_nentries_1_6_V_dout),
  .VMSME_L1PHIE20n1_nentries_1_7_V_dout(VMSME_L1PHIE20n1_nentries_1_7_V_dout),
  .VMSME_L1PHIE20n1_nentries_2_0_V_dout(VMSME_L1PHIE20n1_nentries_2_0_V_dout),
  .VMSME_L1PHIE20n1_nentries_2_1_V_dout(VMSME_L1PHIE20n1_nentries_2_1_V_dout),
  .VMSME_L1PHIE20n1_nentries_2_2_V_dout(VMSME_L1PHIE20n1_nentries_2_2_V_dout),
  .VMSME_L1PHIE20n1_nentries_2_3_V_dout(VMSME_L1PHIE20n1_nentries_2_3_V_dout),
  .VMSME_L1PHIE20n1_nentries_2_4_V_dout(VMSME_L1PHIE20n1_nentries_2_4_V_dout),
  .VMSME_L1PHIE20n1_nentries_2_5_V_dout(VMSME_L1PHIE20n1_nentries_2_5_V_dout),
  .VMSME_L1PHIE20n1_nentries_2_6_V_dout(VMSME_L1PHIE20n1_nentries_2_6_V_dout),
  .VMSME_L1PHIE20n1_nentries_2_7_V_dout(VMSME_L1PHIE20n1_nentries_2_7_V_dout),
  .VMSME_L1PHIE20n1_nentries_3_0_V_dout(VMSME_L1PHIE20n1_nentries_3_0_V_dout),
  .VMSME_L1PHIE20n1_nentries_3_1_V_dout(VMSME_L1PHIE20n1_nentries_3_1_V_dout),
  .VMSME_L1PHIE20n1_nentries_3_2_V_dout(VMSME_L1PHIE20n1_nentries_3_2_V_dout),
  .VMSME_L1PHIE20n1_nentries_3_3_V_dout(VMSME_L1PHIE20n1_nentries_3_3_V_dout),
  .VMSME_L1PHIE20n1_nentries_3_4_V_dout(VMSME_L1PHIE20n1_nentries_3_4_V_dout),
  .VMSME_L1PHIE20n1_nentries_3_5_V_dout(VMSME_L1PHIE20n1_nentries_3_5_V_dout),
  .VMSME_L1PHIE20n1_nentries_3_6_V_dout(VMSME_L1PHIE20n1_nentries_3_6_V_dout),
  .VMSME_L1PHIE20n1_nentries_3_7_V_dout(VMSME_L1PHIE20n1_nentries_3_7_V_dout),				      
  .VMPROJ_L1PHIE20_dataarray_data_V_enb(VMPROJ_L1PHIE20_dataarray_data_V_enb),
  .VMPROJ_L1PHIE20_dataarray_data_V_readaddr(VMPROJ_L1PHIE20_dataarray_data_V_readaddr),
  .VMPROJ_L1PHIE20_dataarray_data_V_dout(VMPROJ_L1PHIE20_dataarray_data_V_dout),
  .VMPROJ_L1PHIE20_nentries_0_V_dout(VMPROJ_L1PHIE20_nentries_0_V_dout),
  .VMPROJ_L1PHIE20_nentries_1_V_dout(VMPROJ_L1PHIE20_nentries_1_V_dout),
  .bx_out_MatchEngine(bx_out_MatchEngine),
  .CM_L1PHIE20_dataarray_data_V_wea(CM_L1PHIE20_dataarray_data_V_wea),
  .CM_L1PHIE20_dataarray_data_V_writeaddr(CM_L1PHIE20_dataarray_data_V_writeaddr),
  .CM_L1PHIE20_dataarray_data_V_din(CM_L1PHIE20_dataarray_data_V_din),
  .CM_L1PHIE20_nentries_0_V_we(CM_L1PHIE20_nentries_0_V_we),
  .CM_L1PHIE20_nentries_0_V_din(CM_L1PHIE20_nentries_0_V_din),
  .CM_L1PHIE20_nentries_1_V_we(CM_L1PHIE20_nentries_1_V_we),
  .CM_L1PHIE20_nentries_1_V_din(CM_L1PHIE20_nentries_1_V_din)
);

endmodule
