# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcvu7p-flvb2104-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /mnt/scratch/rz393/firmware-hls/IntegrationTests/ME_Test_1/ME_Test/ME_Test/ME_Test.cache/wt [current_project]
set_property parent.project_path /mnt/scratch/rz393/firmware-hls/IntegrationTests/ME_Test_1/ME_Test/ME_Test/ME_Test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /mnt/scratch/rz393/firmware-hls/IntegrationTests/ME_Test_1/sourceFiles [current_project]
set_property ip_output_repo /mnt/scratch/rz393/firmware-hls/IntegrationTests/ME_Test_1/ME_Test/ME_Test/ME_Test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  /mnt/scratch/rz393/firmware-hls/IntegrationTests/ME_Test_1/emData/VMProjections_VMPROJ_L1PHIE20_04.dat
  /mnt/scratch/rz393/firmware-hls/IntegrationTests/ME_Test_1/emData/VMStubs_VMSME_L1PHIE20n1_04.dat
}
read_verilog -library xil_defaultlib {
  /mnt/scratch/rz393/firmware-hls/IntegrationTests/ME_Test_1/sourceFiles/MemoreBinned_ME_Test.v
  /mnt/scratch/rz393/firmware-hls/IntegrationTests/ME_Test_1/sourceFiles/Memore_ME_Test.v
  /mnt/scratch/rz393/firmware-hls/IntegrationTests/ME_Test_1/sourceFiles/SectorProcessor.v
  /mnt/scratch/rz393/firmware-hls/IntegrationTests/ME_Test_1/sourceFiles/SectorProcessor_test.v
}
read_ip -quiet /mnt/scratch/rz393/firmware-hls/IntegrationTests/ME_Test_1/ME_Test/ME_Test/ME_Test.srcs/sources_1/ip/MatchEngineTopL1_0_1/MatchEngineTopL1_0.xci
set_property used_in_implementation false [get_files -all /mnt/scratch/rz393/firmware-hls/IntegrationTests/ME_Test_1/ME_Test/ME_Test/ME_Test.srcs/sources_1/ip/MatchEngineTopL1_0_1/constraints/MatchEngineTopL1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top SectorProcessor_test -part xcvu7p-flvb2104-2-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SectorProcessor_test.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file SectorProcessor_test_utilization_synth.rpt -pb SectorProcessor_test_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
