set_property SRC_FILE_INFO {cfile:/mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRMEMC_Test/PRMEMC_Test/PRMEMC_Test.srcs/sources_1/ip/MC_L3PHIC/MC_L3PHIC/MC_L3PHIC_in_context.xdc rfile:../../../../../PRMEMC_Test.srcs/sources_1/ip/MC_L3PHIC/MC_L3PHIC/MC_L3PHIC_in_context.xdc id:1 order:EARLY scoped_inst:MC_L3PHIC} [current_design]
set_property SRC_FILE_INFO {cfile:/mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRMEMC_Test/PRMEMC_Test/PRMEMC_Test.srcs/sources_1/ip/MatchEngineTopL3_0/MatchEngineTopL3_0/MatchEngineTopL3_0_in_context.xdc rfile:../../../../../PRMEMC_Test.srcs/sources_1/ip/MatchEngineTopL3_0/MatchEngineTopL3_0/MatchEngineTopL3_0_in_context.xdc id:2 order:EARLY scoped_inst:{gen_MatchEngineTopL3[0].MatchEngineTopL3_0}} [current_design]
set_property SRC_FILE_INFO {cfile:/mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRMEMC_Test/PRMEMC_Test/PRMEMC_Test.srcs/sources_1/ip/MatchEngineTopL3_0/MatchEngineTopL3_0/MatchEngineTopL3_0_in_context.xdc rfile:../../../../../PRMEMC_Test.srcs/sources_1/ip/MatchEngineTopL3_0/MatchEngineTopL3_0/MatchEngineTopL3_0_in_context.xdc id:3 order:EARLY scoped_inst:{gen_MatchEngineTopL3[1].MatchEngineTopL3_0}} [current_design]
set_property SRC_FILE_INFO {cfile:/mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRMEMC_Test/PRMEMC_Test/PRMEMC_Test.srcs/sources_1/ip/MatchEngineTopL3_0/MatchEngineTopL3_0/MatchEngineTopL3_0_in_context.xdc rfile:../../../../../PRMEMC_Test.srcs/sources_1/ip/MatchEngineTopL3_0/MatchEngineTopL3_0/MatchEngineTopL3_0_in_context.xdc id:4 order:EARLY scoped_inst:{gen_MatchEngineTopL3[2].MatchEngineTopL3_0}} [current_design]
set_property SRC_FILE_INFO {cfile:/mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRMEMC_Test/PRMEMC_Test/PRMEMC_Test.srcs/sources_1/ip/MatchEngineTopL3_0/MatchEngineTopL3_0/MatchEngineTopL3_0_in_context.xdc rfile:../../../../../PRMEMC_Test.srcs/sources_1/ip/MatchEngineTopL3_0/MatchEngineTopL3_0/MatchEngineTopL3_0_in_context.xdc id:5 order:EARLY scoped_inst:{gen_MatchEngineTopL3[3].MatchEngineTopL3_0}} [current_design]
set_property SRC_FILE_INFO {cfile:/mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRMEMC_Test/PRMEMC_Test/PRMEMC_Test.srcs/sources_1/ip/MatchEngineTopL3_0/MatchEngineTopL3_0/MatchEngineTopL3_0_in_context.xdc rfile:../../../../../PRMEMC_Test.srcs/sources_1/ip/MatchEngineTopL3_0/MatchEngineTopL3_0/MatchEngineTopL3_0_in_context.xdc id:6 order:EARLY scoped_inst:{gen_MatchEngineTopL3[4].MatchEngineTopL3_0}} [current_design]
set_property SRC_FILE_INFO {cfile:/mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRMEMC_Test/PRMEMC_Test/PRMEMC_Test.srcs/sources_1/ip/MatchEngineTopL3_0/MatchEngineTopL3_0/MatchEngineTopL3_0_in_context.xdc rfile:../../../../../PRMEMC_Test.srcs/sources_1/ip/MatchEngineTopL3_0/MatchEngineTopL3_0/MatchEngineTopL3_0_in_context.xdc id:7 order:EARLY scoped_inst:{gen_MatchEngineTopL3[5].MatchEngineTopL3_0}} [current_design]
set_property SRC_FILE_INFO {cfile:/mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRMEMC_Test/PRMEMC_Test/PRMEMC_Test.srcs/sources_1/ip/MatchEngineTopL3_0/MatchEngineTopL3_0/MatchEngineTopL3_0_in_context.xdc rfile:../../../../../PRMEMC_Test.srcs/sources_1/ip/MatchEngineTopL3_0/MatchEngineTopL3_0/MatchEngineTopL3_0_in_context.xdc id:8 order:EARLY scoped_inst:{gen_MatchEngineTopL3[6].MatchEngineTopL3_0}} [current_design]
set_property SRC_FILE_INFO {cfile:/mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRMEMC_Test/PRMEMC_Test/PRMEMC_Test.srcs/sources_1/ip/MatchEngineTopL3_0/MatchEngineTopL3_0/MatchEngineTopL3_0_in_context.xdc rfile:../../../../../PRMEMC_Test.srcs/sources_1/ip/MatchEngineTopL3_0/MatchEngineTopL3_0/MatchEngineTopL3_0_in_context.xdc id:9 order:EARLY scoped_inst:{gen_MatchEngineTopL3[7].MatchEngineTopL3_0}} [current_design]
set_property SRC_FILE_INFO {cfile:/mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRMEMC_Test/PRMEMC_Test/PRMEMC_Test.srcs/sources_1/ip/PR_L3PHIC_1/PR_L3PHIC/PR_L3PHIC_in_context.xdc rfile:../../../../../PRMEMC_Test.srcs/sources_1/ip/PR_L3PHIC_1/PR_L3PHIC/PR_L3PHIC_in_context.xdc id:10 order:EARLY scoped_inst:PR_L3PHIC} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins MC_L3PHIC/ap_clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells MC_L3PHIC]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins {gen_MatchEngineTopL3[0].MatchEngineTopL3_0/ap_clk}]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {gen_MatchEngineTopL3[0].MatchEngineTopL3_0}]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins {gen_MatchEngineTopL3[1].MatchEngineTopL3_0/ap_clk}]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {gen_MatchEngineTopL3[1].MatchEngineTopL3_0}]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins {gen_MatchEngineTopL3[2].MatchEngineTopL3_0/ap_clk}]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {gen_MatchEngineTopL3[2].MatchEngineTopL3_0}]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins {gen_MatchEngineTopL3[3].MatchEngineTopL3_0/ap_clk}]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {gen_MatchEngineTopL3[3].MatchEngineTopL3_0}]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins {gen_MatchEngineTopL3[4].MatchEngineTopL3_0/ap_clk}]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {gen_MatchEngineTopL3[4].MatchEngineTopL3_0}]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins {gen_MatchEngineTopL3[5].MatchEngineTopL3_0/ap_clk}]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {gen_MatchEngineTopL3[5].MatchEngineTopL3_0}]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins {gen_MatchEngineTopL3[6].MatchEngineTopL3_0/ap_clk}]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {gen_MatchEngineTopL3[6].MatchEngineTopL3_0}]
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins {gen_MatchEngineTopL3[7].MatchEngineTopL3_0/ap_clk}]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {gen_MatchEngineTopL3[7].MatchEngineTopL3_0}]
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins PR_L3PHIC/ap_clk]
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells PR_L3PHIC]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells MC_L3PHIC]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {gen_MatchEngineTopL3[0].MatchEngineTopL3_0}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {gen_MatchEngineTopL3[1].MatchEngineTopL3_0}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {gen_MatchEngineTopL3[2].MatchEngineTopL3_0}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {gen_MatchEngineTopL3[3].MatchEngineTopL3_0}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {gen_MatchEngineTopL3[4].MatchEngineTopL3_0}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {gen_MatchEngineTopL3[5].MatchEngineTopL3_0}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {gen_MatchEngineTopL3[6].MatchEngineTopL3_0}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {gen_MatchEngineTopL3[7].MatchEngineTopL3_0}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells PR_L3PHIC]
