// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ProjectionRouterTop,hls_ip_2019_1_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu7p-flvb2104-1-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.445000,HLS_SYN_LAT=108,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=625,HLS_SYN_LUT=2433,HLS_VERSION=2019_1_2}" *)

module ProjectionRouterTop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bx_V,
        proj1in_dataarray_data_V_address0,
        proj1in_dataarray_data_V_ce0,
        proj1in_dataarray_data_V_q0,
        proj1in_nentries_V_address0,
        proj1in_nentries_V_ce0,
        proj1in_nentries_V_q0,
        proj2in_dataarray_data_V_address0,
        proj2in_dataarray_data_V_ce0,
        proj2in_dataarray_data_V_q0,
        proj2in_nentries_V_address0,
        proj2in_nentries_V_ce0,
        proj2in_nentries_V_q0,
        proj3in_dataarray_data_V_address0,
        proj3in_dataarray_data_V_ce0,
        proj3in_dataarray_data_V_q0,
        proj3in_nentries_V_address0,
        proj3in_nentries_V_ce0,
        proj3in_nentries_V_q0,
        proj4in_dataarray_data_V_address0,
        proj4in_dataarray_data_V_ce0,
        proj4in_dataarray_data_V_q0,
        proj4in_nentries_V_address0,
        proj4in_nentries_V_ce0,
        proj4in_nentries_V_q0,
        proj5in_dataarray_data_V_address0,
        proj5in_dataarray_data_V_ce0,
        proj5in_dataarray_data_V_q0,
        proj5in_nentries_V_address0,
        proj5in_nentries_V_ce0,
        proj5in_nentries_V_q0,
        proj6in_dataarray_data_V_address0,
        proj6in_dataarray_data_V_ce0,
        proj6in_dataarray_data_V_q0,
        proj6in_nentries_V_address0,
        proj6in_nentries_V_ce0,
        proj6in_nentries_V_q0,
        proj7in_dataarray_data_V_address0,
        proj7in_dataarray_data_V_ce0,
        proj7in_dataarray_data_V_q0,
        proj7in_nentries_V_address0,
        proj7in_nentries_V_ce0,
        proj7in_nentries_V_q0,
        proj8in_dataarray_data_V_address0,
        proj8in_dataarray_data_V_ce0,
        proj8in_dataarray_data_V_q0,
        proj8in_nentries_V_address0,
        proj8in_nentries_V_ce0,
        proj8in_nentries_V_q0,
        bx_o_V,
        bx_o_V_ap_vld,
        allprojout_dataarray_data_V_address0,
        allprojout_dataarray_data_V_ce0,
        allprojout_dataarray_data_V_we0,
        allprojout_dataarray_data_V_d0,
        allprojout_nentries_0_V,
        allprojout_nentries_0_V_ap_vld,
        allprojout_nentries_1_V,
        allprojout_nentries_1_V_ap_vld,
        allprojout_nentries_2_V,
        allprojout_nentries_2_V_ap_vld,
        allprojout_nentries_3_V,
        allprojout_nentries_3_V_ap_vld,
        allprojout_nentries_4_V,
        allprojout_nentries_4_V_ap_vld,
        allprojout_nentries_5_V,
        allprojout_nentries_5_V_ap_vld,
        allprojout_nentries_6_V,
        allprojout_nentries_6_V_ap_vld,
        allprojout_nentries_7_V,
        allprojout_nentries_7_V_ap_vld,
        vmprojout1_dataarray_data_V_address0,
        vmprojout1_dataarray_data_V_ce0,
        vmprojout1_dataarray_data_V_we0,
        vmprojout1_dataarray_data_V_d0,
        vmprojout1_nentries_0_V,
        vmprojout1_nentries_0_V_ap_vld,
        vmprojout1_nentries_1_V,
        vmprojout1_nentries_1_V_ap_vld,
        vmprojout2_dataarray_data_V_address0,
        vmprojout2_dataarray_data_V_ce0,
        vmprojout2_dataarray_data_V_we0,
        vmprojout2_dataarray_data_V_d0,
        vmprojout2_nentries_0_V,
        vmprojout2_nentries_0_V_ap_vld,
        vmprojout2_nentries_1_V,
        vmprojout2_nentries_1_V_ap_vld,
        vmprojout3_dataarray_data_V_address0,
        vmprojout3_dataarray_data_V_ce0,
        vmprojout3_dataarray_data_V_we0,
        vmprojout3_dataarray_data_V_d0,
        vmprojout3_nentries_0_V,
        vmprojout3_nentries_0_V_ap_vld,
        vmprojout3_nentries_1_V,
        vmprojout3_nentries_1_V_ap_vld,
        vmprojout4_dataarray_data_V_address0,
        vmprojout4_dataarray_data_V_ce0,
        vmprojout4_dataarray_data_V_we0,
        vmprojout4_dataarray_data_V_d0,
        vmprojout4_nentries_0_V,
        vmprojout4_nentries_0_V_ap_vld,
        vmprojout4_nentries_1_V,
        vmprojout4_nentries_1_V_ap_vld,
        vmprojout5_dataarray_data_V_address0,
        vmprojout5_dataarray_data_V_ce0,
        vmprojout5_dataarray_data_V_we0,
        vmprojout5_dataarray_data_V_d0,
        vmprojout5_nentries_0_V,
        vmprojout5_nentries_0_V_ap_vld,
        vmprojout5_nentries_1_V,
        vmprojout5_nentries_1_V_ap_vld,
        vmprojout6_dataarray_data_V_address0,
        vmprojout6_dataarray_data_V_ce0,
        vmprojout6_dataarray_data_V_we0,
        vmprojout6_dataarray_data_V_d0,
        vmprojout6_nentries_0_V,
        vmprojout6_nentries_0_V_ap_vld,
        vmprojout6_nentries_1_V,
        vmprojout6_nentries_1_V_ap_vld,
        vmprojout7_dataarray_data_V_address0,
        vmprojout7_dataarray_data_V_ce0,
        vmprojout7_dataarray_data_V_we0,
        vmprojout7_dataarray_data_V_d0,
        vmprojout7_nentries_0_V,
        vmprojout7_nentries_0_V_ap_vld,
        vmprojout7_nentries_1_V,
        vmprojout7_nentries_1_V_ap_vld,
        vmprojout8_dataarray_data_V_address0,
        vmprojout8_dataarray_data_V_ce0,
        vmprojout8_dataarray_data_V_we0,
        vmprojout8_dataarray_data_V_d0,
        vmprojout8_nentries_0_V,
        vmprojout8_nentries_0_V_ap_vld,
        vmprojout8_nentries_1_V,
        vmprojout8_nentries_1_V_ap_vld
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_pp0_stage0 = 6'd16;
parameter    ap_ST_fsm_state9 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [2:0] bx_V;
output  [7:0] proj1in_dataarray_data_V_address0;
output   proj1in_dataarray_data_V_ce0;
input  [59:0] proj1in_dataarray_data_V_q0;
output  [0:0] proj1in_nentries_V_address0;
output   proj1in_nentries_V_ce0;
input  [7:0] proj1in_nentries_V_q0;
output  [7:0] proj2in_dataarray_data_V_address0;
output   proj2in_dataarray_data_V_ce0;
input  [59:0] proj2in_dataarray_data_V_q0;
output  [0:0] proj2in_nentries_V_address0;
output   proj2in_nentries_V_ce0;
input  [7:0] proj2in_nentries_V_q0;
output  [7:0] proj3in_dataarray_data_V_address0;
output   proj3in_dataarray_data_V_ce0;
input  [59:0] proj3in_dataarray_data_V_q0;
output  [0:0] proj3in_nentries_V_address0;
output   proj3in_nentries_V_ce0;
input  [7:0] proj3in_nentries_V_q0;
output  [7:0] proj4in_dataarray_data_V_address0;
output   proj4in_dataarray_data_V_ce0;
input  [59:0] proj4in_dataarray_data_V_q0;
output  [0:0] proj4in_nentries_V_address0;
output   proj4in_nentries_V_ce0;
input  [7:0] proj4in_nentries_V_q0;
output  [7:0] proj5in_dataarray_data_V_address0;
output   proj5in_dataarray_data_V_ce0;
input  [59:0] proj5in_dataarray_data_V_q0;
output  [0:0] proj5in_nentries_V_address0;
output   proj5in_nentries_V_ce0;
input  [7:0] proj5in_nentries_V_q0;
output  [7:0] proj6in_dataarray_data_V_address0;
output   proj6in_dataarray_data_V_ce0;
input  [59:0] proj6in_dataarray_data_V_q0;
output  [0:0] proj6in_nentries_V_address0;
output   proj6in_nentries_V_ce0;
input  [7:0] proj6in_nentries_V_q0;
output  [7:0] proj7in_dataarray_data_V_address0;
output   proj7in_dataarray_data_V_ce0;
input  [59:0] proj7in_dataarray_data_V_q0;
output  [0:0] proj7in_nentries_V_address0;
output   proj7in_nentries_V_ce0;
input  [7:0] proj7in_nentries_V_q0;
output  [7:0] proj8in_dataarray_data_V_address0;
output   proj8in_dataarray_data_V_ce0;
input  [59:0] proj8in_dataarray_data_V_q0;
output  [0:0] proj8in_nentries_V_address0;
output   proj8in_nentries_V_ce0;
input  [7:0] proj8in_nentries_V_q0;
output  [2:0] bx_o_V;
output   bx_o_V_ap_vld;
output  [9:0] allprojout_dataarray_data_V_address0;
output   allprojout_dataarray_data_V_ce0;
output   allprojout_dataarray_data_V_we0;
output  [59:0] allprojout_dataarray_data_V_d0;
output  [7:0] allprojout_nentries_0_V;
output   allprojout_nentries_0_V_ap_vld;
output  [7:0] allprojout_nentries_1_V;
output   allprojout_nentries_1_V_ap_vld;
output  [7:0] allprojout_nentries_2_V;
output   allprojout_nentries_2_V_ap_vld;
output  [7:0] allprojout_nentries_3_V;
output   allprojout_nentries_3_V_ap_vld;
output  [7:0] allprojout_nentries_4_V;
output   allprojout_nentries_4_V_ap_vld;
output  [7:0] allprojout_nentries_5_V;
output   allprojout_nentries_5_V_ap_vld;
output  [7:0] allprojout_nentries_6_V;
output   allprojout_nentries_6_V_ap_vld;
output  [7:0] allprojout_nentries_7_V;
output   allprojout_nentries_7_V_ap_vld;
output  [7:0] vmprojout1_dataarray_data_V_address0;
output   vmprojout1_dataarray_data_V_ce0;
output   vmprojout1_dataarray_data_V_we0;
output  [20:0] vmprojout1_dataarray_data_V_d0;
output  [7:0] vmprojout1_nentries_0_V;
output   vmprojout1_nentries_0_V_ap_vld;
output  [7:0] vmprojout1_nentries_1_V;
output   vmprojout1_nentries_1_V_ap_vld;
output  [7:0] vmprojout2_dataarray_data_V_address0;
output   vmprojout2_dataarray_data_V_ce0;
output   vmprojout2_dataarray_data_V_we0;
output  [20:0] vmprojout2_dataarray_data_V_d0;
output  [7:0] vmprojout2_nentries_0_V;
output   vmprojout2_nentries_0_V_ap_vld;
output  [7:0] vmprojout2_nentries_1_V;
output   vmprojout2_nentries_1_V_ap_vld;
output  [7:0] vmprojout3_dataarray_data_V_address0;
output   vmprojout3_dataarray_data_V_ce0;
output   vmprojout3_dataarray_data_V_we0;
output  [20:0] vmprojout3_dataarray_data_V_d0;
output  [7:0] vmprojout3_nentries_0_V;
output   vmprojout3_nentries_0_V_ap_vld;
output  [7:0] vmprojout3_nentries_1_V;
output   vmprojout3_nentries_1_V_ap_vld;
output  [7:0] vmprojout4_dataarray_data_V_address0;
output   vmprojout4_dataarray_data_V_ce0;
output   vmprojout4_dataarray_data_V_we0;
output  [20:0] vmprojout4_dataarray_data_V_d0;
output  [7:0] vmprojout4_nentries_0_V;
output   vmprojout4_nentries_0_V_ap_vld;
output  [7:0] vmprojout4_nentries_1_V;
output   vmprojout4_nentries_1_V_ap_vld;
output  [7:0] vmprojout5_dataarray_data_V_address0;
output   vmprojout5_dataarray_data_V_ce0;
output   vmprojout5_dataarray_data_V_we0;
output  [20:0] vmprojout5_dataarray_data_V_d0;
output  [7:0] vmprojout5_nentries_0_V;
output   vmprojout5_nentries_0_V_ap_vld;
output  [7:0] vmprojout5_nentries_1_V;
output   vmprojout5_nentries_1_V_ap_vld;
output  [7:0] vmprojout6_dataarray_data_V_address0;
output   vmprojout6_dataarray_data_V_ce0;
output   vmprojout6_dataarray_data_V_we0;
output  [20:0] vmprojout6_dataarray_data_V_d0;
output  [7:0] vmprojout6_nentries_0_V;
output   vmprojout6_nentries_0_V_ap_vld;
output  [7:0] vmprojout6_nentries_1_V;
output   vmprojout6_nentries_1_V_ap_vld;
output  [7:0] vmprojout7_dataarray_data_V_address0;
output   vmprojout7_dataarray_data_V_ce0;
output   vmprojout7_dataarray_data_V_we0;
output  [20:0] vmprojout7_dataarray_data_V_d0;
output  [7:0] vmprojout7_nentries_0_V;
output   vmprojout7_nentries_0_V_ap_vld;
output  [7:0] vmprojout7_nentries_1_V;
output   vmprojout7_nentries_1_V_ap_vld;
output  [7:0] vmprojout8_dataarray_data_V_address0;
output   vmprojout8_dataarray_data_V_ce0;
output   vmprojout8_dataarray_data_V_we0;
output  [20:0] vmprojout8_dataarray_data_V_d0;
output  [7:0] vmprojout8_nentries_0_V;
output   vmprojout8_nentries_0_V_ap_vld;
output  [7:0] vmprojout8_nentries_1_V;
output   vmprojout8_nentries_1_V_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg proj1in_dataarray_data_V_ce0;
reg proj1in_nentries_V_ce0;
reg proj2in_dataarray_data_V_ce0;
reg proj2in_nentries_V_ce0;
reg proj3in_dataarray_data_V_ce0;
reg proj3in_nentries_V_ce0;
reg proj4in_dataarray_data_V_ce0;
reg proj4in_nentries_V_ce0;
reg proj5in_dataarray_data_V_ce0;
reg proj5in_nentries_V_ce0;
reg proj6in_dataarray_data_V_ce0;
reg proj6in_nentries_V_ce0;
reg proj7in_dataarray_data_V_ce0;
reg proj7in_nentries_V_ce0;
reg proj8in_dataarray_data_V_ce0;
reg proj8in_nentries_V_ce0;
reg allprojout_dataarray_data_V_ce0;
reg allprojout_dataarray_data_V_we0;
reg[7:0] allprojout_nentries_0_V;
reg allprojout_nentries_0_V_ap_vld;
reg[7:0] allprojout_nentries_1_V;
reg allprojout_nentries_1_V_ap_vld;
reg[7:0] allprojout_nentries_2_V;
reg allprojout_nentries_2_V_ap_vld;
reg[7:0] allprojout_nentries_3_V;
reg allprojout_nentries_3_V_ap_vld;
reg[7:0] allprojout_nentries_4_V;
reg allprojout_nentries_4_V_ap_vld;
reg[7:0] allprojout_nentries_5_V;
reg allprojout_nentries_5_V_ap_vld;
reg[7:0] allprojout_nentries_6_V;
reg allprojout_nentries_6_V_ap_vld;
reg[7:0] allprojout_nentries_7_V;
reg allprojout_nentries_7_V_ap_vld;
reg vmprojout1_dataarray_data_V_ce0;
reg vmprojout1_dataarray_data_V_we0;
reg[7:0] vmprojout1_nentries_0_V;
reg vmprojout1_nentries_0_V_ap_vld;
reg[7:0] vmprojout1_nentries_1_V;
reg vmprojout1_nentries_1_V_ap_vld;
reg vmprojout2_dataarray_data_V_ce0;
reg vmprojout2_dataarray_data_V_we0;
reg[7:0] vmprojout2_nentries_0_V;
reg vmprojout2_nentries_0_V_ap_vld;
reg[7:0] vmprojout2_nentries_1_V;
reg vmprojout2_nentries_1_V_ap_vld;
reg vmprojout3_dataarray_data_V_ce0;
reg vmprojout3_dataarray_data_V_we0;
reg[7:0] vmprojout3_nentries_0_V;
reg vmprojout3_nentries_0_V_ap_vld;
reg[7:0] vmprojout3_nentries_1_V;
reg vmprojout3_nentries_1_V_ap_vld;
reg vmprojout4_dataarray_data_V_ce0;
reg vmprojout4_dataarray_data_V_we0;
reg[7:0] vmprojout4_nentries_0_V;
reg vmprojout4_nentries_0_V_ap_vld;
reg[7:0] vmprojout4_nentries_1_V;
reg vmprojout4_nentries_1_V_ap_vld;
reg vmprojout5_dataarray_data_V_ce0;
reg vmprojout5_dataarray_data_V_we0;
reg[7:0] vmprojout5_nentries_0_V;
reg vmprojout5_nentries_0_V_ap_vld;
reg[7:0] vmprojout5_nentries_1_V;
reg vmprojout5_nentries_1_V_ap_vld;
reg vmprojout6_dataarray_data_V_ce0;
reg vmprojout6_dataarray_data_V_we0;
reg[7:0] vmprojout6_nentries_0_V;
reg vmprojout6_nentries_0_V_ap_vld;
reg[7:0] vmprojout6_nentries_1_V;
reg vmprojout6_nentries_1_V_ap_vld;
reg vmprojout7_dataarray_data_V_ce0;
reg vmprojout7_dataarray_data_V_we0;
reg[7:0] vmprojout7_nentries_0_V;
reg vmprojout7_nentries_0_V_ap_vld;
reg[7:0] vmprojout7_nentries_1_V;
reg vmprojout7_nentries_1_V_ap_vld;
reg vmprojout8_dataarray_data_V_ce0;
reg vmprojout8_dataarray_data_V_we0;
reg[7:0] vmprojout8_nentries_0_V;
reg vmprojout8_nentries_0_V_ap_vld;
reg[7:0] vmprojout8_nentries_1_V;
reg vmprojout8_nentries_1_V_ap_vld;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [2:0] bx_o_V_1_data_reg;
reg    bx_o_V_1_vld_reg;
reg    bx_o_V_1_vld_in;
reg   [6:0] p_Repl2_1_reg_848;
reg   [6:0] p_Repl2_1_reg_848_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_state7_pp0_stage0_iter2;
wire    ap_block_state8_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
reg   [6:0] p_Repl2_1_reg_848_pp0_iter2_reg;
wire   [2:0] bx_V_read_read_fu_318_p2;
wire   [11:0] zext_ln321_fu_868_p1;
reg   [11:0] zext_ln321_reg_2080;
wire   [0:0] trunc_ln209_fu_872_p1;
reg   [0:0] trunc_ln209_reg_2085;
wire   [9:0] zext_ln321_1_fu_896_p1;
reg   [9:0] zext_ln321_1_reg_2090;
reg   [7:0] num_V_reg_2228;
wire    ap_CS_fsm_state3;
wire   [0:0] p_Val2_s_fu_950_p2;
reg   [0:0] p_Val2_s_reg_2233;
reg   [7:0] num_V_1_reg_2239;
wire   [0:0] icmp_ln895_fu_956_p2;
reg   [0:0] icmp_ln895_reg_2244;
reg   [7:0] num_V_2_reg_2249;
wire   [0:0] icmp_ln895_1_fu_962_p2;
reg   [0:0] icmp_ln895_1_reg_2254;
reg   [7:0] num_V_3_reg_2259;
reg   [7:0] num_V_4_reg_2265;
reg   [7:0] num_V_5_reg_2271;
reg   [7:0] num_V_6_reg_2277;
reg   [7:0] num_V_7_reg_2283;
wire   [0:0] icmp_ln227_fu_1128_p2;
reg   [0:0] icmp_ln227_reg_2289;
wire   [6:0] i_fu_1134_p2;
reg   [6:0] i_reg_2293;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] icmp_ln879_fu_1143_p2;
reg   [0:0] icmp_ln879_reg_2298;
reg   [0:0] icmp_ln879_reg_2298_pp0_iter1_reg;
reg   [0:0] icmp_ln879_reg_2298_pp0_iter2_reg;
wire   [4:0] read_imem_V_fu_1164_p1;
reg   [4:0] read_imem_V_reg_2302;
reg   [4:0] read_imem_V_reg_2302_pp0_iter1_reg;
wire   [0:0] icmp_ln367_fu_1261_p2;
reg   [2:0] iphi_V_reg_2358;
wire   [12:0] zext_ln1354_fu_1396_p1;
reg   [12:0] zext_ln1354_reg_2362;
wire   [12:0] ret_V_fu_1400_p2;
reg   [12:0] ret_V_reg_2367;
reg   [3:0] trunc_ln3_reg_2372;
reg   [3:0] trunc_ln1503_2_reg_2377;
reg   [4:0] trunc_ln1503_3_reg_2382;
wire   [0:0] psseed_fu_1482_p2;
reg   [0:0] psseed_reg_2387;
wire   [0:0] icmp_ln70_8_fu_1491_p2;
wire    ap_CS_fsm_state4;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state5;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg   [6:0] ap_phi_mux_p_Repl2_1_phi_fu_852_p4;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln544_fu_876_p1;
wire   [63:0] zext_ln63_fu_1175_p1;
wire  signed [63:0] sext_ln321_8_fu_1506_p1;
wire  signed [63:0] sext_ln321_7_fu_1701_p1;
wire   [0:0] icmp_ln70_7_fu_1686_p2;
wire  signed [63:0] sext_ln321_6_fu_1750_p1;
wire   [0:0] icmp_ln70_6_fu_1735_p2;
wire  signed [63:0] sext_ln321_5_fu_1799_p1;
wire   [0:0] icmp_ln70_5_fu_1784_p2;
wire  signed [63:0] sext_ln321_4_fu_1848_p1;
wire   [0:0] icmp_ln70_4_fu_1833_p2;
wire  signed [63:0] sext_ln321_3_fu_1897_p1;
wire   [0:0] icmp_ln70_3_fu_1882_p2;
wire  signed [63:0] sext_ln321_2_fu_1946_p1;
wire   [0:0] icmp_ln70_2_fu_1931_p2;
wire  signed [63:0] sext_ln321_1_fu_1995_p1;
wire   [0:0] icmp_ln70_1_fu_1980_p2;
wire  signed [63:0] sext_ln321_fu_2044_p1;
wire   [0:0] icmp_ln70_fu_2029_p2;
reg   [31:0] addr_index_assign_7_fu_274;
wire   [31:0] nvmprojout8_fu_1721_p2;
reg   [31:0] addr_index_assign_6_fu_278;
wire   [31:0] nvmprojout7_fu_1770_p2;
reg   [31:0] addr_index_assign_5_fu_282;
wire   [31:0] nvmprojout6_fu_1819_p2;
reg   [31:0] addr_index_assign_4_fu_286;
wire   [31:0] nvmprojout5_fu_1868_p2;
reg   [31:0] addr_index_assign_3_fu_290;
wire   [31:0] nvmprojout4_fu_1917_p2;
reg   [31:0] addr_index_assign_2_fu_294;
wire   [31:0] nvmprojout3_fu_1966_p2;
reg   [31:0] addr_index_assign_1_fu_298;
wire   [31:0] nvmprojout2_fu_2015_p2;
reg   [31:0] addr_index_assign_fu_302;
wire   [31:0] nvmprojout1_fu_2064_p2;
reg   [31:0] addr_index_assign_8_fu_306;
wire   [31:0] nallproj_fu_1532_p2;
reg   [7:0] p_Val2_7_fu_310;
wire   [7:0] select_ln895_fu_1115_p3;
wire   [7:0] mem_hasdata_V_7_fu_1243_p3;
reg   [6:0] read_addr_V_read_ass_fu_314;
wire   [6:0] select_ln891_fu_1235_p3;
wire   [7:0] add_ln301_8_fu_1515_p2;
wire    ap_block_pp0_stage0_01001;
wire   [7:0] add_ln301_fu_2053_p2;
wire   [7:0] add_ln301_1_fu_2004_p2;
wire   [7:0] add_ln301_2_fu_1955_p2;
wire   [7:0] add_ln301_3_fu_1906_p2;
wire   [7:0] add_ln301_4_fu_1857_p2;
wire   [7:0] add_ln301_5_fu_1808_p2;
wire   [7:0] add_ln301_6_fu_1759_p2;
wire   [7:0] add_ln301_7_fu_1710_p2;
wire    ap_CS_fsm_state2;
wire   [59:0] p_Val2_15_fu_1363_p3;
wire   [20:0] ret_V_2_fu_1660_p7;
wire   [9:0] tmp_3_fu_860_p3;
wire   [7:0] tmp_5_fu_888_p3;
wire   [1:0] zext_ln39_fu_968_p1;
wire   [1:0] tmp_1_fu_971_p3;
wire   [1:0] p_Val2_9_fu_978_p3;
wire   [2:0] tmp_4_fu_989_p3;
wire   [7:0] zext_ln895_fu_985_p1;
wire   [7:0] p_Result_s_fu_997_p1;
wire   [7:0] p_Val2_10_fu_1001_p3;
wire   [0:0] icmp_ln895_2_fu_1008_p2;
reg   [7:0] p_Result_1_fu_1013_p4;
wire   [7:0] p_Val2_11_fu_1023_p3;
wire   [0:0] icmp_ln895_3_fu_1031_p2;
reg   [7:0] p_Result_2_fu_1036_p4;
wire   [7:0] p_Val2_12_fu_1046_p3;
wire   [0:0] icmp_ln895_4_fu_1054_p2;
reg   [7:0] p_Result_3_fu_1059_p4;
wire   [7:0] p_Val2_13_fu_1069_p3;
wire   [0:0] icmp_ln895_5_fu_1077_p2;
reg   [7:0] p_Result_4_fu_1082_p4;
wire   [7:0] p_Val2_14_fu_1092_p3;
wire   [0:0] icmp_ln895_6_fu_1100_p2;
reg   [7:0] p_Result_5_fu_1105_p4;
wire   [31:0] zext_ln96_fu_1152_p1;
reg   [31:0] val_assign_fu_1156_p3;
wire   [7:0] tmp_6_fu_1168_p3;
wire   [6:0] mem_read_addr_V_fu_1187_p2;
wire   [2:0] tmp_2_fu_1201_p9;
wire   [7:0] zext_ln891_fu_1193_p1;
wire   [7:0] tmp_2_fu_1201_p10;
wire   [31:0] zext_ln111_fu_1221_p1;
wire   [0:0] icmp_ln891_fu_1215_p2;
reg   [7:0] p_Result_6_fu_1225_p4;
wire   [0:0] icmp_ln879_1_fu_1267_p2;
wire   [0:0] icmp_ln879_2_fu_1280_p2;
wire   [59:0] select_ln879_fu_1272_p3;
wire   [0:0] icmp_ln879_3_fu_1293_p2;
wire   [59:0] select_ln879_1_fu_1285_p3;
wire   [0:0] icmp_ln879_4_fu_1306_p2;
wire   [59:0] select_ln879_2_fu_1298_p3;
wire   [0:0] icmp_ln879_5_fu_1319_p2;
wire   [59:0] select_ln879_3_fu_1311_p3;
wire   [0:0] icmp_ln879_6_fu_1332_p2;
wire   [59:0] select_ln879_4_fu_1324_p3;
wire   [0:0] icmp_ln879_7_fu_1345_p2;
wire   [59:0] select_ln879_5_fu_1337_p3;
wire   [0:0] icmp_ln879_8_fu_1358_p2;
wire   [59:0] select_ln879_6_fu_1350_p3;
wire   [4:0] trunc_ln1503_5_fu_1382_p4;
wire  signed [11:0] r_V_fu_1392_p1;
wire   [9:0] tmp_7_fu_1426_p4;
wire   [10:0] shl_ln_fu_1436_p3;
wire   [10:0] irinv_tmp_V_fu_1444_p2;
wire   [2:0] iseed_V_fu_1460_p4;
wire   [0:0] icmp_ln317_fu_1470_p2;
wire   [0:0] icmp_ln317_1_fu_1476_p2;
wire   [11:0] trunc_ln321_8_fu_1497_p1;
wire   [11:0] add_ln321_8_fu_1501_p2;
wire   [7:0] trunc_ln72_8_fu_1511_p1;
wire   [12:0] ret_V_1_fu_1557_p2;
wire   [3:0] trunc_ln1503_1_fu_1562_p4;
wire   [3:0] zbin1tmp_V_fu_1552_p2;
wire   [3:0] zbin2tmp_V_fu_1582_p2;
wire   [2:0] trunc_ln1503_6_fu_1543_p4;
wire   [0:0] tmp_14_fu_1588_p3;
wire   [2:0] xor_ln209_fu_1604_p2;
wire   [2:0] trunc_ln1503_7_fu_1572_p4;
wire   [0:0] tmp_15_fu_1596_p3;
wire   [2:0] xor_ln209_1_fu_1618_p2;
wire   [2:0] zbin2_V_fu_1624_p3;
wire   [2:0] zbin1_V_fu_1610_p3;
wire   [0:0] trunc_ln312_fu_1638_p1;
wire   [3:0] trunc_ln_fu_1642_p3;
wire   [0:0] icmp_ln883_fu_1632_p2;
wire   [3:0] finez_V_fu_1650_p2;
wire   [4:0] rinv_V_fu_1655_p2;
wire   [9:0] trunc_ln321_7_fu_1692_p1;
wire   [9:0] add_ln321_7_fu_1696_p2;
wire   [7:0] trunc_ln72_7_fu_1706_p1;
wire   [9:0] trunc_ln321_6_fu_1741_p1;
wire   [9:0] add_ln321_6_fu_1745_p2;
wire   [7:0] trunc_ln72_6_fu_1755_p1;
wire   [9:0] trunc_ln321_5_fu_1790_p1;
wire   [9:0] add_ln321_5_fu_1794_p2;
wire   [7:0] trunc_ln72_5_fu_1804_p1;
wire   [9:0] trunc_ln321_4_fu_1839_p1;
wire   [9:0] add_ln321_4_fu_1843_p2;
wire   [7:0] trunc_ln72_4_fu_1853_p1;
wire   [9:0] trunc_ln321_3_fu_1888_p1;
wire   [9:0] add_ln321_3_fu_1892_p2;
wire   [7:0] trunc_ln72_3_fu_1902_p1;
wire   [9:0] trunc_ln321_2_fu_1937_p1;
wire   [9:0] add_ln321_2_fu_1941_p2;
wire   [7:0] trunc_ln72_2_fu_1951_p1;
wire   [9:0] trunc_ln321_1_fu_1986_p1;
wire   [9:0] add_ln321_1_fu_1990_p2;
wire   [7:0] trunc_ln72_1_fu_2000_p1;
wire   [9:0] trunc_ln321_fu_2035_p1;
wire   [9:0] add_ln321_fu_2039_p2;
wire   [7:0] trunc_ln72_fu_2049_p1;
wire    ap_CS_fsm_state9;
reg   [1:0] bx_o_V_1_state;
reg    ap_block_state9;
reg   [5:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_1478;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 bx_o_V_1_data_reg = 3'd0;
#0 bx_o_V_1_vld_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

ProjectionRouterTop_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
ProjectionRouterTop_mux_83_8_1_1_U1(
    .din0(num_V_reg_2228),
    .din1(num_V_1_reg_2239),
    .din2(num_V_2_reg_2249),
    .din3(num_V_3_reg_2259),
    .din4(num_V_4_reg_2265),
    .din5(num_V_5_reg_2271),
    .din6(num_V_6_reg_2277),
    .din7(num_V_7_reg_2283),
    .din8(tmp_2_fu_1201_p9),
    .dout(tmp_2_fu_1201_p10)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state5) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state5)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state5);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((iphi_V_reg_2358 == 3'd1) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        addr_index_assign_1_fu_298 <= nvmprojout2_fu_2015_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        addr_index_assign_1_fu_298 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((iphi_V_reg_2358 == 3'd2) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        addr_index_assign_2_fu_294 <= nvmprojout3_fu_1966_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        addr_index_assign_2_fu_294 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((iphi_V_reg_2358 == 3'd3) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        addr_index_assign_3_fu_290 <= nvmprojout4_fu_1917_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        addr_index_assign_3_fu_290 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((iphi_V_reg_2358 == 3'd4) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        addr_index_assign_4_fu_286 <= nvmprojout5_fu_1868_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        addr_index_assign_4_fu_286 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((iphi_V_reg_2358 == 3'd5) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        addr_index_assign_5_fu_282 <= nvmprojout6_fu_1819_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        addr_index_assign_5_fu_282 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((iphi_V_reg_2358 == 3'd6) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        addr_index_assign_6_fu_278 <= nvmprojout7_fu_1770_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        addr_index_assign_6_fu_278 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((iphi_V_reg_2358 == 3'd7) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        addr_index_assign_7_fu_274 <= nvmprojout8_fu_1721_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        addr_index_assign_7_fu_274 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln879_reg_2298_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        addr_index_assign_8_fu_306 <= nallproj_fu_1532_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        addr_index_assign_8_fu_306 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (iphi_V_reg_2358 == 3'd0))) begin
        addr_index_assign_fu_302 <= nvmprojout1_fu_2064_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        addr_index_assign_fu_302 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b1;
    end else if (((bx_o_V_1_vld_in == 1'b0) & (1'b1 == 1'b1) & (bx_o_V_1_vld_reg == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_Repl2_1_reg_848 <= 7'd0;
    end else if (((icmp_ln227_reg_2289 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_Repl2_1_reg_848 <= i_reg_2293;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln879_fu_1143_p2 == 1'd0) & (icmp_ln227_fu_1128_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_Val2_7_fu_310 <= mem_hasdata_V_7_fu_1243_p3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_Val2_7_fu_310 <= select_ln895_fu_1115_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln879_fu_1143_p2 == 1'd0) & (icmp_ln227_fu_1128_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        read_addr_V_read_ass_fu_314 <= select_ln891_fu_1235_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        read_addr_V_read_ass_fu_314 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (bx_o_V_1_vld_in == 1'b1) & (bx_o_V_1_vld_reg == 1'b1)))) begin
        bx_o_V_1_data_reg <= bx_V;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_2293 <= i_fu_1134_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln227_reg_2289 <= icmp_ln227_fu_1128_p2;
        icmp_ln879_reg_2298_pp0_iter1_reg <= icmp_ln879_reg_2298;
        p_Repl2_1_reg_848_pp0_iter1_reg <= p_Repl2_1_reg_848;
        read_imem_V_reg_2302_pp0_iter1_reg <= read_imem_V_reg_2302;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln227_fu_1128_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln879_reg_2298 <= icmp_ln879_fu_1143_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln879_reg_2298_pp0_iter2_reg <= icmp_ln879_reg_2298_pp0_iter1_reg;
        p_Repl2_1_reg_848_pp0_iter2_reg <= p_Repl2_1_reg_848_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp_ln895_1_reg_2254 <= icmp_ln895_1_fu_962_p2;
        icmp_ln895_reg_2244 <= icmp_ln895_fu_956_p2;
        num_V_1_reg_2239 <= proj2in_nentries_V_q0;
        num_V_2_reg_2249 <= proj3in_nentries_V_q0;
        num_V_3_reg_2259 <= proj4in_nentries_V_q0;
        num_V_4_reg_2265 <= proj5in_nentries_V_q0;
        num_V_5_reg_2271 <= proj6in_nentries_V_q0;
        num_V_6_reg_2277 <= proj7in_nentries_V_q0;
        num_V_7_reg_2283 <= proj8in_nentries_V_q0;
        num_V_reg_2228 <= proj1in_nentries_V_q0;
        p_Val2_s_reg_2233 <= p_Val2_s_fu_950_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln879_reg_2298_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        iphi_V_reg_2358 <= {{p_Val2_15_fu_1363_p3[43:41]}};
        psseed_reg_2387 <= psseed_fu_1482_p2;
        ret_V_reg_2367 <= ret_V_fu_1400_p2;
        trunc_ln1503_2_reg_2377 <= {{p_Val2_15_fu_1363_p3[29:26]}};
        trunc_ln1503_3_reg_2382 <= {{irinv_tmp_V_fu_1444_p2[10:6]}};
        trunc_ln3_reg_2372 <= {{ret_V_fu_1400_p2[5:2]}};
        zext_ln1354_reg_2362[11 : 0] <= zext_ln1354_fu_1396_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln879_fu_1143_p2 == 1'd0) & (icmp_ln227_fu_1128_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        read_imem_V_reg_2302 <= read_imem_V_fu_1164_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        trunc_ln209_reg_2085 <= trunc_ln209_fu_872_p1;
        zext_ln321_1_reg_2090[7] <= zext_ln321_1_fu_896_p1[7];
        zext_ln321_reg_2080[9 : 7] <= zext_ln321_fu_868_p1[9 : 7];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        allprojout_dataarray_data_V_ce0 = 1'b1;
    end else begin
        allprojout_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln70_8_fu_1491_p2 == 1'd1) & (icmp_ln879_reg_2298_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        allprojout_dataarray_data_V_we0 = 1'b1;
    end else begin
        allprojout_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((bx_V_read_read_fu_318_p2 == 3'd0)) begin
        if ((1'b1 == ap_condition_1478)) begin
            allprojout_nentries_0_V = add_ln301_8_fu_1515_p2;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            allprojout_nentries_0_V = 8'd0;
        end else begin
            allprojout_nentries_0_V = 'bx;
        end
    end else begin
        allprojout_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_8_fu_1491_p2 == 1'd1) & (icmp_ln879_reg_2298_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (bx_V_read_read_fu_318_p2 == 3'd0)) | ((1'b1 == ap_CS_fsm_state1) & (bx_V_read_read_fu_318_p2 == 3'd0) & (ap_start == 1'b1)))) begin
        allprojout_nentries_0_V_ap_vld = 1'b1;
    end else begin
        allprojout_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((bx_V_read_read_fu_318_p2 == 3'd1)) begin
        if ((1'b1 == ap_condition_1478)) begin
            allprojout_nentries_1_V = add_ln301_8_fu_1515_p2;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            allprojout_nentries_1_V = 8'd0;
        end else begin
            allprojout_nentries_1_V = 'bx;
        end
    end else begin
        allprojout_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_8_fu_1491_p2 == 1'd1) & (icmp_ln879_reg_2298_pp0_iter1_reg == 1'd0) & (bx_V_read_read_fu_318_p2 == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((bx_V_read_read_fu_318_p2 == 3'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        allprojout_nentries_1_V_ap_vld = 1'b1;
    end else begin
        allprojout_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((bx_V_read_read_fu_318_p2 == 3'd2)) begin
        if ((1'b1 == ap_condition_1478)) begin
            allprojout_nentries_2_V = add_ln301_8_fu_1515_p2;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            allprojout_nentries_2_V = 8'd0;
        end else begin
            allprojout_nentries_2_V = 'bx;
        end
    end else begin
        allprojout_nentries_2_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_8_fu_1491_p2 == 1'd1) & (icmp_ln879_reg_2298_pp0_iter1_reg == 1'd0) & (bx_V_read_read_fu_318_p2 == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((bx_V_read_read_fu_318_p2 == 3'd2) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        allprojout_nentries_2_V_ap_vld = 1'b1;
    end else begin
        allprojout_nentries_2_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((bx_V_read_read_fu_318_p2 == 3'd3)) begin
        if ((1'b1 == ap_condition_1478)) begin
            allprojout_nentries_3_V = add_ln301_8_fu_1515_p2;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            allprojout_nentries_3_V = 8'd0;
        end else begin
            allprojout_nentries_3_V = 'bx;
        end
    end else begin
        allprojout_nentries_3_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_8_fu_1491_p2 == 1'd1) & (icmp_ln879_reg_2298_pp0_iter1_reg == 1'd0) & (bx_V_read_read_fu_318_p2 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((bx_V_read_read_fu_318_p2 == 3'd3) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        allprojout_nentries_3_V_ap_vld = 1'b1;
    end else begin
        allprojout_nentries_3_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((bx_V_read_read_fu_318_p2 == 3'd4)) begin
        if ((1'b1 == ap_condition_1478)) begin
            allprojout_nentries_4_V = add_ln301_8_fu_1515_p2;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            allprojout_nentries_4_V = 8'd0;
        end else begin
            allprojout_nentries_4_V = 'bx;
        end
    end else begin
        allprojout_nentries_4_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_8_fu_1491_p2 == 1'd1) & (icmp_ln879_reg_2298_pp0_iter1_reg == 1'd0) & (bx_V_read_read_fu_318_p2 == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((bx_V_read_read_fu_318_p2 == 3'd4) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        allprojout_nentries_4_V_ap_vld = 1'b1;
    end else begin
        allprojout_nentries_4_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((bx_V_read_read_fu_318_p2 == 3'd5)) begin
        if ((1'b1 == ap_condition_1478)) begin
            allprojout_nentries_5_V = add_ln301_8_fu_1515_p2;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            allprojout_nentries_5_V = 8'd0;
        end else begin
            allprojout_nentries_5_V = 'bx;
        end
    end else begin
        allprojout_nentries_5_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_8_fu_1491_p2 == 1'd1) & (icmp_ln879_reg_2298_pp0_iter1_reg == 1'd0) & (bx_V_read_read_fu_318_p2 == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((bx_V_read_read_fu_318_p2 == 3'd5) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        allprojout_nentries_5_V_ap_vld = 1'b1;
    end else begin
        allprojout_nentries_5_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((bx_V_read_read_fu_318_p2 == 3'd6)) begin
        if ((1'b1 == ap_condition_1478)) begin
            allprojout_nentries_6_V = add_ln301_8_fu_1515_p2;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            allprojout_nentries_6_V = 8'd0;
        end else begin
            allprojout_nentries_6_V = 'bx;
        end
    end else begin
        allprojout_nentries_6_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_8_fu_1491_p2 == 1'd1) & (icmp_ln879_reg_2298_pp0_iter1_reg == 1'd0) & (bx_V_read_read_fu_318_p2 == 3'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((bx_V_read_read_fu_318_p2 == 3'd6) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        allprojout_nentries_6_V_ap_vld = 1'b1;
    end else begin
        allprojout_nentries_6_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((bx_V_read_read_fu_318_p2 == 3'd7)) begin
        if ((1'b1 == ap_condition_1478)) begin
            allprojout_nentries_7_V = add_ln301_8_fu_1515_p2;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            allprojout_nentries_7_V = 8'd0;
        end else begin
            allprojout_nentries_7_V = 'bx;
        end
    end else begin
        allprojout_nentries_7_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_8_fu_1491_p2 == 1'd1) & (icmp_ln879_reg_2298_pp0_iter1_reg == 1'd0) & (bx_V_read_read_fu_318_p2 == 3'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((bx_V_read_read_fu_318_p2 == 3'd7) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        allprojout_nentries_7_V_ap_vld = 1'b1;
    end else begin
        allprojout_nentries_7_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln227_fu_1128_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if ((~((bx_o_V_1_state == 2'd1) | ((1'b1 == 1'b0) & (bx_o_V_1_state == 2'd3))) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln227_reg_2289 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_p_Repl2_1_phi_fu_852_p4 = i_reg_2293;
    end else begin
        ap_phi_mux_p_Repl2_1_phi_fu_852_p4 = p_Repl2_1_reg_848;
    end
end

always @ (*) begin
    if ((~((bx_o_V_1_state == 2'd1) | ((1'b1 == 1'b0) & (bx_o_V_1_state == 2'd3))) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln367_fu_1261_p2 == 1'd1) & (icmp_ln227_fu_1128_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bx_o_V_1_vld_in = 1'b1;
    end else begin
        bx_o_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        proj1in_dataarray_data_V_ce0 = 1'b1;
    end else begin
        proj1in_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        proj1in_nentries_V_ce0 = 1'b1;
    end else begin
        proj1in_nentries_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        proj2in_dataarray_data_V_ce0 = 1'b1;
    end else begin
        proj2in_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        proj2in_nentries_V_ce0 = 1'b1;
    end else begin
        proj2in_nentries_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        proj3in_dataarray_data_V_ce0 = 1'b1;
    end else begin
        proj3in_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        proj3in_nentries_V_ce0 = 1'b1;
    end else begin
        proj3in_nentries_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        proj4in_dataarray_data_V_ce0 = 1'b1;
    end else begin
        proj4in_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        proj4in_nentries_V_ce0 = 1'b1;
    end else begin
        proj4in_nentries_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        proj5in_dataarray_data_V_ce0 = 1'b1;
    end else begin
        proj5in_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        proj5in_nentries_V_ce0 = 1'b1;
    end else begin
        proj5in_nentries_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        proj6in_dataarray_data_V_ce0 = 1'b1;
    end else begin
        proj6in_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        proj6in_nentries_V_ce0 = 1'b1;
    end else begin
        proj6in_nentries_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        proj7in_dataarray_data_V_ce0 = 1'b1;
    end else begin
        proj7in_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        proj7in_nentries_V_ce0 = 1'b1;
    end else begin
        proj7in_nentries_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        proj8in_dataarray_data_V_ce0 = 1'b1;
    end else begin
        proj8in_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        proj8in_nentries_V_ce0 = 1'b1;
    end else begin
        proj8in_nentries_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout1_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout1_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln70_fu_2029_p2 == 1'd1) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (iphi_V_reg_2358 == 3'd0))) begin
        vmprojout1_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout1_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (icmp_ln70_fu_2029_p2 == 1'd1) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (iphi_V_reg_2358 == 3'd0))) begin
        vmprojout1_nentries_0_V = add_ln301_fu_2053_p2;
    end else if (((trunc_ln209_fu_872_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        vmprojout1_nentries_0_V = 8'd0;
    end else begin
        vmprojout1_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_fu_2029_p2 == 1'd1) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (iphi_V_reg_2358 == 3'd0)) | ((trunc_ln209_fu_872_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        vmprojout1_nentries_0_V_ap_vld = 1'b1;
    end else begin
        vmprojout1_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (icmp_ln70_fu_2029_p2 == 1'd1) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (iphi_V_reg_2358 == 3'd0))) begin
        vmprojout1_nentries_1_V = add_ln301_fu_2053_p2;
    end else if (((trunc_ln209_fu_872_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        vmprojout1_nentries_1_V = 8'd0;
    end else begin
        vmprojout1_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_fu_2029_p2 == 1'd1) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (iphi_V_reg_2358 == 3'd0)) | ((trunc_ln209_fu_872_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        vmprojout1_nentries_1_V_ap_vld = 1'b1;
    end else begin
        vmprojout1_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout2_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout2_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln70_1_fu_1980_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd1) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout2_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout2_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (icmp_ln70_1_fu_1980_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd1) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout2_nentries_0_V = add_ln301_1_fu_2004_p2;
    end else if (((trunc_ln209_fu_872_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        vmprojout2_nentries_0_V = 8'd0;
    end else begin
        vmprojout2_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_1_fu_1980_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd1) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln209_fu_872_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        vmprojout2_nentries_0_V_ap_vld = 1'b1;
    end else begin
        vmprojout2_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (icmp_ln70_1_fu_1980_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd1) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout2_nentries_1_V = add_ln301_1_fu_2004_p2;
    end else if (((trunc_ln209_fu_872_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        vmprojout2_nentries_1_V = 8'd0;
    end else begin
        vmprojout2_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_1_fu_1980_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd1) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln209_fu_872_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        vmprojout2_nentries_1_V_ap_vld = 1'b1;
    end else begin
        vmprojout2_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout3_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout3_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln70_2_fu_1931_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd2) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout3_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout3_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (icmp_ln70_2_fu_1931_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd2) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout3_nentries_0_V = add_ln301_2_fu_1955_p2;
    end else if (((trunc_ln209_fu_872_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        vmprojout3_nentries_0_V = 8'd0;
    end else begin
        vmprojout3_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_2_fu_1931_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd2) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln209_fu_872_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        vmprojout3_nentries_0_V_ap_vld = 1'b1;
    end else begin
        vmprojout3_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (icmp_ln70_2_fu_1931_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd2) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout3_nentries_1_V = add_ln301_2_fu_1955_p2;
    end else if (((trunc_ln209_fu_872_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        vmprojout3_nentries_1_V = 8'd0;
    end else begin
        vmprojout3_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_2_fu_1931_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd2) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln209_fu_872_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        vmprojout3_nentries_1_V_ap_vld = 1'b1;
    end else begin
        vmprojout3_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout4_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout4_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln70_3_fu_1882_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd3) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout4_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout4_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (icmp_ln70_3_fu_1882_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd3) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout4_nentries_0_V = add_ln301_3_fu_1906_p2;
    end else if (((trunc_ln209_fu_872_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        vmprojout4_nentries_0_V = 8'd0;
    end else begin
        vmprojout4_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_3_fu_1882_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd3) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln209_fu_872_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        vmprojout4_nentries_0_V_ap_vld = 1'b1;
    end else begin
        vmprojout4_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (icmp_ln70_3_fu_1882_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd3) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout4_nentries_1_V = add_ln301_3_fu_1906_p2;
    end else if (((trunc_ln209_fu_872_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        vmprojout4_nentries_1_V = 8'd0;
    end else begin
        vmprojout4_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_3_fu_1882_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd3) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln209_fu_872_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        vmprojout4_nentries_1_V_ap_vld = 1'b1;
    end else begin
        vmprojout4_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout5_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout5_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln70_4_fu_1833_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd4) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout5_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout5_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (icmp_ln70_4_fu_1833_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd4) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout5_nentries_0_V = add_ln301_4_fu_1857_p2;
    end else if (((trunc_ln209_fu_872_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        vmprojout5_nentries_0_V = 8'd0;
    end else begin
        vmprojout5_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_4_fu_1833_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd4) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln209_fu_872_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        vmprojout5_nentries_0_V_ap_vld = 1'b1;
    end else begin
        vmprojout5_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (icmp_ln70_4_fu_1833_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd4) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout5_nentries_1_V = add_ln301_4_fu_1857_p2;
    end else if (((trunc_ln209_fu_872_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        vmprojout5_nentries_1_V = 8'd0;
    end else begin
        vmprojout5_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_4_fu_1833_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd4) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln209_fu_872_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        vmprojout5_nentries_1_V_ap_vld = 1'b1;
    end else begin
        vmprojout5_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout6_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout6_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln70_5_fu_1784_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd5) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout6_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout6_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (icmp_ln70_5_fu_1784_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd5) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout6_nentries_0_V = add_ln301_5_fu_1808_p2;
    end else if (((trunc_ln209_fu_872_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        vmprojout6_nentries_0_V = 8'd0;
    end else begin
        vmprojout6_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_5_fu_1784_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd5) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln209_fu_872_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        vmprojout6_nentries_0_V_ap_vld = 1'b1;
    end else begin
        vmprojout6_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (icmp_ln70_5_fu_1784_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd5) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout6_nentries_1_V = add_ln301_5_fu_1808_p2;
    end else if (((trunc_ln209_fu_872_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        vmprojout6_nentries_1_V = 8'd0;
    end else begin
        vmprojout6_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_5_fu_1784_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd5) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln209_fu_872_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        vmprojout6_nentries_1_V_ap_vld = 1'b1;
    end else begin
        vmprojout6_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout7_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout7_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln70_6_fu_1735_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd6) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout7_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout7_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (icmp_ln70_6_fu_1735_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd6) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout7_nentries_0_V = add_ln301_6_fu_1759_p2;
    end else if (((trunc_ln209_fu_872_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        vmprojout7_nentries_0_V = 8'd0;
    end else begin
        vmprojout7_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_6_fu_1735_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd6) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln209_fu_872_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        vmprojout7_nentries_0_V_ap_vld = 1'b1;
    end else begin
        vmprojout7_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (icmp_ln70_6_fu_1735_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd6) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout7_nentries_1_V = add_ln301_6_fu_1759_p2;
    end else if (((trunc_ln209_fu_872_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        vmprojout7_nentries_1_V = 8'd0;
    end else begin
        vmprojout7_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_6_fu_1735_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd6) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln209_fu_872_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        vmprojout7_nentries_1_V_ap_vld = 1'b1;
    end else begin
        vmprojout7_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout8_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout8_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln70_7_fu_1686_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd7) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout8_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout8_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (icmp_ln70_7_fu_1686_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd7) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout8_nentries_0_V = add_ln301_7_fu_1710_p2;
    end else if (((trunc_ln209_fu_872_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        vmprojout8_nentries_0_V = 8'd0;
    end else begin
        vmprojout8_nentries_0_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_7_fu_1686_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd7) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln209_fu_872_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        vmprojout8_nentries_0_V_ap_vld = 1'b1;
    end else begin
        vmprojout8_nentries_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (icmp_ln70_7_fu_1686_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd7) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        vmprojout8_nentries_1_V = add_ln301_7_fu_1710_p2;
    end else if (((trunc_ln209_fu_872_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        vmprojout8_nentries_1_V = 8'd0;
    end else begin
        vmprojout8_nentries_1_V = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln70_7_fu_1686_p2 == 1'd1) & (iphi_V_reg_2358 == 3'd7) & (icmp_ln879_reg_2298_pp0_iter2_reg == 1'd0) & (trunc_ln209_reg_2085 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((trunc_ln209_fu_872_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        vmprojout8_nentries_1_V_ap_vld = 1'b1;
    end else begin
        vmprojout8_nentries_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln227_fu_1128_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln227_fu_1128_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            if ((~((bx_o_V_1_state == 2'd1) | ((1'b1 == 1'b0) & (bx_o_V_1_state == 2'd3))) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln301_1_fu_2004_p2 = (8'd1 + trunc_ln72_1_fu_2000_p1);

assign add_ln301_2_fu_1955_p2 = (8'd1 + trunc_ln72_2_fu_1951_p1);

assign add_ln301_3_fu_1906_p2 = (8'd1 + trunc_ln72_3_fu_1902_p1);

assign add_ln301_4_fu_1857_p2 = (8'd1 + trunc_ln72_4_fu_1853_p1);

assign add_ln301_5_fu_1808_p2 = (8'd1 + trunc_ln72_5_fu_1804_p1);

assign add_ln301_6_fu_1759_p2 = (8'd1 + trunc_ln72_6_fu_1755_p1);

assign add_ln301_7_fu_1710_p2 = (8'd1 + trunc_ln72_7_fu_1706_p1);

assign add_ln301_8_fu_1515_p2 = (8'd1 + trunc_ln72_8_fu_1511_p1);

assign add_ln301_fu_2053_p2 = (8'd1 + trunc_ln72_fu_2049_p1);

assign add_ln321_1_fu_1990_p2 = (trunc_ln321_1_fu_1986_p1 + zext_ln321_1_reg_2090);

assign add_ln321_2_fu_1941_p2 = (trunc_ln321_2_fu_1937_p1 + zext_ln321_1_reg_2090);

assign add_ln321_3_fu_1892_p2 = (trunc_ln321_3_fu_1888_p1 + zext_ln321_1_reg_2090);

assign add_ln321_4_fu_1843_p2 = (trunc_ln321_4_fu_1839_p1 + zext_ln321_1_reg_2090);

assign add_ln321_5_fu_1794_p2 = (trunc_ln321_5_fu_1790_p1 + zext_ln321_1_reg_2090);

assign add_ln321_6_fu_1745_p2 = (trunc_ln321_6_fu_1741_p1 + zext_ln321_1_reg_2090);

assign add_ln321_7_fu_1696_p2 = (trunc_ln321_7_fu_1692_p1 + zext_ln321_1_reg_2090);

assign add_ln321_8_fu_1501_p2 = (trunc_ln321_8_fu_1497_p1 + zext_ln321_reg_2080);

assign add_ln321_fu_2039_p2 = (trunc_ln321_fu_2035_p1 + zext_ln321_1_reg_2090);

assign allprojout_dataarray_data_V_address0 = sext_ln321_8_fu_1506_p1;

assign allprojout_dataarray_data_V_d0 = p_Val2_15_fu_1363_p3;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9 = ((bx_o_V_1_state == 2'd1) | ((1'b1 == 1'b0) & (bx_o_V_1_state == 2'd3)));
end

always @ (*) begin
    ap_condition_1478 = ((1'b0 == ap_block_pp0_stage0_01001) & (icmp_ln70_8_fu_1491_p2 == 1'd1) & (icmp_ln879_reg_2298_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign bx_V_read_read_fu_318_p2 = bx_V;

assign bx_o_V = bx_o_V_1_data_reg;

assign bx_o_V_ap_vld = bx_o_V_1_vld_reg;

assign finez_V_fu_1650_p2 = (trunc_ln1503_2_reg_2377 - trunc_ln_fu_1642_p3);

assign i_fu_1134_p2 = (ap_phi_mux_p_Repl2_1_phi_fu_852_p4 + 7'd1);

assign icmp_ln227_fu_1128_p2 = ((ap_phi_mux_p_Repl2_1_phi_fu_852_p4 == 7'd101) ? 1'b1 : 1'b0);

assign icmp_ln317_1_fu_1476_p2 = ((iseed_V_fu_1460_p4 != 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln317_fu_1470_p2 = ((iseed_V_fu_1460_p4 != 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln367_fu_1261_p2 = ((ap_phi_mux_p_Repl2_1_phi_fu_852_p4 == 7'd100) ? 1'b1 : 1'b0);

assign icmp_ln70_1_fu_1980_p2 = (($signed(addr_index_assign_1_fu_298) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign icmp_ln70_2_fu_1931_p2 = (($signed(addr_index_assign_2_fu_294) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign icmp_ln70_3_fu_1882_p2 = (($signed(addr_index_assign_3_fu_290) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign icmp_ln70_4_fu_1833_p2 = (($signed(addr_index_assign_4_fu_286) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign icmp_ln70_5_fu_1784_p2 = (($signed(addr_index_assign_5_fu_282) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign icmp_ln70_6_fu_1735_p2 = (($signed(addr_index_assign_6_fu_278) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign icmp_ln70_7_fu_1686_p2 = (($signed(addr_index_assign_7_fu_274) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign icmp_ln70_8_fu_1491_p2 = (($signed(addr_index_assign_8_fu_306) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_2029_p2 = (($signed(addr_index_assign_fu_302) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign icmp_ln879_1_fu_1267_p2 = ((read_imem_V_reg_2302_pp0_iter1_reg == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln879_2_fu_1280_p2 = ((read_imem_V_reg_2302_pp0_iter1_reg == 5'd1) ? 1'b1 : 1'b0);

assign icmp_ln879_3_fu_1293_p2 = ((read_imem_V_reg_2302_pp0_iter1_reg == 5'd2) ? 1'b1 : 1'b0);

assign icmp_ln879_4_fu_1306_p2 = ((read_imem_V_reg_2302_pp0_iter1_reg == 5'd3) ? 1'b1 : 1'b0);

assign icmp_ln879_5_fu_1319_p2 = ((read_imem_V_reg_2302_pp0_iter1_reg == 5'd4) ? 1'b1 : 1'b0);

assign icmp_ln879_6_fu_1332_p2 = ((read_imem_V_reg_2302_pp0_iter1_reg == 5'd5) ? 1'b1 : 1'b0);

assign icmp_ln879_7_fu_1345_p2 = ((read_imem_V_reg_2302_pp0_iter1_reg == 5'd6) ? 1'b1 : 1'b0);

assign icmp_ln879_8_fu_1358_p2 = ((read_imem_V_reg_2302_pp0_iter1_reg == 5'd7) ? 1'b1 : 1'b0);

assign icmp_ln879_fu_1143_p2 = ((p_Val2_7_fu_310 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln883_fu_1632_p2 = ((zbin2_V_fu_1624_p3 != zbin1_V_fu_1610_p3) ? 1'b1 : 1'b0);

assign icmp_ln891_fu_1215_p2 = ((zext_ln891_fu_1193_p1 < tmp_2_fu_1201_p10) ? 1'b1 : 1'b0);

assign icmp_ln895_1_fu_962_p2 = ((proj3in_nentries_V_q0 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln895_2_fu_1008_p2 = ((num_V_3_reg_2259 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln895_3_fu_1031_p2 = ((num_V_4_reg_2265 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln895_4_fu_1054_p2 = ((num_V_5_reg_2271 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln895_5_fu_1077_p2 = ((num_V_6_reg_2277 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln895_6_fu_1100_p2 = ((num_V_7_reg_2283 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_956_p2 = ((proj2in_nentries_V_q0 == 8'd0) ? 1'b1 : 1'b0);

assign irinv_tmp_V_fu_1444_p2 = (11'd0 - shl_ln_fu_1436_p3);

assign iseed_V_fu_1460_p4 = {{p_Val2_15_fu_1363_p3[59:57]}};

assign mem_hasdata_V_7_fu_1243_p3 = ((icmp_ln891_fu_1215_p2[0:0] === 1'b1) ? p_Val2_7_fu_310 : p_Result_6_fu_1225_p4);

assign mem_read_addr_V_fu_1187_p2 = (7'd1 + read_addr_V_read_ass_fu_314);

assign nallproj_fu_1532_p2 = (addr_index_assign_8_fu_306 + 32'd1);

assign nvmprojout1_fu_2064_p2 = (addr_index_assign_fu_302 + 32'd1);

assign nvmprojout2_fu_2015_p2 = (addr_index_assign_1_fu_298 + 32'd1);

assign nvmprojout3_fu_1966_p2 = (addr_index_assign_2_fu_294 + 32'd1);

assign nvmprojout4_fu_1917_p2 = (addr_index_assign_3_fu_290 + 32'd1);

assign nvmprojout5_fu_1868_p2 = (addr_index_assign_4_fu_286 + 32'd1);

assign nvmprojout6_fu_1819_p2 = (addr_index_assign_5_fu_282 + 32'd1);

assign nvmprojout7_fu_1770_p2 = (addr_index_assign_6_fu_278 + 32'd1);

assign nvmprojout8_fu_1721_p2 = (addr_index_assign_7_fu_274 + 32'd1);

always @ (*) begin
    p_Result_1_fu_1013_p4 = p_Val2_10_fu_1001_p3;
    p_Result_1_fu_1013_p4[32'd3] = |(1'd1);
end

always @ (*) begin
    p_Result_2_fu_1036_p4 = p_Val2_11_fu_1023_p3;
    p_Result_2_fu_1036_p4[32'd4] = |(1'd1);
end

always @ (*) begin
    p_Result_3_fu_1059_p4 = p_Val2_12_fu_1046_p3;
    p_Result_3_fu_1059_p4[32'd5] = |(1'd1);
end

always @ (*) begin
    p_Result_4_fu_1082_p4 = p_Val2_13_fu_1069_p3;
    p_Result_4_fu_1082_p4[32'd6] = |(1'd1);
end

always @ (*) begin
    p_Result_5_fu_1105_p4 = p_Val2_14_fu_1092_p3;
    p_Result_5_fu_1105_p4[32'd7] = |(1'd1);
end

always @ (*) begin
    p_Result_6_fu_1225_p4 = p_Val2_7_fu_310;
    p_Result_6_fu_1225_p4[zext_ln111_fu_1221_p1] = |(32'd0);
end

assign p_Result_s_fu_997_p1 = tmp_4_fu_989_p3;

assign p_Val2_10_fu_1001_p3 = ((icmp_ln895_1_reg_2254[0:0] === 1'b1) ? zext_ln895_fu_985_p1 : p_Result_s_fu_997_p1);

assign p_Val2_11_fu_1023_p3 = ((icmp_ln895_2_fu_1008_p2[0:0] === 1'b1) ? p_Val2_10_fu_1001_p3 : p_Result_1_fu_1013_p4);

assign p_Val2_12_fu_1046_p3 = ((icmp_ln895_3_fu_1031_p2[0:0] === 1'b1) ? p_Val2_11_fu_1023_p3 : p_Result_2_fu_1036_p4);

assign p_Val2_13_fu_1069_p3 = ((icmp_ln895_4_fu_1054_p2[0:0] === 1'b1) ? p_Val2_12_fu_1046_p3 : p_Result_3_fu_1059_p4);

assign p_Val2_14_fu_1092_p3 = ((icmp_ln895_5_fu_1077_p2[0:0] === 1'b1) ? p_Val2_13_fu_1069_p3 : p_Result_4_fu_1082_p4);

assign p_Val2_15_fu_1363_p3 = ((icmp_ln879_8_fu_1358_p2[0:0] === 1'b1) ? proj8in_dataarray_data_V_q0 : select_ln879_6_fu_1350_p3);

assign p_Val2_9_fu_978_p3 = ((icmp_ln895_reg_2244[0:0] === 1'b1) ? zext_ln39_fu_968_p1 : tmp_1_fu_971_p3);

assign p_Val2_s_fu_950_p2 = ((proj1in_nentries_V_q0 != 8'd0) ? 1'b1 : 1'b0);

assign proj1in_dataarray_data_V_address0 = zext_ln63_fu_1175_p1;

assign proj1in_nentries_V_address0 = zext_ln544_fu_876_p1;

assign proj2in_dataarray_data_V_address0 = zext_ln63_fu_1175_p1;

assign proj2in_nentries_V_address0 = zext_ln544_fu_876_p1;

assign proj3in_dataarray_data_V_address0 = zext_ln63_fu_1175_p1;

assign proj3in_nentries_V_address0 = zext_ln544_fu_876_p1;

assign proj4in_dataarray_data_V_address0 = zext_ln63_fu_1175_p1;

assign proj4in_nentries_V_address0 = zext_ln544_fu_876_p1;

assign proj5in_dataarray_data_V_address0 = zext_ln63_fu_1175_p1;

assign proj5in_nentries_V_address0 = zext_ln544_fu_876_p1;

assign proj6in_dataarray_data_V_address0 = zext_ln63_fu_1175_p1;

assign proj6in_nentries_V_address0 = zext_ln544_fu_876_p1;

assign proj7in_dataarray_data_V_address0 = zext_ln63_fu_1175_p1;

assign proj7in_nentries_V_address0 = zext_ln544_fu_876_p1;

assign proj8in_dataarray_data_V_address0 = zext_ln63_fu_1175_p1;

assign proj8in_nentries_V_address0 = zext_ln544_fu_876_p1;

assign psseed_fu_1482_p2 = (icmp_ln317_fu_1470_p2 & icmp_ln317_1_fu_1476_p2);

assign r_V_fu_1392_p1 = $signed(trunc_ln1503_5_fu_1382_p4);

assign read_imem_V_fu_1164_p1 = val_assign_fu_1156_p3[4:0];

assign ret_V_1_fu_1557_p2 = (13'd2 + zext_ln1354_reg_2362);

assign ret_V_2_fu_1660_p7 = {{{{{{p_Repl2_1_reg_848_pp0_iter2_reg}, {zbin1_V_fu_1610_p3}}, {icmp_ln883_fu_1632_p2}}, {finez_V_fu_1650_p2}}, {rinv_V_fu_1655_p2}}, {psseed_reg_2387}};

assign ret_V_fu_1400_p2 = (13'd62 + zext_ln1354_fu_1396_p1);

assign rinv_V_fu_1655_p2 = (trunc_ln1503_3_reg_2382 ^ 5'd16);

assign select_ln879_1_fu_1285_p3 = ((icmp_ln879_2_fu_1280_p2[0:0] === 1'b1) ? proj2in_dataarray_data_V_q0 : select_ln879_fu_1272_p3);

assign select_ln879_2_fu_1298_p3 = ((icmp_ln879_3_fu_1293_p2[0:0] === 1'b1) ? proj3in_dataarray_data_V_q0 : select_ln879_1_fu_1285_p3);

assign select_ln879_3_fu_1311_p3 = ((icmp_ln879_4_fu_1306_p2[0:0] === 1'b1) ? proj4in_dataarray_data_V_q0 : select_ln879_2_fu_1298_p3);

assign select_ln879_4_fu_1324_p3 = ((icmp_ln879_5_fu_1319_p2[0:0] === 1'b1) ? proj5in_dataarray_data_V_q0 : select_ln879_3_fu_1311_p3);

assign select_ln879_5_fu_1337_p3 = ((icmp_ln879_6_fu_1332_p2[0:0] === 1'b1) ? proj6in_dataarray_data_V_q0 : select_ln879_4_fu_1324_p3);

assign select_ln879_6_fu_1350_p3 = ((icmp_ln879_7_fu_1345_p2[0:0] === 1'b1) ? proj7in_dataarray_data_V_q0 : select_ln879_5_fu_1337_p3);

assign select_ln879_fu_1272_p3 = ((icmp_ln879_1_fu_1267_p2[0:0] === 1'b1) ? proj1in_dataarray_data_V_q0 : 60'd0);

assign select_ln891_fu_1235_p3 = ((icmp_ln891_fu_1215_p2[0:0] === 1'b1) ? mem_read_addr_V_fu_1187_p2 : 7'd0);

assign select_ln895_fu_1115_p3 = ((icmp_ln895_6_fu_1100_p2[0:0] === 1'b1) ? p_Val2_14_fu_1092_p3 : p_Result_5_fu_1105_p4);

assign sext_ln321_1_fu_1995_p1 = $signed(add_ln321_1_fu_1990_p2);

assign sext_ln321_2_fu_1946_p1 = $signed(add_ln321_2_fu_1941_p2);

assign sext_ln321_3_fu_1897_p1 = $signed(add_ln321_3_fu_1892_p2);

assign sext_ln321_4_fu_1848_p1 = $signed(add_ln321_4_fu_1843_p2);

assign sext_ln321_5_fu_1799_p1 = $signed(add_ln321_5_fu_1794_p2);

assign sext_ln321_6_fu_1750_p1 = $signed(add_ln321_6_fu_1745_p2);

assign sext_ln321_7_fu_1701_p1 = $signed(add_ln321_7_fu_1696_p2);

assign sext_ln321_8_fu_1506_p1 = $signed(add_ln321_8_fu_1501_p2);

assign sext_ln321_fu_2044_p1 = $signed(add_ln321_fu_2039_p2);

assign shl_ln_fu_1436_p3 = {{tmp_7_fu_1426_p4}, {1'd0}};

assign tmp_14_fu_1588_p3 = zbin1tmp_V_fu_1552_p2[32'd3];

assign tmp_15_fu_1596_p3 = zbin2tmp_V_fu_1582_p2[32'd3];

assign tmp_1_fu_971_p3 = {{1'd1}, {p_Val2_s_reg_2233}};

assign tmp_2_fu_1201_p9 = val_assign_fu_1156_p3[2:0];

assign tmp_3_fu_860_p3 = {{bx_V}, {7'd0}};

assign tmp_4_fu_989_p3 = {{1'd1}, {p_Val2_9_fu_978_p3}};

assign tmp_5_fu_888_p3 = {{trunc_ln209_fu_872_p1}, {7'd0}};

assign tmp_6_fu_1168_p3 = {{trunc_ln209_reg_2085}, {read_addr_V_read_ass_fu_314}};

assign tmp_7_fu_1426_p4 = {{p_Val2_15_fu_1363_p3[19:10]}};

assign trunc_ln1503_1_fu_1562_p4 = {{ret_V_1_fu_1557_p2[5:2]}};

assign trunc_ln1503_5_fu_1382_p4 = {{p_Val2_15_fu_1363_p3[31:27]}};

assign trunc_ln1503_6_fu_1543_p4 = {{ret_V_reg_2367[4:2]}};

assign trunc_ln1503_7_fu_1572_p4 = {{ret_V_1_fu_1557_p2[4:2]}};

assign trunc_ln209_fu_872_p1 = bx_V[0:0];

assign trunc_ln312_fu_1638_p1 = zbin1_V_fu_1610_p3[0:0];

assign trunc_ln321_1_fu_1986_p1 = addr_index_assign_1_fu_298[9:0];

assign trunc_ln321_2_fu_1937_p1 = addr_index_assign_2_fu_294[9:0];

assign trunc_ln321_3_fu_1888_p1 = addr_index_assign_3_fu_290[9:0];

assign trunc_ln321_4_fu_1839_p1 = addr_index_assign_4_fu_286[9:0];

assign trunc_ln321_5_fu_1790_p1 = addr_index_assign_5_fu_282[9:0];

assign trunc_ln321_6_fu_1741_p1 = addr_index_assign_6_fu_278[9:0];

assign trunc_ln321_7_fu_1692_p1 = addr_index_assign_7_fu_274[9:0];

assign trunc_ln321_8_fu_1497_p1 = addr_index_assign_8_fu_306[11:0];

assign trunc_ln321_fu_2035_p1 = addr_index_assign_fu_302[9:0];

assign trunc_ln72_1_fu_2000_p1 = addr_index_assign_1_fu_298[7:0];

assign trunc_ln72_2_fu_1951_p1 = addr_index_assign_2_fu_294[7:0];

assign trunc_ln72_3_fu_1902_p1 = addr_index_assign_3_fu_290[7:0];

assign trunc_ln72_4_fu_1853_p1 = addr_index_assign_4_fu_286[7:0];

assign trunc_ln72_5_fu_1804_p1 = addr_index_assign_5_fu_282[7:0];

assign trunc_ln72_6_fu_1755_p1 = addr_index_assign_6_fu_278[7:0];

assign trunc_ln72_7_fu_1706_p1 = addr_index_assign_7_fu_274[7:0];

assign trunc_ln72_8_fu_1511_p1 = addr_index_assign_8_fu_306[7:0];

assign trunc_ln72_fu_2049_p1 = addr_index_assign_fu_302[7:0];

assign trunc_ln_fu_1642_p3 = {{trunc_ln312_fu_1638_p1}, {3'd0}};


always @ (zext_ln96_fu_1152_p1) begin
    if (zext_ln96_fu_1152_p1[0] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd0;
    end else if (zext_ln96_fu_1152_p1[1] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd1;
    end else if (zext_ln96_fu_1152_p1[2] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd2;
    end else if (zext_ln96_fu_1152_p1[3] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd3;
    end else if (zext_ln96_fu_1152_p1[4] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd4;
    end else if (zext_ln96_fu_1152_p1[5] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd5;
    end else if (zext_ln96_fu_1152_p1[6] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd6;
    end else if (zext_ln96_fu_1152_p1[7] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd7;
    end else if (zext_ln96_fu_1152_p1[8] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd8;
    end else if (zext_ln96_fu_1152_p1[9] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd9;
    end else if (zext_ln96_fu_1152_p1[10] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd10;
    end else if (zext_ln96_fu_1152_p1[11] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd11;
    end else if (zext_ln96_fu_1152_p1[12] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd12;
    end else if (zext_ln96_fu_1152_p1[13] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd13;
    end else if (zext_ln96_fu_1152_p1[14] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd14;
    end else if (zext_ln96_fu_1152_p1[15] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd15;
    end else if (zext_ln96_fu_1152_p1[16] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd16;
    end else if (zext_ln96_fu_1152_p1[17] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd17;
    end else if (zext_ln96_fu_1152_p1[18] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd18;
    end else if (zext_ln96_fu_1152_p1[19] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd19;
    end else if (zext_ln96_fu_1152_p1[20] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd20;
    end else if (zext_ln96_fu_1152_p1[21] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd21;
    end else if (zext_ln96_fu_1152_p1[22] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd22;
    end else if (zext_ln96_fu_1152_p1[23] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd23;
    end else if (zext_ln96_fu_1152_p1[24] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd24;
    end else if (zext_ln96_fu_1152_p1[25] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd25;
    end else if (zext_ln96_fu_1152_p1[26] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd26;
    end else if (zext_ln96_fu_1152_p1[27] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd27;
    end else if (zext_ln96_fu_1152_p1[28] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd28;
    end else if (zext_ln96_fu_1152_p1[29] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd29;
    end else if (zext_ln96_fu_1152_p1[30] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd30;
    end else if (zext_ln96_fu_1152_p1[31] == 1'b1) begin
        val_assign_fu_1156_p3 = 32'd31;
    end else begin
        val_assign_fu_1156_p3 = 32'd32;
    end
end

assign vmprojout1_dataarray_data_V_address0 = sext_ln321_fu_2044_p1;

assign vmprojout1_dataarray_data_V_d0 = ret_V_2_fu_1660_p7;

assign vmprojout2_dataarray_data_V_address0 = sext_ln321_1_fu_1995_p1;

assign vmprojout2_dataarray_data_V_d0 = ret_V_2_fu_1660_p7;

assign vmprojout3_dataarray_data_V_address0 = sext_ln321_2_fu_1946_p1;

assign vmprojout3_dataarray_data_V_d0 = ret_V_2_fu_1660_p7;

assign vmprojout4_dataarray_data_V_address0 = sext_ln321_3_fu_1897_p1;

assign vmprojout4_dataarray_data_V_d0 = ret_V_2_fu_1660_p7;

assign vmprojout5_dataarray_data_V_address0 = sext_ln321_4_fu_1848_p1;

assign vmprojout5_dataarray_data_V_d0 = ret_V_2_fu_1660_p7;

assign vmprojout6_dataarray_data_V_address0 = sext_ln321_5_fu_1799_p1;

assign vmprojout6_dataarray_data_V_d0 = ret_V_2_fu_1660_p7;

assign vmprojout7_dataarray_data_V_address0 = sext_ln321_6_fu_1750_p1;

assign vmprojout7_dataarray_data_V_d0 = ret_V_2_fu_1660_p7;

assign vmprojout8_dataarray_data_V_address0 = sext_ln321_7_fu_1701_p1;

assign vmprojout8_dataarray_data_V_d0 = ret_V_2_fu_1660_p7;

assign xor_ln209_1_fu_1618_p2 = (trunc_ln1503_7_fu_1572_p4 ^ 3'd4);

assign xor_ln209_fu_1604_p2 = (trunc_ln1503_6_fu_1543_p4 ^ 3'd4);

assign zbin1_V_fu_1610_p3 = ((tmp_14_fu_1588_p3[0:0] === 1'b1) ? 3'd0 : xor_ln209_fu_1604_p2);

assign zbin1tmp_V_fu_1552_p2 = (4'd4 + trunc_ln3_reg_2372);

assign zbin2_V_fu_1624_p3 = ((tmp_15_fu_1596_p3[0:0] === 1'b1) ? 3'd7 : xor_ln209_1_fu_1618_p2);

assign zbin2tmp_V_fu_1582_p2 = (4'd4 + trunc_ln1503_1_fu_1562_p4);

assign zext_ln111_fu_1221_p1 = read_imem_V_fu_1164_p1;

assign zext_ln1354_fu_1396_p1 = $unsigned(r_V_fu_1392_p1);

assign zext_ln321_1_fu_896_p1 = tmp_5_fu_888_p3;

assign zext_ln321_fu_868_p1 = tmp_3_fu_860_p3;

assign zext_ln39_fu_968_p1 = p_Val2_s_reg_2233;

assign zext_ln544_fu_876_p1 = trunc_ln209_fu_872_p1;

assign zext_ln63_fu_1175_p1 = tmp_6_fu_1168_p3;

assign zext_ln891_fu_1193_p1 = mem_read_addr_V_fu_1187_p2;

assign zext_ln895_fu_985_p1 = p_Val2_9_fu_978_p3;

assign zext_ln96_fu_1152_p1 = p_Val2_7_fu_310;

always @ (posedge ap_clk) begin
    zext_ln321_reg_2080[6:0] <= 7'b0000000;
    zext_ln321_reg_2080[11:10] <= 2'b00;
    zext_ln321_1_reg_2090[6:0] <= 7'b0000000;
    zext_ln321_1_reg_2090[9:8] <= 2'b00;
    zext_ln1354_reg_2362[12] <= 1'b0;
    bx_o_V_1_state[1:0] <= 2'b00;
end

endmodule //ProjectionRouterTop
