-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MatchEngine_3_0_3_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    bx_V : IN STD_LOGIC_VECTOR (2 downto 0);
    inputStubData_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    inputStubData_dataarray_data_V_ce0 : OUT STD_LOGIC;
    inputStubData_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (12 downto 0);
    inputStubData_0_0_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_0_1_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_0_2_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_0_3_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_0_4_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_0_5_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_0_6_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_0_7_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_1_0_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_1_1_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_1_2_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_1_3_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_1_4_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_1_5_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_1_6_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_1_7_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_2_0_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_2_1_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_2_2_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_2_3_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_2_4_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_2_5_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_2_6_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_2_7_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_3_0_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_3_1_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_3_2_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_3_3_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_3_4_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_3_5_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_3_6_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputStubData_3_7_nentries_V_read : IN STD_LOGIC_VECTOR (4 downto 0);
    inputProjectionData_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    inputProjectionData_dataarray_data_V_ce0 : OUT STD_LOGIC;
    inputProjectionData_dataarray_data_V_q0 : IN STD_LOGIC_VECTOR (20 downto 0);
    inputProjectionData_0_nentries_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
    inputProjectionData_1_nentries_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
    outputCandidateMatch_dataarray_data_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    outputCandidateMatch_dataarray_data_V_ce0 : OUT STD_LOGIC;
    outputCandidateMatch_dataarray_data_V_we0 : OUT STD_LOGIC;
    outputCandidateMatch_dataarray_data_V_d0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of MatchEngine_3_0_3_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv7_6C : STD_LOGIC_VECTOR (6 downto 0) := "1101100";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv55_0 : STD_LOGIC_VECTOR (54 downto 0) := "0000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv32_81 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal table1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal table1_ce0 : STD_LOGIC;
    signal table1_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal head_writeindex_tmp_V_reg_534 : STD_LOGIC_VECTOR (2 downto 0);
    signal iprojectiontmp_V_reg_546 : STD_LOGIC_VECTOR (6 downto 0);
    signal t_V_3_reg_558 : STD_LOGIC_VECTOR (6 downto 0);
    signal moreProjectionsAvailable_0_reg_569 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln209_fu_595_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln209_reg_2438 : STD_LOGIC_VECTOR (0 downto 0);
    signal nproj_V_fu_599_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal nproj_V_reg_2445 : STD_LOGIC_VECTOR (7 downto 0);
    signal moreProjectionsAvailable_fu_607_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln209_1_fu_613_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln209_1_reg_2455 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln79_fu_625_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln79_reg_2462 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln887_fu_644_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln887_reg_2467 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln887_reg_2467_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln887_reg_2467_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal istep_V_fu_650_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal t_V_2_reg_2481 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln98_fu_707_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln98_reg_2488 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln98_reg_2488_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal projectiondatatmp_data_V_reg_2501 : STD_LOGIC_VECTOR (20 downto 0);
    signal zbinfirst_V_fu_728_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal zbinfirst_V_reg_2507 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_738_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_2512 : STD_LOGIC_VECTOR (0 downto 0);
    signal zbinlast_V_fu_750_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal zbinlast_V_reg_2517 : STD_LOGIC_VECTOR (2 downto 0);
    signal nstubfirst_V_fu_767_p34 : STD_LOGIC_VECTOR (4 downto 0);
    signal nstubfirst_V_reg_2522 : STD_LOGIC_VECTOR (4 downto 0);
    signal nstublast_V_fu_816_p34 : STD_LOGIC_VECTOR (4 downto 0);
    signal nstublast_V_reg_2527 : STD_LOGIC_VECTOR (4 downto 0);
    signal savefirst_fu_854_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal savefirst_reg_2533 : STD_LOGIC_VECTOR (0 downto 0);
    signal iprojection_V_1_fu_860_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal moreProjectionsAvailable_2_fu_868_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal moreProjectionsAvailable_2_reg_2551 : STD_LOGIC_VECTOR (0 downto 0);
    signal projectionBuffer_7_V_40_load_reg_2556 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_50_load_reg_2561 : STD_LOGIC_VECTOR (29 downto 0);
    signal bufferNotEmpty_fu_921_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bufferNotEmpty_reg_2566 : STD_LOGIC_VECTOR (0 downto 0);
    signal bufferNotEmpty_reg_2566_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal projectionBuffer_7_V_181_fu_1663_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_181_reg_2570 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_182_fu_1671_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_182_reg_2575 : STD_LOGIC_VECTOR (29 downto 0);
    signal head_writeindex_V_1_fu_1779_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal trunc_ln681_fu_1819_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln681_reg_2585 : STD_LOGIC_VECTOR (0 downto 0);
    signal projindex_V_reg_2590 : STD_LOGIC_VECTOR (6 downto 0);
    signal projindex_V_reg_2590_pp0_iter3_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal projfinez_V_reg_2595 : STD_LOGIC_VECTOR (3 downto 0);
    signal projrinv_V_reg_2601 : STD_LOGIC_VECTOR (4 downto 0);
    signal isPSseed_reg_2606 : STD_LOGIC_VECTOR (0 downto 0);
    signal stubindex_V_reg_2619 : STD_LOGIC_VECTOR (6 downto 0);
    signal pass_fu_2043_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal pass_reg_2624 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_phi_mux_head_writeindex_tmp_V_phi_fu_538_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_mux_iprojectiontmp_V_phi_fu_550_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_phi_mux_moreProjectionsAvailable_0_phi_fu_572_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln66_fu_663_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_7_fu_1922_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln560_fu_2057_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln321_fu_2087_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln87_fu_2072_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal projectionBuffer_7_V_1_fu_220 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_196_fu_1772_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_37_fu_224 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_195_fu_1765_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_33_fu_228 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_194_fu_1758_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_28_fu_232 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_193_fu_1751_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_22_fu_236 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_192_fu_1744_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_15_fu_240 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_191_fu_1737_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_40_fu_244 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_190_fu_1939_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_sig_allocacmp_projectionBuffer_7_V_40_load : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_50_fu_248 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_189_fu_1934_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_sig_allocacmp_projectionBuffer_7_V_50_load : STD_LOGIC_VECTOR (29 downto 0);
    signal outputCandidateMatch_1_nentries_V_write_assign_fu_252 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln321_1_fu_2109_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal outputCandidateMatch_0_nentries_V_write_assign_fu_256 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln321_fu_2102_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal addr_index_assign_fu_260 : STD_LOGIC_VECTOR (31 downto 0);
    signal ncmatch_fu_2129_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tail_readindex_V_fu_264 : STD_LOGIC_VECTOR (2 downto 0);
    signal tail_readindex_V_1_fu_1901_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln891_fu_1895_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_allocacmp_t_V_2 : STD_LOGIC_VECTOR (2 downto 0);
    signal istub_V_fu_268 : STD_LOGIC_VECTOR (3 downto 0);
    signal istub_V_1_fu_1911_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_617_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_656_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal head_writeindexplus_V_fu_671_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal head_writeindexplusplus_V_fu_677_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal phitmp_fu_689_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln98_fu_695_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln98_1_fu_701_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln883_fu_683_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal iprojection_V_fu_713_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln887_fu_719_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln209_1_fu_746_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_756_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal nstubfirst_V_fu_767_p33 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_805_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal nstublast_V_fu_816_p33 : STD_LOGIC_VECTOR (5 downto 0);
    signal moreProjectionsAvailable_1_fu_723_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln113_fu_926_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln321_fu_945_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_936_p5 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln321_1_fu_959_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal projectionBuffer_7_V_fu_951_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln321_2_fu_973_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal projectionBuffer_7_V_103_fu_965_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln321_3_fu_987_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal projectionBuffer_7_V_104_fu_979_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln321_4_fu_1001_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal projectionBuffer_7_V_105_fu_993_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln321_5_fu_1015_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal projectionBuffer_7_V_106_fu_1007_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln321_6_fu_1029_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal projectionBuffer_7_V_107_fu_1021_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_109_fu_1043_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_110_fu_1051_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_111_fu_1059_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_112_fu_1067_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_113_fu_1075_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_114_fu_1083_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_116_fu_1099_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_117_fu_1107_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_118_fu_1115_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_119_fu_1123_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_120_fu_1131_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_122_fu_1147_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_123_fu_1155_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_124_fu_1163_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_125_fu_1171_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_127_fu_1187_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_128_fu_1195_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_129_fu_1203_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_131_fu_1219_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_132_fu_1227_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_134_fu_1243_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_108_fu_1035_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_115_fu_1091_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_121_fu_1139_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_126_fu_1179_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_130_fu_1211_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_133_fu_1235_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_135_fu_1251_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_136_fu_1259_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal zext_ln209_fu_1323_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal head_writeindex_tmp_last_V_fu_1326_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln321_7_fu_1341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal projectionBuffer_7_V_137_fu_1267_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_Result_1_fu_1332_p5 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln321_8_fu_1355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal projectionBuffer_7_V_146_fu_1347_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln321_9_fu_1369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal projectionBuffer_7_V_147_fu_1361_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln321_10_fu_1383_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal projectionBuffer_7_V_148_fu_1375_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln321_11_fu_1397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal projectionBuffer_7_V_149_fu_1389_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln321_12_fu_1411_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal projectionBuffer_7_V_150_fu_1403_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln321_13_fu_1425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal projectionBuffer_7_V_151_fu_1417_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_138_fu_1274_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_153_fu_1439_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_154_fu_1447_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_155_fu_1455_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_156_fu_1463_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_157_fu_1471_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_158_fu_1479_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_139_fu_1281_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_160_fu_1495_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_161_fu_1503_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_162_fu_1511_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_163_fu_1519_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_164_fu_1527_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_140_fu_1288_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_166_fu_1543_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_167_fu_1551_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_168_fu_1559_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_169_fu_1567_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_141_fu_1295_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_171_fu_1583_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_172_fu_1591_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_173_fu_1599_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_142_fu_1302_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_175_fu_1615_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_176_fu_1623_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_143_fu_1309_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_178_fu_1639_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_144_fu_1316_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal savelast_fu_931_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal projectionBuffer_7_V_152_fu_1431_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_159_fu_1487_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_165_fu_1535_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_170_fu_1575_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_174_fu_1607_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_177_fu_1631_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_179_fu_1647_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_180_fu_1655_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal zext_ln209_2_fu_1727_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal projectionBuffer_7_V_183_fu_1679_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_184_fu_1687_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_185_fu_1695_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_186_fu_1703_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_187_fu_1711_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal projectionBuffer_7_V_188_fu_1719_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal head_writeindex_V_fu_1731_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal qdata_V_fu_900_p10 : STD_LOGIC_VECTOR (29 downto 0);
    signal zext_ln215_fu_1881_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal nstubs_V_fu_1823_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ret_V_fu_1885_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln891_fu_1891_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zbin_V_fu_1833_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal projfinezadj_V_1_fu_1981_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln68_fu_1986_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal projfinezadj_V_fu_1978_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal stubfinez_V_fu_1964_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln68_fu_1997_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal projfinezadj_V_2_fu_1990_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal idz_V_fu_2001_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln891_1_fu_2007_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln899_fu_2013_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_2_fu_2025_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln899_1_fu_2031_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln175_fu_2019_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln175_1_fu_2037_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal stubbend_V_fu_1968_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_2_fu_2050_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln321_fu_2078_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln321_fu_2082_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln89_fu_2092_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln301_fu_2096_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component SuperMatchEngineTop_mux_326_5_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        din17_WIDTH : INTEGER;
        din18_WIDTH : INTEGER;
        din19_WIDTH : INTEGER;
        din20_WIDTH : INTEGER;
        din21_WIDTH : INTEGER;
        din22_WIDTH : INTEGER;
        din23_WIDTH : INTEGER;
        din24_WIDTH : INTEGER;
        din25_WIDTH : INTEGER;
        din26_WIDTH : INTEGER;
        din27_WIDTH : INTEGER;
        din28_WIDTH : INTEGER;
        din29_WIDTH : INTEGER;
        din30_WIDTH : INTEGER;
        din31_WIDTH : INTEGER;
        din32_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (4 downto 0);
        din3 : IN STD_LOGIC_VECTOR (4 downto 0);
        din4 : IN STD_LOGIC_VECTOR (4 downto 0);
        din5 : IN STD_LOGIC_VECTOR (4 downto 0);
        din6 : IN STD_LOGIC_VECTOR (4 downto 0);
        din7 : IN STD_LOGIC_VECTOR (4 downto 0);
        din8 : IN STD_LOGIC_VECTOR (4 downto 0);
        din9 : IN STD_LOGIC_VECTOR (4 downto 0);
        din10 : IN STD_LOGIC_VECTOR (4 downto 0);
        din11 : IN STD_LOGIC_VECTOR (4 downto 0);
        din12 : IN STD_LOGIC_VECTOR (4 downto 0);
        din13 : IN STD_LOGIC_VECTOR (4 downto 0);
        din14 : IN STD_LOGIC_VECTOR (4 downto 0);
        din15 : IN STD_LOGIC_VECTOR (4 downto 0);
        din16 : IN STD_LOGIC_VECTOR (4 downto 0);
        din17 : IN STD_LOGIC_VECTOR (4 downto 0);
        din18 : IN STD_LOGIC_VECTOR (4 downto 0);
        din19 : IN STD_LOGIC_VECTOR (4 downto 0);
        din20 : IN STD_LOGIC_VECTOR (4 downto 0);
        din21 : IN STD_LOGIC_VECTOR (4 downto 0);
        din22 : IN STD_LOGIC_VECTOR (4 downto 0);
        din23 : IN STD_LOGIC_VECTOR (4 downto 0);
        din24 : IN STD_LOGIC_VECTOR (4 downto 0);
        din25 : IN STD_LOGIC_VECTOR (4 downto 0);
        din26 : IN STD_LOGIC_VECTOR (4 downto 0);
        din27 : IN STD_LOGIC_VECTOR (4 downto 0);
        din28 : IN STD_LOGIC_VECTOR (4 downto 0);
        din29 : IN STD_LOGIC_VECTOR (4 downto 0);
        din30 : IN STD_LOGIC_VECTOR (4 downto 0);
        din31 : IN STD_LOGIC_VECTOR (4 downto 0);
        din32 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component SuperMatchEngineTop_mux_83_30_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (29 downto 0);
        din1 : IN STD_LOGIC_VECTOR (29 downto 0);
        din2 : IN STD_LOGIC_VECTOR (29 downto 0);
        din3 : IN STD_LOGIC_VECTOR (29 downto 0);
        din4 : IN STD_LOGIC_VECTOR (29 downto 0);
        din5 : IN STD_LOGIC_VECTOR (29 downto 0);
        din6 : IN STD_LOGIC_VECTOR (29 downto 0);
        din7 : IN STD_LOGIC_VECTOR (29 downto 0);
        din8 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component MatchEngine_3_0_3_s_table1 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    table1_U : component MatchEngine_3_0_3_s_table1
    generic map (
        DataWidth => 1,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table1_address0,
        ce0 => table1_ce0,
        q0 => table1_q0);

    SuperMatchEngineTop_mux_326_5_1_1_U1 : component SuperMatchEngineTop_mux_326_5_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 5,
        din2_WIDTH => 5,
        din3_WIDTH => 5,
        din4_WIDTH => 5,
        din5_WIDTH => 5,
        din6_WIDTH => 5,
        din7_WIDTH => 5,
        din8_WIDTH => 5,
        din9_WIDTH => 5,
        din10_WIDTH => 5,
        din11_WIDTH => 5,
        din12_WIDTH => 5,
        din13_WIDTH => 5,
        din14_WIDTH => 5,
        din15_WIDTH => 5,
        din16_WIDTH => 5,
        din17_WIDTH => 5,
        din18_WIDTH => 5,
        din19_WIDTH => 5,
        din20_WIDTH => 5,
        din21_WIDTH => 5,
        din22_WIDTH => 5,
        din23_WIDTH => 5,
        din24_WIDTH => 5,
        din25_WIDTH => 5,
        din26_WIDTH => 5,
        din27_WIDTH => 5,
        din28_WIDTH => 5,
        din29_WIDTH => 5,
        din30_WIDTH => 5,
        din31_WIDTH => 5,
        din32_WIDTH => 6,
        dout_WIDTH => 5)
    port map (
        din0 => inputStubData_0_0_nentries_V_read,
        din1 => inputStubData_0_1_nentries_V_read,
        din2 => inputStubData_0_2_nentries_V_read,
        din3 => inputStubData_0_3_nentries_V_read,
        din4 => inputStubData_0_4_nentries_V_read,
        din5 => inputStubData_0_5_nentries_V_read,
        din6 => inputStubData_0_6_nentries_V_read,
        din7 => inputStubData_0_7_nentries_V_read,
        din8 => inputStubData_1_0_nentries_V_read,
        din9 => inputStubData_1_1_nentries_V_read,
        din10 => inputStubData_1_2_nentries_V_read,
        din11 => inputStubData_1_3_nentries_V_read,
        din12 => inputStubData_1_4_nentries_V_read,
        din13 => inputStubData_1_5_nentries_V_read,
        din14 => inputStubData_1_6_nentries_V_read,
        din15 => inputStubData_1_7_nentries_V_read,
        din16 => inputStubData_2_0_nentries_V_read,
        din17 => inputStubData_2_1_nentries_V_read,
        din18 => inputStubData_2_2_nentries_V_read,
        din19 => inputStubData_2_3_nentries_V_read,
        din20 => inputStubData_2_4_nentries_V_read,
        din21 => inputStubData_2_5_nentries_V_read,
        din22 => inputStubData_2_6_nentries_V_read,
        din23 => inputStubData_2_7_nentries_V_read,
        din24 => inputStubData_3_0_nentries_V_read,
        din25 => inputStubData_3_1_nentries_V_read,
        din26 => inputStubData_3_2_nentries_V_read,
        din27 => inputStubData_3_3_nentries_V_read,
        din28 => inputStubData_3_4_nentries_V_read,
        din29 => inputStubData_3_5_nentries_V_read,
        din30 => inputStubData_3_6_nentries_V_read,
        din31 => inputStubData_3_7_nentries_V_read,
        din32 => nstubfirst_V_fu_767_p33,
        dout => nstubfirst_V_fu_767_p34);

    SuperMatchEngineTop_mux_326_5_1_1_U2 : component SuperMatchEngineTop_mux_326_5_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 5,
        din2_WIDTH => 5,
        din3_WIDTH => 5,
        din4_WIDTH => 5,
        din5_WIDTH => 5,
        din6_WIDTH => 5,
        din7_WIDTH => 5,
        din8_WIDTH => 5,
        din9_WIDTH => 5,
        din10_WIDTH => 5,
        din11_WIDTH => 5,
        din12_WIDTH => 5,
        din13_WIDTH => 5,
        din14_WIDTH => 5,
        din15_WIDTH => 5,
        din16_WIDTH => 5,
        din17_WIDTH => 5,
        din18_WIDTH => 5,
        din19_WIDTH => 5,
        din20_WIDTH => 5,
        din21_WIDTH => 5,
        din22_WIDTH => 5,
        din23_WIDTH => 5,
        din24_WIDTH => 5,
        din25_WIDTH => 5,
        din26_WIDTH => 5,
        din27_WIDTH => 5,
        din28_WIDTH => 5,
        din29_WIDTH => 5,
        din30_WIDTH => 5,
        din31_WIDTH => 5,
        din32_WIDTH => 6,
        dout_WIDTH => 5)
    port map (
        din0 => inputStubData_0_0_nentries_V_read,
        din1 => inputStubData_0_1_nentries_V_read,
        din2 => inputStubData_0_2_nentries_V_read,
        din3 => inputStubData_0_3_nentries_V_read,
        din4 => inputStubData_0_4_nentries_V_read,
        din5 => inputStubData_0_5_nentries_V_read,
        din6 => inputStubData_0_6_nentries_V_read,
        din7 => inputStubData_0_7_nentries_V_read,
        din8 => inputStubData_1_0_nentries_V_read,
        din9 => inputStubData_1_1_nentries_V_read,
        din10 => inputStubData_1_2_nentries_V_read,
        din11 => inputStubData_1_3_nentries_V_read,
        din12 => inputStubData_1_4_nentries_V_read,
        din13 => inputStubData_1_5_nentries_V_read,
        din14 => inputStubData_1_6_nentries_V_read,
        din15 => inputStubData_1_7_nentries_V_read,
        din16 => inputStubData_2_0_nentries_V_read,
        din17 => inputStubData_2_1_nentries_V_read,
        din18 => inputStubData_2_2_nentries_V_read,
        din19 => inputStubData_2_3_nentries_V_read,
        din20 => inputStubData_2_4_nentries_V_read,
        din21 => inputStubData_2_5_nentries_V_read,
        din22 => inputStubData_2_6_nentries_V_read,
        din23 => inputStubData_2_7_nentries_V_read,
        din24 => inputStubData_3_0_nentries_V_read,
        din25 => inputStubData_3_1_nentries_V_read,
        din26 => inputStubData_3_2_nentries_V_read,
        din27 => inputStubData_3_3_nentries_V_read,
        din28 => inputStubData_3_4_nentries_V_read,
        din29 => inputStubData_3_5_nentries_V_read,
        din30 => inputStubData_3_6_nentries_V_read,
        din31 => inputStubData_3_7_nentries_V_read,
        din32 => nstublast_V_fu_816_p33,
        dout => nstublast_V_fu_816_p34);

    SuperMatchEngineTop_mux_83_30_1_1_U3 : component SuperMatchEngineTop_mux_83_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 30,
        din1_WIDTH => 30,
        din2_WIDTH => 30,
        din3_WIDTH => 30,
        din4_WIDTH => 30,
        din5_WIDTH => 30,
        din6_WIDTH => 30,
        din7_WIDTH => 30,
        din8_WIDTH => 3,
        dout_WIDTH => 30)
    port map (
        din0 => projectionBuffer_7_V_1_fu_220,
        din1 => projectionBuffer_7_V_37_fu_224,
        din2 => projectionBuffer_7_V_33_fu_228,
        din3 => projectionBuffer_7_V_28_fu_232,
        din4 => projectionBuffer_7_V_22_fu_236,
        din5 => projectionBuffer_7_V_15_fu_240,
        din6 => ap_sig_allocacmp_projectionBuffer_7_V_40_load,
        din7 => ap_sig_allocacmp_projectionBuffer_7_V_50_load,
        din8 => t_V_2_reg_2481,
        dout => qdata_V_fu_900_p10);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    addr_index_assign_fu_260_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((table1_q0 = ap_const_lv1_1) and (pass_reg_2624 = ap_const_lv1_1) and (bufferNotEmpty_reg_2566_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                addr_index_assign_fu_260 <= ncmatch_fu_2129_p2;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                addr_index_assign_fu_260 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    head_writeindex_tmp_V_reg_534_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln887_reg_2467_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                head_writeindex_tmp_V_reg_534 <= head_writeindex_V_1_fu_1779_p3;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                head_writeindex_tmp_V_reg_534 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    iprojectiontmp_V_reg_546_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln887_reg_2467 = ap_const_lv1_0))) then 
                iprojectiontmp_V_reg_546 <= iprojection_V_1_fu_860_p3;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                iprojectiontmp_V_reg_546 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    istub_V_fu_268_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln891_fu_1895_p2 = ap_const_lv1_1) and (bufferNotEmpty_fu_921_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                istub_V_fu_268 <= istub_V_1_fu_1911_p2;
            elsif ((((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln891_fu_1895_p2 = ap_const_lv1_0) and (bufferNotEmpty_fu_921_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                istub_V_fu_268 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    moreProjectionsAvailable_0_reg_569_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln887_reg_2467_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                moreProjectionsAvailable_0_reg_569 <= moreProjectionsAvailable_2_reg_2551;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                moreProjectionsAvailable_0_reg_569 <= moreProjectionsAvailable_fu_607_p2;
            end if; 
        end if;
    end process;

    outputCandidateMatch_0_nentries_V_write_assign_fu_256_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((table1_q0 = ap_const_lv1_1) and (icmp_ln87_fu_2072_p2 = ap_const_lv1_1) and (pass_reg_2624 = ap_const_lv1_1) and (bufferNotEmpty_reg_2566_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                outputCandidateMatch_0_nentries_V_write_assign_fu_256 <= select_ln321_fu_2102_p3;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                outputCandidateMatch_0_nentries_V_write_assign_fu_256 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    outputCandidateMatch_1_nentries_V_write_assign_fu_252_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((table1_q0 = ap_const_lv1_1) and (icmp_ln87_fu_2072_p2 = ap_const_lv1_1) and (pass_reg_2624 = ap_const_lv1_1) and (bufferNotEmpty_reg_2566_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                outputCandidateMatch_1_nentries_V_write_assign_fu_252 <= select_ln321_1_fu_2109_p3;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                outputCandidateMatch_1_nentries_V_write_assign_fu_252 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    t_V_3_reg_558_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln887_fu_644_p2 = ap_const_lv1_0))) then 
                t_V_3_reg_558 <= istep_V_fu_650_p2;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                t_V_3_reg_558 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    tail_readindex_V_fu_264_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln891_fu_1895_p2 = ap_const_lv1_0) and (bufferNotEmpty_fu_921_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                tail_readindex_V_fu_264 <= tail_readindex_V_1_fu_1901_p2;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                tail_readindex_V_fu_264 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln887_reg_2467_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                bufferNotEmpty_reg_2566 <= bufferNotEmpty_fu_921_p2;
                projectionBuffer_7_V_40_load_reg_2556 <= ap_sig_allocacmp_projectionBuffer_7_V_40_load;
                projectionBuffer_7_V_50_load_reg_2561 <= ap_sig_allocacmp_projectionBuffer_7_V_50_load;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                bufferNotEmpty_reg_2566_pp0_iter3_reg <= bufferNotEmpty_reg_2566;
                icmp_ln887_reg_2467_pp0_iter2_reg <= icmp_ln887_reg_2467_pp0_iter1_reg;
                or_ln98_reg_2488_pp0_iter2_reg <= or_ln98_reg_2488;
                projindex_V_reg_2590_pp0_iter3_reg <= projindex_V_reg_2590;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln887_reg_2467 <= icmp_ln887_fu_644_p2;
                icmp_ln887_reg_2467_pp0_iter1_reg <= icmp_ln887_reg_2467;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((bufferNotEmpty_fu_921_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                isPSseed_reg_2606 <= qdata_V_fu_900_p10(4 downto 4);
                projfinez_V_reg_2595 <= qdata_V_fu_900_p10(13 downto 10);
                projindex_V_reg_2590 <= qdata_V_fu_900_p10(24 downto 18);
                projrinv_V_reg_2601 <= qdata_V_fu_900_p10(9 downto 5);
                trunc_ln681_reg_2585 <= trunc_ln681_fu_1819_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln887_reg_2467 = ap_const_lv1_0))) then
                moreProjectionsAvailable_2_reg_2551 <= moreProjectionsAvailable_2_fu_868_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                nproj_V_reg_2445 <= nproj_V_fu_599_p3;
                trunc_ln209_1_reg_2455 <= trunc_ln209_1_fu_613_p1;
                trunc_ln209_reg_2438 <= trunc_ln209_fu_595_p1;
                    zext_ln79_reg_2462(7) <= zext_ln79_fu_625_p1(7);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln887_reg_2467 = ap_const_lv1_0))) then
                nstubfirst_V_reg_2522 <= nstubfirst_V_fu_767_p34;
                nstublast_V_reg_2527 <= nstublast_V_fu_816_p34;
                or_ln98_reg_2488 <= or_ln98_fu_707_p2;
                projectiondatatmp_data_V_reg_2501 <= inputProjectionData_dataarray_data_V_q0;
                savefirst_reg_2533 <= savefirst_fu_854_p2;
                t_V_2_reg_2481 <= ap_sig_allocacmp_t_V_2;
                tmp_3_reg_2512 <= inputProjectionData_dataarray_data_V_q0(10 downto 10);
                zbinfirst_V_reg_2507 <= inputProjectionData_dataarray_data_V_q0(13 downto 11);
                zbinlast_V_reg_2517 <= zbinlast_V_fu_750_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((bufferNotEmpty_reg_2566 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                pass_reg_2624 <= pass_fu_2043_p3;
                stubindex_V_reg_2619 <= inputStubData_dataarray_data_V_q0(12 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln887_reg_2467_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                projectionBuffer_7_V_15_fu_240 <= projectionBuffer_7_V_191_fu_1737_p3;
                projectionBuffer_7_V_1_fu_220 <= projectionBuffer_7_V_196_fu_1772_p3;
                projectionBuffer_7_V_22_fu_236 <= projectionBuffer_7_V_192_fu_1744_p3;
                projectionBuffer_7_V_28_fu_232 <= projectionBuffer_7_V_193_fu_1751_p3;
                projectionBuffer_7_V_33_fu_228 <= projectionBuffer_7_V_194_fu_1758_p3;
                projectionBuffer_7_V_37_fu_224 <= projectionBuffer_7_V_195_fu_1765_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_ln98_reg_2488 = ap_const_lv1_0) and (icmp_ln887_reg_2467_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                projectionBuffer_7_V_181_reg_2570 <= projectionBuffer_7_V_181_fu_1663_p3;
                projectionBuffer_7_V_182_reg_2575 <= projectionBuffer_7_V_182_fu_1671_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln887_reg_2467_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                projectionBuffer_7_V_40_fu_244 <= projectionBuffer_7_V_190_fu_1939_p3;
                projectionBuffer_7_V_50_fu_248 <= projectionBuffer_7_V_189_fu_1934_p3;
            end if;
        end if;
    end process;
    zext_ln79_reg_2462(6 downto 0) <= "0000000";
    zext_ln79_reg_2462(9 downto 8) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln887_fu_644_p2, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln887_fu_644_p2 = ap_const_lv1_1))) and not(((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln887_fu_644_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln301_fu_2096_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(trunc_ln89_fu_2092_p1));
    add_ln321_fu_2082_p2 <= std_logic_vector(unsigned(trunc_ln321_fu_2078_p1) + unsigned(zext_ln79_reg_2462));
    and_ln175_1_fu_2037_p2 <= (icmp_ln899_1_fu_2031_p2 and icmp_ln891_2_fu_2025_p2);
    and_ln175_fu_2019_p2 <= (icmp_ln899_fu_2013_p2 and icmp_ln891_1_fu_2007_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state7 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln887_fu_644_p2)
    begin
        if ((icmp_ln887_fu_644_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_head_writeindex_tmp_V_phi_fu_538_p4_assign_proc : process(head_writeindex_tmp_V_reg_534, icmp_ln887_reg_2467_pp0_iter1_reg, head_writeindex_V_1_fu_1779_p3, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln887_reg_2467_pp0_iter1_reg = ap_const_lv1_0))) then 
            ap_phi_mux_head_writeindex_tmp_V_phi_fu_538_p4 <= head_writeindex_V_1_fu_1779_p3;
        else 
            ap_phi_mux_head_writeindex_tmp_V_phi_fu_538_p4 <= head_writeindex_tmp_V_reg_534;
        end if; 
    end process;


    ap_phi_mux_iprojectiontmp_V_phi_fu_550_p4_assign_proc : process(iprojectiontmp_V_reg_546, icmp_ln887_reg_2467, ap_CS_fsm_pp0_stage0, iprojection_V_1_fu_860_p3, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln887_reg_2467 = ap_const_lv1_0))) then 
            ap_phi_mux_iprojectiontmp_V_phi_fu_550_p4 <= iprojection_V_1_fu_860_p3;
        else 
            ap_phi_mux_iprojectiontmp_V_phi_fu_550_p4 <= iprojectiontmp_V_reg_546;
        end if; 
    end process;


    ap_phi_mux_moreProjectionsAvailable_0_phi_fu_572_p4_assign_proc : process(moreProjectionsAvailable_0_reg_569, icmp_ln887_reg_2467_pp0_iter1_reg, moreProjectionsAvailable_2_reg_2551, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln887_reg_2467_pp0_iter1_reg = ap_const_lv1_0))) then 
            ap_phi_mux_moreProjectionsAvailable_0_phi_fu_572_p4 <= moreProjectionsAvailable_2_reg_2551;
        else 
            ap_phi_mux_moreProjectionsAvailable_0_phi_fu_572_p4 <= moreProjectionsAvailable_0_reg_569;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= bx_V;
    ap_return_1 <= outputCandidateMatch_0_nentries_V_write_assign_fu_256;
    ap_return_2 <= outputCandidateMatch_1_nentries_V_write_assign_fu_252;

    ap_sig_allocacmp_projectionBuffer_7_V_40_load_assign_proc : process(icmp_ln887_reg_2467_pp0_iter2_reg, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, projectionBuffer_7_V_40_fu_244, projectionBuffer_7_V_190_fu_1939_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln887_reg_2467_pp0_iter2_reg = ap_const_lv1_0))) then 
            ap_sig_allocacmp_projectionBuffer_7_V_40_load <= projectionBuffer_7_V_190_fu_1939_p3;
        else 
            ap_sig_allocacmp_projectionBuffer_7_V_40_load <= projectionBuffer_7_V_40_fu_244;
        end if; 
    end process;


    ap_sig_allocacmp_projectionBuffer_7_V_50_load_assign_proc : process(icmp_ln887_reg_2467_pp0_iter2_reg, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, projectionBuffer_7_V_50_fu_248, projectionBuffer_7_V_189_fu_1934_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln887_reg_2467_pp0_iter2_reg = ap_const_lv1_0))) then 
            ap_sig_allocacmp_projectionBuffer_7_V_50_load <= projectionBuffer_7_V_189_fu_1934_p3;
        else 
            ap_sig_allocacmp_projectionBuffer_7_V_50_load <= projectionBuffer_7_V_50_fu_248;
        end if; 
    end process;


    ap_sig_allocacmp_t_V_2_assign_proc : process(bufferNotEmpty_fu_921_p2, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, tail_readindex_V_fu_264, tail_readindex_V_1_fu_1901_p2, icmp_ln891_fu_1895_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln891_fu_1895_p2 = ap_const_lv1_0) and (bufferNotEmpty_fu_921_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_sig_allocacmp_t_V_2 <= tail_readindex_V_1_fu_1901_p2;
        else 
            ap_sig_allocacmp_t_V_2 <= tail_readindex_V_fu_264;
        end if; 
    end process;

    bufferNotEmpty_fu_921_p2 <= "1" when (head_writeindex_tmp_V_reg_534 = t_V_2_reg_2481) else "0";
    head_writeindex_V_1_fu_1779_p3 <= 
        head_writeindex_tmp_V_reg_534 when (or_ln98_reg_2488(0) = '1') else 
        head_writeindex_V_fu_1731_p2;
    head_writeindex_V_fu_1731_p2 <= std_logic_vector(unsigned(head_writeindex_tmp_last_V_fu_1326_p2) + unsigned(zext_ln209_2_fu_1727_p1));
    head_writeindex_tmp_last_V_fu_1326_p2 <= std_logic_vector(unsigned(head_writeindex_tmp_V_reg_534) + unsigned(zext_ln209_fu_1323_p1));
    head_writeindexplus_V_fu_671_p2 <= std_logic_vector(unsigned(ap_phi_mux_head_writeindex_tmp_V_phi_fu_538_p4) + unsigned(ap_const_lv3_1));
    head_writeindexplusplus_V_fu_677_p2 <= std_logic_vector(unsigned(ap_phi_mux_head_writeindex_tmp_V_phi_fu_538_p4) + unsigned(ap_const_lv3_2));
    icmp_ln113_fu_926_p2 <= "0" when (nstublast_V_reg_2527 = ap_const_lv5_0) else "1";
    icmp_ln321_10_fu_1383_p2 <= "1" when (head_writeindex_tmp_last_V_fu_1326_p2 = ap_const_lv3_3) else "0";
    icmp_ln321_11_fu_1397_p2 <= "1" when (head_writeindex_tmp_last_V_fu_1326_p2 = ap_const_lv3_2) else "0";
    icmp_ln321_12_fu_1411_p2 <= "1" when (head_writeindex_tmp_last_V_fu_1326_p2 = ap_const_lv3_1) else "0";
    icmp_ln321_13_fu_1425_p2 <= "1" when (head_writeindex_tmp_last_V_fu_1326_p2 = ap_const_lv3_0) else "0";
    icmp_ln321_1_fu_959_p2 <= "1" when (head_writeindex_tmp_V_reg_534 = ap_const_lv3_5) else "0";
    icmp_ln321_2_fu_973_p2 <= "1" when (head_writeindex_tmp_V_reg_534 = ap_const_lv3_4) else "0";
    icmp_ln321_3_fu_987_p2 <= "1" when (head_writeindex_tmp_V_reg_534 = ap_const_lv3_3) else "0";
    icmp_ln321_4_fu_1001_p2 <= "1" when (head_writeindex_tmp_V_reg_534 = ap_const_lv3_2) else "0";
    icmp_ln321_5_fu_1015_p2 <= "1" when (head_writeindex_tmp_V_reg_534 = ap_const_lv3_1) else "0";
    icmp_ln321_6_fu_1029_p2 <= "1" when (head_writeindex_tmp_V_reg_534 = ap_const_lv3_0) else "0";
    icmp_ln321_7_fu_1341_p2 <= "1" when (head_writeindex_tmp_last_V_fu_1326_p2 = ap_const_lv3_6) else "0";
    icmp_ln321_8_fu_1355_p2 <= "1" when (head_writeindex_tmp_last_V_fu_1326_p2 = ap_const_lv3_5) else "0";
    icmp_ln321_9_fu_1369_p2 <= "1" when (head_writeindex_tmp_last_V_fu_1326_p2 = ap_const_lv3_4) else "0";
    icmp_ln321_fu_945_p2 <= "1" when (head_writeindex_tmp_V_reg_534 = ap_const_lv3_6) else "0";
    icmp_ln87_fu_2072_p2 <= "1" when (signed(addr_index_assign_fu_260) < signed(ap_const_lv32_81)) else "0";
    icmp_ln883_fu_683_p2 <= "1" when (head_writeindexplus_V_fu_671_p2 = ap_sig_allocacmp_t_V_2) else "0";
    icmp_ln887_fu_644_p2 <= "1" when (t_V_3_reg_558 = ap_const_lv7_6C) else "0";
    icmp_ln891_1_fu_2007_p2 <= "1" when (signed(idz_V_fu_2001_p2) > signed(ap_const_lv5_1D)) else "0";
    icmp_ln891_2_fu_2025_p2 <= "1" when (signed(idz_V_fu_2001_p2) > signed(ap_const_lv5_1A)) else "0";
    icmp_ln891_fu_1895_p2 <= "1" when (unsigned(ret_V_fu_1885_p2) < unsigned(zext_ln891_fu_1891_p1)) else "0";
    icmp_ln899_1_fu_2031_p2 <= "1" when (signed(idz_V_fu_2001_p2) < signed(ap_const_lv5_6)) else "0";
    icmp_ln899_fu_2013_p2 <= "1" when (signed(idz_V_fu_2001_p2) < signed(ap_const_lv5_3)) else "0";
    idz_V_fu_2001_p2 <= std_logic_vector(unsigned(zext_ln68_fu_1997_p1) - unsigned(projfinezadj_V_2_fu_1990_p3));
    inputProjectionData_dataarray_data_V_address0 <= zext_ln66_fu_663_p1(8 - 1 downto 0);

    inputProjectionData_dataarray_data_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputProjectionData_dataarray_data_V_ce0 <= ap_const_logic_1;
        else 
            inputProjectionData_dataarray_data_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    inputStubData_dataarray_data_V_address0 <= tmp_7_fu_1922_p5(9 - 1 downto 0);

    inputStubData_dataarray_data_V_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputStubData_dataarray_data_V_ce0 <= ap_const_logic_1;
        else 
            inputStubData_dataarray_data_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    iprojection_V_1_fu_860_p3 <= 
        iprojectiontmp_V_reg_546 when (or_ln98_fu_707_p2(0) = '1') else 
        iprojection_V_fu_713_p2;
    iprojection_V_fu_713_p2 <= std_logic_vector(unsigned(iprojectiontmp_V_reg_546) + unsigned(ap_const_lv7_1));
    istep_V_fu_650_p2 <= std_logic_vector(unsigned(t_V_3_reg_558) + unsigned(ap_const_lv7_1));
    istub_V_1_fu_1911_p2 <= std_logic_vector(unsigned(istub_V_fu_268) + unsigned(ap_const_lv4_1));
    moreProjectionsAvailable_1_fu_723_p2 <= "1" when (unsigned(zext_ln887_fu_719_p1) < unsigned(nproj_V_reg_2445)) else "0";
    moreProjectionsAvailable_2_fu_868_p3 <= 
        ap_phi_mux_moreProjectionsAvailable_0_phi_fu_572_p4 when (or_ln98_fu_707_p2(0) = '1') else 
        moreProjectionsAvailable_1_fu_723_p2;
    moreProjectionsAvailable_fu_607_p2 <= "0" when (nproj_V_fu_599_p3 = ap_const_lv8_0) else "1";
    ncmatch_fu_2129_p2 <= std_logic_vector(unsigned(addr_index_assign_fu_260) + unsigned(ap_const_lv32_1));
    nproj_V_fu_599_p3 <= 
        inputProjectionData_1_nentries_V_read when (trunc_ln209_fu_595_p1(0) = '1') else 
        inputProjectionData_0_nentries_V_read;
    nstubfirst_V_fu_767_p33 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_756_p3),6));
    nstublast_V_fu_816_p33 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_805_p3),6));
    nstubs_V_fu_1823_p4 <= qdata_V_fu_900_p10(28 downto 25);
    or_ln98_1_fu_701_p2 <= (xor_ln98_fu_695_p2 or phitmp_fu_689_p2);
    or_ln98_fu_707_p2 <= (or_ln98_1_fu_701_p2 or icmp_ln883_fu_683_p2);
    outputCandidateMatch_dataarray_data_V_address0 <= sext_ln321_fu_2087_p1(8 - 1 downto 0);

    outputCandidateMatch_dataarray_data_V_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            outputCandidateMatch_dataarray_data_V_ce0 <= ap_const_logic_1;
        else 
            outputCandidateMatch_dataarray_data_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    outputCandidateMatch_dataarray_data_V_d0 <= (projindex_V_reg_2590_pp0_iter3_reg & stubindex_V_reg_2619);

    outputCandidateMatch_dataarray_data_V_we0_assign_proc : process(table1_q0, ap_block_pp0_stage0_11001, bufferNotEmpty_reg_2566_pp0_iter3_reg, pass_reg_2624, ap_enable_reg_pp0_iter4, icmp_ln87_fu_2072_p2)
    begin
        if (((table1_q0 = ap_const_lv1_1) and (icmp_ln87_fu_2072_p2 = ap_const_lv1_1) and (pass_reg_2624 = ap_const_lv1_1) and (bufferNotEmpty_reg_2566_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            outputCandidateMatch_dataarray_data_V_we0 <= ap_const_logic_1;
        else 
            outputCandidateMatch_dataarray_data_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_Result_1_fu_1332_p5 <= (((nstublast_V_reg_2527 & projectiondatatmp_data_V_reg_2501) & zbinlast_V_reg_2517) & ap_const_lv1_1);
    p_Result_2_fu_2050_p3 <= (projrinv_V_reg_2601 & stubbend_V_fu_1968_p4);
    p_Result_s_fu_936_p5 <= (((nstubfirst_V_reg_2522 & projectiondatatmp_data_V_reg_2501) & zbinfirst_V_reg_2507) & ap_const_lv1_0);
    pass_fu_2043_p3 <= 
        and_ln175_fu_2019_p2 when (isPSseed_reg_2606(0) = '1') else 
        and_ln175_1_fu_2037_p2;
    phitmp_fu_689_p2 <= "1" when (head_writeindexplusplus_V_fu_677_p2 = ap_sig_allocacmp_t_V_2) else "0";
    projectionBuffer_7_V_103_fu_965_p3 <= 
        ap_sig_allocacmp_projectionBuffer_7_V_50_load when (icmp_ln321_1_fu_959_p2(0) = '1') else 
        projectionBuffer_7_V_fu_951_p3;
    projectionBuffer_7_V_104_fu_979_p3 <= 
        ap_sig_allocacmp_projectionBuffer_7_V_50_load when (icmp_ln321_2_fu_973_p2(0) = '1') else 
        projectionBuffer_7_V_103_fu_965_p3;
    projectionBuffer_7_V_105_fu_993_p3 <= 
        ap_sig_allocacmp_projectionBuffer_7_V_50_load when (icmp_ln321_3_fu_987_p2(0) = '1') else 
        projectionBuffer_7_V_104_fu_979_p3;
    projectionBuffer_7_V_106_fu_1007_p3 <= 
        ap_sig_allocacmp_projectionBuffer_7_V_50_load when (icmp_ln321_4_fu_1001_p2(0) = '1') else 
        projectionBuffer_7_V_105_fu_993_p3;
    projectionBuffer_7_V_107_fu_1021_p3 <= 
        ap_sig_allocacmp_projectionBuffer_7_V_50_load when (icmp_ln321_5_fu_1015_p2(0) = '1') else 
        projectionBuffer_7_V_106_fu_1007_p3;
    projectionBuffer_7_V_108_fu_1035_p3 <= 
        ap_sig_allocacmp_projectionBuffer_7_V_50_load when (icmp_ln321_6_fu_1029_p2(0) = '1') else 
        projectionBuffer_7_V_107_fu_1021_p3;
    projectionBuffer_7_V_109_fu_1043_p3 <= 
        p_Result_s_fu_936_p5 when (icmp_ln321_fu_945_p2(0) = '1') else 
        ap_sig_allocacmp_projectionBuffer_7_V_40_load;
    projectionBuffer_7_V_110_fu_1051_p3 <= 
        ap_sig_allocacmp_projectionBuffer_7_V_40_load when (icmp_ln321_1_fu_959_p2(0) = '1') else 
        projectionBuffer_7_V_109_fu_1043_p3;
    projectionBuffer_7_V_111_fu_1059_p3 <= 
        ap_sig_allocacmp_projectionBuffer_7_V_40_load when (icmp_ln321_2_fu_973_p2(0) = '1') else 
        projectionBuffer_7_V_110_fu_1051_p3;
    projectionBuffer_7_V_112_fu_1067_p3 <= 
        ap_sig_allocacmp_projectionBuffer_7_V_40_load when (icmp_ln321_3_fu_987_p2(0) = '1') else 
        projectionBuffer_7_V_111_fu_1059_p3;
    projectionBuffer_7_V_113_fu_1075_p3 <= 
        ap_sig_allocacmp_projectionBuffer_7_V_40_load when (icmp_ln321_4_fu_1001_p2(0) = '1') else 
        projectionBuffer_7_V_112_fu_1067_p3;
    projectionBuffer_7_V_114_fu_1083_p3 <= 
        ap_sig_allocacmp_projectionBuffer_7_V_40_load when (icmp_ln321_5_fu_1015_p2(0) = '1') else 
        projectionBuffer_7_V_113_fu_1075_p3;
    projectionBuffer_7_V_115_fu_1091_p3 <= 
        ap_sig_allocacmp_projectionBuffer_7_V_40_load when (icmp_ln321_6_fu_1029_p2(0) = '1') else 
        projectionBuffer_7_V_114_fu_1083_p3;
    projectionBuffer_7_V_116_fu_1099_p3 <= 
        p_Result_s_fu_936_p5 when (icmp_ln321_1_fu_959_p2(0) = '1') else 
        projectionBuffer_7_V_15_fu_240;
    projectionBuffer_7_V_117_fu_1107_p3 <= 
        projectionBuffer_7_V_15_fu_240 when (icmp_ln321_2_fu_973_p2(0) = '1') else 
        projectionBuffer_7_V_116_fu_1099_p3;
    projectionBuffer_7_V_118_fu_1115_p3 <= 
        projectionBuffer_7_V_15_fu_240 when (icmp_ln321_3_fu_987_p2(0) = '1') else 
        projectionBuffer_7_V_117_fu_1107_p3;
    projectionBuffer_7_V_119_fu_1123_p3 <= 
        projectionBuffer_7_V_15_fu_240 when (icmp_ln321_4_fu_1001_p2(0) = '1') else 
        projectionBuffer_7_V_118_fu_1115_p3;
    projectionBuffer_7_V_120_fu_1131_p3 <= 
        projectionBuffer_7_V_15_fu_240 when (icmp_ln321_5_fu_1015_p2(0) = '1') else 
        projectionBuffer_7_V_119_fu_1123_p3;
    projectionBuffer_7_V_121_fu_1139_p3 <= 
        projectionBuffer_7_V_15_fu_240 when (icmp_ln321_6_fu_1029_p2(0) = '1') else 
        projectionBuffer_7_V_120_fu_1131_p3;
    projectionBuffer_7_V_122_fu_1147_p3 <= 
        p_Result_s_fu_936_p5 when (icmp_ln321_2_fu_973_p2(0) = '1') else 
        projectionBuffer_7_V_22_fu_236;
    projectionBuffer_7_V_123_fu_1155_p3 <= 
        projectionBuffer_7_V_22_fu_236 when (icmp_ln321_3_fu_987_p2(0) = '1') else 
        projectionBuffer_7_V_122_fu_1147_p3;
    projectionBuffer_7_V_124_fu_1163_p3 <= 
        projectionBuffer_7_V_22_fu_236 when (icmp_ln321_4_fu_1001_p2(0) = '1') else 
        projectionBuffer_7_V_123_fu_1155_p3;
    projectionBuffer_7_V_125_fu_1171_p3 <= 
        projectionBuffer_7_V_22_fu_236 when (icmp_ln321_5_fu_1015_p2(0) = '1') else 
        projectionBuffer_7_V_124_fu_1163_p3;
    projectionBuffer_7_V_126_fu_1179_p3 <= 
        projectionBuffer_7_V_22_fu_236 when (icmp_ln321_6_fu_1029_p2(0) = '1') else 
        projectionBuffer_7_V_125_fu_1171_p3;
    projectionBuffer_7_V_127_fu_1187_p3 <= 
        p_Result_s_fu_936_p5 when (icmp_ln321_3_fu_987_p2(0) = '1') else 
        projectionBuffer_7_V_28_fu_232;
    projectionBuffer_7_V_128_fu_1195_p3 <= 
        projectionBuffer_7_V_28_fu_232 when (icmp_ln321_4_fu_1001_p2(0) = '1') else 
        projectionBuffer_7_V_127_fu_1187_p3;
    projectionBuffer_7_V_129_fu_1203_p3 <= 
        projectionBuffer_7_V_28_fu_232 when (icmp_ln321_5_fu_1015_p2(0) = '1') else 
        projectionBuffer_7_V_128_fu_1195_p3;
    projectionBuffer_7_V_130_fu_1211_p3 <= 
        projectionBuffer_7_V_28_fu_232 when (icmp_ln321_6_fu_1029_p2(0) = '1') else 
        projectionBuffer_7_V_129_fu_1203_p3;
    projectionBuffer_7_V_131_fu_1219_p3 <= 
        p_Result_s_fu_936_p5 when (icmp_ln321_4_fu_1001_p2(0) = '1') else 
        projectionBuffer_7_V_33_fu_228;
    projectionBuffer_7_V_132_fu_1227_p3 <= 
        projectionBuffer_7_V_33_fu_228 when (icmp_ln321_5_fu_1015_p2(0) = '1') else 
        projectionBuffer_7_V_131_fu_1219_p3;
    projectionBuffer_7_V_133_fu_1235_p3 <= 
        projectionBuffer_7_V_33_fu_228 when (icmp_ln321_6_fu_1029_p2(0) = '1') else 
        projectionBuffer_7_V_132_fu_1227_p3;
    projectionBuffer_7_V_134_fu_1243_p3 <= 
        p_Result_s_fu_936_p5 when (icmp_ln321_5_fu_1015_p2(0) = '1') else 
        projectionBuffer_7_V_37_fu_224;
    projectionBuffer_7_V_135_fu_1251_p3 <= 
        projectionBuffer_7_V_37_fu_224 when (icmp_ln321_6_fu_1029_p2(0) = '1') else 
        projectionBuffer_7_V_134_fu_1243_p3;
    projectionBuffer_7_V_136_fu_1259_p3 <= 
        p_Result_s_fu_936_p5 when (icmp_ln321_6_fu_1029_p2(0) = '1') else 
        projectionBuffer_7_V_1_fu_220;
    projectionBuffer_7_V_137_fu_1267_p3 <= 
        projectionBuffer_7_V_108_fu_1035_p3 when (savefirst_reg_2533(0) = '1') else 
        ap_sig_allocacmp_projectionBuffer_7_V_50_load;
    projectionBuffer_7_V_138_fu_1274_p3 <= 
        projectionBuffer_7_V_115_fu_1091_p3 when (savefirst_reg_2533(0) = '1') else 
        ap_sig_allocacmp_projectionBuffer_7_V_40_load;
    projectionBuffer_7_V_139_fu_1281_p3 <= 
        projectionBuffer_7_V_121_fu_1139_p3 when (savefirst_reg_2533(0) = '1') else 
        projectionBuffer_7_V_15_fu_240;
    projectionBuffer_7_V_140_fu_1288_p3 <= 
        projectionBuffer_7_V_126_fu_1179_p3 when (savefirst_reg_2533(0) = '1') else 
        projectionBuffer_7_V_22_fu_236;
    projectionBuffer_7_V_141_fu_1295_p3 <= 
        projectionBuffer_7_V_130_fu_1211_p3 when (savefirst_reg_2533(0) = '1') else 
        projectionBuffer_7_V_28_fu_232;
    projectionBuffer_7_V_142_fu_1302_p3 <= 
        projectionBuffer_7_V_133_fu_1235_p3 when (savefirst_reg_2533(0) = '1') else 
        projectionBuffer_7_V_33_fu_228;
    projectionBuffer_7_V_143_fu_1309_p3 <= 
        projectionBuffer_7_V_135_fu_1251_p3 when (savefirst_reg_2533(0) = '1') else 
        projectionBuffer_7_V_37_fu_224;
    projectionBuffer_7_V_144_fu_1316_p3 <= 
        projectionBuffer_7_V_136_fu_1259_p3 when (savefirst_reg_2533(0) = '1') else 
        projectionBuffer_7_V_1_fu_220;
    projectionBuffer_7_V_146_fu_1347_p3 <= 
        projectionBuffer_7_V_137_fu_1267_p3 when (icmp_ln321_7_fu_1341_p2(0) = '1') else 
        p_Result_1_fu_1332_p5;
    projectionBuffer_7_V_147_fu_1361_p3 <= 
        projectionBuffer_7_V_137_fu_1267_p3 when (icmp_ln321_8_fu_1355_p2(0) = '1') else 
        projectionBuffer_7_V_146_fu_1347_p3;
    projectionBuffer_7_V_148_fu_1375_p3 <= 
        projectionBuffer_7_V_137_fu_1267_p3 when (icmp_ln321_9_fu_1369_p2(0) = '1') else 
        projectionBuffer_7_V_147_fu_1361_p3;
    projectionBuffer_7_V_149_fu_1389_p3 <= 
        projectionBuffer_7_V_137_fu_1267_p3 when (icmp_ln321_10_fu_1383_p2(0) = '1') else 
        projectionBuffer_7_V_148_fu_1375_p3;
    projectionBuffer_7_V_150_fu_1403_p3 <= 
        projectionBuffer_7_V_137_fu_1267_p3 when (icmp_ln321_11_fu_1397_p2(0) = '1') else 
        projectionBuffer_7_V_149_fu_1389_p3;
    projectionBuffer_7_V_151_fu_1417_p3 <= 
        projectionBuffer_7_V_137_fu_1267_p3 when (icmp_ln321_12_fu_1411_p2(0) = '1') else 
        projectionBuffer_7_V_150_fu_1403_p3;
    projectionBuffer_7_V_152_fu_1431_p3 <= 
        projectionBuffer_7_V_137_fu_1267_p3 when (icmp_ln321_13_fu_1425_p2(0) = '1') else 
        projectionBuffer_7_V_151_fu_1417_p3;
    projectionBuffer_7_V_153_fu_1439_p3 <= 
        p_Result_1_fu_1332_p5 when (icmp_ln321_7_fu_1341_p2(0) = '1') else 
        projectionBuffer_7_V_138_fu_1274_p3;
    projectionBuffer_7_V_154_fu_1447_p3 <= 
        projectionBuffer_7_V_138_fu_1274_p3 when (icmp_ln321_8_fu_1355_p2(0) = '1') else 
        projectionBuffer_7_V_153_fu_1439_p3;
    projectionBuffer_7_V_155_fu_1455_p3 <= 
        projectionBuffer_7_V_138_fu_1274_p3 when (icmp_ln321_9_fu_1369_p2(0) = '1') else 
        projectionBuffer_7_V_154_fu_1447_p3;
    projectionBuffer_7_V_156_fu_1463_p3 <= 
        projectionBuffer_7_V_138_fu_1274_p3 when (icmp_ln321_10_fu_1383_p2(0) = '1') else 
        projectionBuffer_7_V_155_fu_1455_p3;
    projectionBuffer_7_V_157_fu_1471_p3 <= 
        projectionBuffer_7_V_138_fu_1274_p3 when (icmp_ln321_11_fu_1397_p2(0) = '1') else 
        projectionBuffer_7_V_156_fu_1463_p3;
    projectionBuffer_7_V_158_fu_1479_p3 <= 
        projectionBuffer_7_V_138_fu_1274_p3 when (icmp_ln321_12_fu_1411_p2(0) = '1') else 
        projectionBuffer_7_V_157_fu_1471_p3;
    projectionBuffer_7_V_159_fu_1487_p3 <= 
        projectionBuffer_7_V_138_fu_1274_p3 when (icmp_ln321_13_fu_1425_p2(0) = '1') else 
        projectionBuffer_7_V_158_fu_1479_p3;
    projectionBuffer_7_V_160_fu_1495_p3 <= 
        p_Result_1_fu_1332_p5 when (icmp_ln321_8_fu_1355_p2(0) = '1') else 
        projectionBuffer_7_V_139_fu_1281_p3;
    projectionBuffer_7_V_161_fu_1503_p3 <= 
        projectionBuffer_7_V_139_fu_1281_p3 when (icmp_ln321_9_fu_1369_p2(0) = '1') else 
        projectionBuffer_7_V_160_fu_1495_p3;
    projectionBuffer_7_V_162_fu_1511_p3 <= 
        projectionBuffer_7_V_139_fu_1281_p3 when (icmp_ln321_10_fu_1383_p2(0) = '1') else 
        projectionBuffer_7_V_161_fu_1503_p3;
    projectionBuffer_7_V_163_fu_1519_p3 <= 
        projectionBuffer_7_V_139_fu_1281_p3 when (icmp_ln321_11_fu_1397_p2(0) = '1') else 
        projectionBuffer_7_V_162_fu_1511_p3;
    projectionBuffer_7_V_164_fu_1527_p3 <= 
        projectionBuffer_7_V_139_fu_1281_p3 when (icmp_ln321_12_fu_1411_p2(0) = '1') else 
        projectionBuffer_7_V_163_fu_1519_p3;
    projectionBuffer_7_V_165_fu_1535_p3 <= 
        projectionBuffer_7_V_139_fu_1281_p3 when (icmp_ln321_13_fu_1425_p2(0) = '1') else 
        projectionBuffer_7_V_164_fu_1527_p3;
    projectionBuffer_7_V_166_fu_1543_p3 <= 
        p_Result_1_fu_1332_p5 when (icmp_ln321_9_fu_1369_p2(0) = '1') else 
        projectionBuffer_7_V_140_fu_1288_p3;
    projectionBuffer_7_V_167_fu_1551_p3 <= 
        projectionBuffer_7_V_140_fu_1288_p3 when (icmp_ln321_10_fu_1383_p2(0) = '1') else 
        projectionBuffer_7_V_166_fu_1543_p3;
    projectionBuffer_7_V_168_fu_1559_p3 <= 
        projectionBuffer_7_V_140_fu_1288_p3 when (icmp_ln321_11_fu_1397_p2(0) = '1') else 
        projectionBuffer_7_V_167_fu_1551_p3;
    projectionBuffer_7_V_169_fu_1567_p3 <= 
        projectionBuffer_7_V_140_fu_1288_p3 when (icmp_ln321_12_fu_1411_p2(0) = '1') else 
        projectionBuffer_7_V_168_fu_1559_p3;
    projectionBuffer_7_V_170_fu_1575_p3 <= 
        projectionBuffer_7_V_140_fu_1288_p3 when (icmp_ln321_13_fu_1425_p2(0) = '1') else 
        projectionBuffer_7_V_169_fu_1567_p3;
    projectionBuffer_7_V_171_fu_1583_p3 <= 
        p_Result_1_fu_1332_p5 when (icmp_ln321_10_fu_1383_p2(0) = '1') else 
        projectionBuffer_7_V_141_fu_1295_p3;
    projectionBuffer_7_V_172_fu_1591_p3 <= 
        projectionBuffer_7_V_141_fu_1295_p3 when (icmp_ln321_11_fu_1397_p2(0) = '1') else 
        projectionBuffer_7_V_171_fu_1583_p3;
    projectionBuffer_7_V_173_fu_1599_p3 <= 
        projectionBuffer_7_V_141_fu_1295_p3 when (icmp_ln321_12_fu_1411_p2(0) = '1') else 
        projectionBuffer_7_V_172_fu_1591_p3;
    projectionBuffer_7_V_174_fu_1607_p3 <= 
        projectionBuffer_7_V_141_fu_1295_p3 when (icmp_ln321_13_fu_1425_p2(0) = '1') else 
        projectionBuffer_7_V_173_fu_1599_p3;
    projectionBuffer_7_V_175_fu_1615_p3 <= 
        p_Result_1_fu_1332_p5 when (icmp_ln321_11_fu_1397_p2(0) = '1') else 
        projectionBuffer_7_V_142_fu_1302_p3;
    projectionBuffer_7_V_176_fu_1623_p3 <= 
        projectionBuffer_7_V_142_fu_1302_p3 when (icmp_ln321_12_fu_1411_p2(0) = '1') else 
        projectionBuffer_7_V_175_fu_1615_p3;
    projectionBuffer_7_V_177_fu_1631_p3 <= 
        projectionBuffer_7_V_142_fu_1302_p3 when (icmp_ln321_13_fu_1425_p2(0) = '1') else 
        projectionBuffer_7_V_176_fu_1623_p3;
    projectionBuffer_7_V_178_fu_1639_p3 <= 
        p_Result_1_fu_1332_p5 when (icmp_ln321_12_fu_1411_p2(0) = '1') else 
        projectionBuffer_7_V_143_fu_1309_p3;
    projectionBuffer_7_V_179_fu_1647_p3 <= 
        projectionBuffer_7_V_143_fu_1309_p3 when (icmp_ln321_13_fu_1425_p2(0) = '1') else 
        projectionBuffer_7_V_178_fu_1639_p3;
    projectionBuffer_7_V_180_fu_1655_p3 <= 
        p_Result_1_fu_1332_p5 when (icmp_ln321_13_fu_1425_p2(0) = '1') else 
        projectionBuffer_7_V_144_fu_1316_p3;
    projectionBuffer_7_V_181_fu_1663_p3 <= 
        projectionBuffer_7_V_152_fu_1431_p3 when (savelast_fu_931_p2(0) = '1') else 
        projectionBuffer_7_V_137_fu_1267_p3;
    projectionBuffer_7_V_182_fu_1671_p3 <= 
        projectionBuffer_7_V_159_fu_1487_p3 when (savelast_fu_931_p2(0) = '1') else 
        projectionBuffer_7_V_138_fu_1274_p3;
    projectionBuffer_7_V_183_fu_1679_p3 <= 
        projectionBuffer_7_V_165_fu_1535_p3 when (savelast_fu_931_p2(0) = '1') else 
        projectionBuffer_7_V_139_fu_1281_p3;
    projectionBuffer_7_V_184_fu_1687_p3 <= 
        projectionBuffer_7_V_170_fu_1575_p3 when (savelast_fu_931_p2(0) = '1') else 
        projectionBuffer_7_V_140_fu_1288_p3;
    projectionBuffer_7_V_185_fu_1695_p3 <= 
        projectionBuffer_7_V_174_fu_1607_p3 when (savelast_fu_931_p2(0) = '1') else 
        projectionBuffer_7_V_141_fu_1295_p3;
    projectionBuffer_7_V_186_fu_1703_p3 <= 
        projectionBuffer_7_V_177_fu_1631_p3 when (savelast_fu_931_p2(0) = '1') else 
        projectionBuffer_7_V_142_fu_1302_p3;
    projectionBuffer_7_V_187_fu_1711_p3 <= 
        projectionBuffer_7_V_179_fu_1647_p3 when (savelast_fu_931_p2(0) = '1') else 
        projectionBuffer_7_V_143_fu_1309_p3;
    projectionBuffer_7_V_188_fu_1719_p3 <= 
        projectionBuffer_7_V_180_fu_1655_p3 when (savelast_fu_931_p2(0) = '1') else 
        projectionBuffer_7_V_144_fu_1316_p3;
    projectionBuffer_7_V_189_fu_1934_p3 <= 
        projectionBuffer_7_V_50_load_reg_2561 when (or_ln98_reg_2488_pp0_iter2_reg(0) = '1') else 
        projectionBuffer_7_V_181_reg_2570;
    projectionBuffer_7_V_190_fu_1939_p3 <= 
        projectionBuffer_7_V_40_load_reg_2556 when (or_ln98_reg_2488_pp0_iter2_reg(0) = '1') else 
        projectionBuffer_7_V_182_reg_2575;
    projectionBuffer_7_V_191_fu_1737_p3 <= 
        projectionBuffer_7_V_15_fu_240 when (or_ln98_reg_2488(0) = '1') else 
        projectionBuffer_7_V_183_fu_1679_p3;
    projectionBuffer_7_V_192_fu_1744_p3 <= 
        projectionBuffer_7_V_22_fu_236 when (or_ln98_reg_2488(0) = '1') else 
        projectionBuffer_7_V_184_fu_1687_p3;
    projectionBuffer_7_V_193_fu_1751_p3 <= 
        projectionBuffer_7_V_28_fu_232 when (or_ln98_reg_2488(0) = '1') else 
        projectionBuffer_7_V_185_fu_1695_p3;
    projectionBuffer_7_V_194_fu_1758_p3 <= 
        projectionBuffer_7_V_33_fu_228 when (or_ln98_reg_2488(0) = '1') else 
        projectionBuffer_7_V_186_fu_1703_p3;
    projectionBuffer_7_V_195_fu_1765_p3 <= 
        projectionBuffer_7_V_37_fu_224 when (or_ln98_reg_2488(0) = '1') else 
        projectionBuffer_7_V_187_fu_1711_p3;
    projectionBuffer_7_V_196_fu_1772_p3 <= 
        projectionBuffer_7_V_1_fu_220 when (or_ln98_reg_2488(0) = '1') else 
        projectionBuffer_7_V_188_fu_1719_p3;
    projectionBuffer_7_V_fu_951_p3 <= 
        ap_sig_allocacmp_projectionBuffer_7_V_50_load when (icmp_ln321_fu_945_p2(0) = '1') else 
        p_Result_s_fu_936_p5;
    projfinezadj_V_1_fu_1981_p2 <= (projfinez_V_reg_2595 xor ap_const_lv4_8);
    projfinezadj_V_2_fu_1990_p3 <= 
        sext_ln68_fu_1986_p1 when (trunc_ln681_reg_2585(0) = '1') else 
        projfinezadj_V_fu_1978_p1;
    projfinezadj_V_fu_1978_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(projfinez_V_reg_2595),5));
    ret_V_fu_1885_p2 <= std_logic_vector(unsigned(ap_const_lv5_1) + unsigned(zext_ln215_fu_1881_p1));
    savefirst_fu_854_p2 <= "0" when (nstubfirst_V_fu_767_p34 = ap_const_lv5_0) else "1";
    savelast_fu_931_p2 <= (tmp_3_reg_2512 and icmp_ln113_fu_926_p2);
    select_ln321_1_fu_2109_p3 <= 
        add_ln301_fu_2096_p2 when (trunc_ln209_reg_2438(0) = '1') else 
        outputCandidateMatch_1_nentries_V_write_assign_fu_252;
    select_ln321_fu_2102_p3 <= 
        outputCandidateMatch_0_nentries_V_write_assign_fu_256 when (trunc_ln209_reg_2438(0) = '1') else 
        add_ln301_fu_2096_p2;
        sext_ln321_fu_2087_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln321_fu_2082_p2),64));

        sext_ln68_fu_1986_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(projfinezadj_V_1_fu_1981_p2),5));

    stubbend_V_fu_1968_p4 <= inputStubData_dataarray_data_V_q0(5 downto 3);
    stubfinez_V_fu_1964_p1 <= inputStubData_dataarray_data_V_q0(3 - 1 downto 0);
    table1_address0 <= zext_ln560_fu_2057_p1(8 - 1 downto 0);

    table1_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            table1_ce0 <= ap_const_logic_1;
        else 
            table1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tail_readindex_V_1_fu_1901_p2 <= std_logic_vector(unsigned(t_V_2_reg_2481) + unsigned(ap_const_lv3_1));
    tmp_1_fu_756_p3 <= (trunc_ln209_1_reg_2455 & zbinfirst_V_fu_728_p4);
    tmp_2_fu_805_p3 <= (trunc_ln209_1_reg_2455 & zbinlast_V_fu_750_p2);
    tmp_3_fu_738_p3 <= inputProjectionData_dataarray_data_V_q0(10 downto 10);
    tmp_5_fu_617_p3 <= (trunc_ln209_fu_595_p1 & ap_const_lv7_0);
    tmp_6_fu_656_p3 <= (trunc_ln209_reg_2438 & ap_phi_mux_iprojectiontmp_V_phi_fu_550_p4);
    tmp_7_fu_1922_p5 <= (((ap_const_lv55_0 & trunc_ln209_1_reg_2455) & zbin_V_fu_1833_p4) & istub_V_fu_268);
    trunc_ln209_1_fu_613_p1 <= bx_V(2 - 1 downto 0);
    trunc_ln209_fu_595_p1 <= bx_V(1 - 1 downto 0);
    trunc_ln321_fu_2078_p1 <= addr_index_assign_fu_260(10 - 1 downto 0);
    trunc_ln681_fu_1819_p1 <= qdata_V_fu_900_p10(1 - 1 downto 0);
    trunc_ln89_fu_2092_p1 <= addr_index_assign_fu_260(8 - 1 downto 0);
    xor_ln98_fu_695_p2 <= (ap_phi_mux_moreProjectionsAvailable_0_phi_fu_572_p4 xor ap_const_lv1_1);
    zbin_V_fu_1833_p4 <= qdata_V_fu_900_p10(3 downto 1);
    zbinfirst_V_fu_728_p4 <= inputProjectionData_dataarray_data_V_q0(13 downto 11);
    zbinlast_V_fu_750_p2 <= std_logic_vector(unsigned(zbinfirst_V_fu_728_p4) + unsigned(zext_ln209_1_fu_746_p1));
    zext_ln209_1_fu_746_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_738_p3),3));
    zext_ln209_2_fu_1727_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(savelast_fu_931_p2),3));
    zext_ln209_fu_1323_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(savefirst_reg_2533),3));
    zext_ln215_fu_1881_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(istub_V_fu_268),5));
    zext_ln560_fu_2057_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_2_fu_2050_p3),64));
    zext_ln66_fu_663_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_656_p3),64));
    zext_ln68_fu_1997_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(stubfinez_V_fu_1964_p1),5));
    zext_ln79_fu_625_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_617_p3),10));
    zext_ln887_fu_719_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(iprojection_V_fu_713_p2),8));
    zext_ln891_fu_1891_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(nstubs_V_fu_1823_p4),5));
end behav;
