# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/ProjectionRouter_BARRELPS_BARREL_8_3_0_1/ProjectionRouter_BARRELPS_BARREL_8_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProjectionRouter_BARRELPS_BARREL_8_3_0 || ORIG_REF_NAME==ProjectionRouter_BARRELPS_BARREL_8_3_0} -quiet] -quiet
