# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcvu7p-flvb2104-1-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/PRME_Test/PRME_Test.cache/wt [current_project]
set_property parent.project_path /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/PRME_Test/PRME_Test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /mnt/scratch/rz393/firmware-hls/IntegrationTests/PR_Test/sourceFiles
  /mnt/scratch/rz393/firmware-hls/project/matchenginePl1II120182Trunc/solution1/impl
} [current_project]
set_property ip_output_repo /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/PRME_Test/PRME_Test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/emData/VMStubs_VMSME_L3PHIC22n1_04MOD.dat
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/emData/VMStubs_VMSME_L3PHIC23n1_04MOD.dat
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/emData/TrackletProjections_TPROJ_L1L2G_L3PHIC_04MOD.dat
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/emData/VMStubs_VMSME_L3PHIC20n1_04MOD.dat
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/emData/VMStubs_VMSME_L3PHIC24n1_04MOD.dat
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/emData/TrackletProjections_TPROJ_L5L6B_L3PHIC_04MOD.dat
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/emData/TrackletProjections_TPROJ_L1L2I_L3PHIC_04MOD.dat
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/emData/VMStubs_VMSME_L3PHIC18n1_04MOD.dat
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/emData/VMStubs_VMSME_L3PHIC21n1_04MOD.dat
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/emData/TrackletProjections_TPROJ_L5L6D_L3PHIC_04MOD.dat
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/emData/TrackletProjections_TPROJ_L1L2F_L3PHIC_04MOD.dat
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/emData/VMStubs_VMSME_L3PHIC19n1_04MOD.dat
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/emData/VMStubs_VMSME_L3PHIC17n1_04MOD.dat
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/emData/TrackletProjections_TPROJ_L5L6C_L3PHIC_04MOD.dat
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/emData/TrackletProjections_TPROJ_L1L2J_L3PHIC_04MOD.dat
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/emData/TrackletProjections_TPROJ_L1L2H_L3PHIC_04MOD.dat
}
read_verilog -library xil_defaultlib -sv {
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/sourceFiles/SectorProcessor.v
  /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/sourceFiles/SectorProcessor_test.v
}
read_verilog -library xil_defaultlib {
  /mnt/scratch/rz393/firmware-hls_1/TrackletAlgorithm/Memory.v
  /mnt/scratch/rz393/firmware-hls/TrackletAlgorithm/MemoryBinned.v
}
read_ip -quiet /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/PRME_Test/PRME_Test.srcs/sources_1/ip/ProjectionRouter_BARRELPS_BARREL_8_3_0_1/ProjectionRouter_BARRELPS_BARREL_8_3_0.xci
set_property used_in_implementation false [get_files -all /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/PRME_Test/PRME_Test.srcs/sources_1/ip/ProjectionRouter_BARRELPS_BARREL_8_3_0_1/constraints/ProjectionRouterTop_ooc.xdc]

read_ip -quiet /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/PRME_Test/PRME_Test.srcs/sources_1/ip/MatchEngineTopL1_0_2/MatchEngineTopL1_0.xci
set_property used_in_implementation false [get_files -all /mnt/scratch/rz393/firmware-hls_1/IntegrationTests/PRME_Test/PRME_Test/PRME_Test.srcs/sources_1/ip/MatchEngineTopL1_0_2/constraints/MatchEngineTopL1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top SectorProcessor_test -part xcvu7p-flvb2104-1-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SectorProcessor_test.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file SectorProcessor_test_utilization_synth.rpt -pb SectorProcessor_test_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
